apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daveFrontend.fullname" . }}
  labels:
    {{- include "daveFrontend.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "daveFrontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "daveFrontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: dave-hazelcast
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            {{- if .Values.existingConfigMap }}
            name: {{ .Values.existingConfigMap }}
            {{- else }}
            name: {{ include "daveFrontend.fullname" . }}
            {{- end }}
            defaultMode: 420
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.app.server.port | quote}}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.spring.profile.active }}
            - name: LOG_LEVEL_ROOT
              value: {{ .Values.app.log.level.root }}
            - name: SPRING_CLOUD_GATEWAY_ACTUATOR_VERBOSE_ENABLED
              value: {{ .Values.app.spring.cloud.gateway.actuator.verbose.enabled | quote }}
            {{- if .Values.app.auth.enabled }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_PROVIDER
              value: {{ .Values.app.auth.client.registration.keycloak.provider }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE
              value: {{ .Values.app.auth.client.registration.keycloak.authorization_grant_type }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID  
              value: {{ .Values.app.auth.client.registration.keycloak.client_id }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.app.auth.client.registration.keycloak.client_secret }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE
              value: {{ .Values.app.auth.client.registration.keycloak.scope }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_MYKEYCLOAK_ISSUER_URI
              value: {{ .Values.app.auth.client.provider.mykeycloak.issuer_uri }}
            {{- else }}
            - name: SPRING_AUTOCONFIGURE_EXCLUDE 
              value: org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientAutoConfiguration
            {{- end }}
            {{- with .Values.app.spring.routes }}
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.app.spring.hazelcast }}
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnvVars }}
            {{- range $name, $value := . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "daveFrontend.fullname" . }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}  
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /deployments/config
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
