/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuswertungMessstelleWithFileDTO,
  MessstelleAuswertungDTO,
  MessstelleAuswertungOptionsDTO,
} from '../models/index';
import {
    AuswertungMessstelleWithFileDTOFromJSON,
    AuswertungMessstelleWithFileDTOToJSON,
    MessstelleAuswertungDTOFromJSON,
    MessstelleAuswertungDTOToJSON,
    MessstelleAuswertungOptionsDTOFromJSON,
    MessstelleAuswertungOptionsDTOToJSON,
} from '../models/index';

export interface GetAuswertungMessstelleRequest {
    messstelleAuswertungOptionsDTO: MessstelleAuswertungOptionsDTO;
}

/**
 * 
 */
export class AuswertungControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllVisibleMessstellenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MessstelleAuswertungDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auswertung/messstelle/getAllVisibleMessstellen`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MessstelleAuswertungDTOFromJSON));
    }

    /**
     */
    async getAllVisibleMessstellen(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MessstelleAuswertungDTO>> {
        const response = await this.getAllVisibleMessstellenRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getAuswertungMessstelleRaw(requestParameters: GetAuswertungMessstelleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuswertungMessstelleWithFileDTO>> {
        if (requestParameters['messstelleAuswertungOptionsDTO'] == null) {
            throw new runtime.RequiredError(
                'messstelleAuswertungOptionsDTO',
                'Required parameter "messstelleAuswertungOptionsDTO" was null or undefined when calling getAuswertungMessstelle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auswertung/messstelle`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessstelleAuswertungOptionsDTOToJSON(requestParameters['messstelleAuswertungOptionsDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuswertungMessstelleWithFileDTOFromJSON(jsonValue));
    }

    /**
     */
    async getAuswertungMessstelle(requestParameters: GetAuswertungMessstelleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuswertungMessstelleWithFileDTO> {
        const response = await this.getAuswertungMessstelleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
