/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  LadeAuswertungSpitzenstundeDTO,
  LadeAuswertungVisumDTO,
  LadeAuswertungZaehlstelleKoordinateDTO,
  Zeitblock,
} from "../models/index";

import {
  LadeAuswertungSpitzenstundeDTOFromJSON,
  LadeAuswertungSpitzenstundeDTOToJSON,
  LadeAuswertungVisumDTOFromJSON,
  LadeAuswertungVisumDTOToJSON,
  LadeAuswertungZaehlstelleKoordinateDTOFromJSON,
  LadeAuswertungZaehlstelleKoordinateDTOToJSON,
  ZeitblockFromJSON,
  ZeitblockToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface LadeAuswertungSpitzenstundeRequest {
  zaehlstelleNummer: string;
  zaehlart: LadeAuswertungSpitzenstundeZaehlartEnum;
  zaehldatum: Date;
  zeitblock: Zeitblock;
  zeitauswahl: string;
}

export interface LadeAuswertungVisumRequest {
  jahr: number;
  monat: number;
}

/**
 *
 */
export class EaiControllerApi extends runtime.BaseAPI {
  /**
   */
  async ladeAuswertungSpitzenstundeRaw(
    requestParameters: LadeAuswertungSpitzenstundeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<LadeAuswertungSpitzenstundeDTO>>> {
    if (requestParameters["zaehlstelleNummer"] == null) {
      throw new runtime.RequiredError(
        "zaehlstelleNummer",
        'Required parameter "zaehlstelleNummer" was null or undefined when calling ladeAuswertungSpitzenstunde().'
      );
    }

    if (requestParameters["zaehlart"] == null) {
      throw new runtime.RequiredError(
        "zaehlart",
        'Required parameter "zaehlart" was null or undefined when calling ladeAuswertungSpitzenstunde().'
      );
    }

    if (requestParameters["zaehldatum"] == null) {
      throw new runtime.RequiredError(
        "zaehldatum",
        'Required parameter "zaehldatum" was null or undefined when calling ladeAuswertungSpitzenstunde().'
      );
    }

    if (requestParameters["zeitblock"] == null) {
      throw new runtime.RequiredError(
        "zeitblock",
        'Required parameter "zeitblock" was null or undefined when calling ladeAuswertungSpitzenstunde().'
      );
    }

    if (requestParameters["zeitauswahl"] == null) {
      throw new runtime.RequiredError(
        "zeitauswahl",
        'Required parameter "zeitauswahl" was null or undefined when calling ladeAuswertungSpitzenstunde().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["zaehlstelleNummer"] != null) {
      queryParameters["zaehlstelle_nummer"] =
        requestParameters["zaehlstelleNummer"];
    }

    if (requestParameters["zaehlart"] != null) {
      queryParameters["zaehlart"] = requestParameters["zaehlart"];
    }

    if (requestParameters["zaehldatum"] != null) {
      queryParameters["zaehldatum"] = (requestParameters["zaehldatum"] as any)
        .toISOString()
        .substring(0, 10);
    }

    if (requestParameters["zeitblock"] != null) {
      queryParameters["zeitblock"] = requestParameters["zeitblock"];
    }

    if (requestParameters["zeitauswahl"] != null) {
      queryParameters["zeitauswahl"] = requestParameters["zeitauswahl"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/lade-auswertung-spitzenstunde`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LadeAuswertungSpitzenstundeDTOFromJSON)
    );
  }

  /**
   */
  async ladeAuswertungSpitzenstunde(
    requestParameters: LadeAuswertungSpitzenstundeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<LadeAuswertungSpitzenstundeDTO>> {
    const response = await this.ladeAuswertungSpitzenstundeRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async ladeAuswertungVisumRaw(
    requestParameters: LadeAuswertungVisumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LadeAuswertungVisumDTO>> {
    if (requestParameters["jahr"] == null) {
      throw new runtime.RequiredError(
        "jahr",
        'Required parameter "jahr" was null or undefined when calling ladeAuswertungVisum().'
      );
    }

    if (requestParameters["monat"] == null) {
      throw new runtime.RequiredError(
        "monat",
        'Required parameter "monat" was null or undefined when calling ladeAuswertungVisum().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["jahr"] != null) {
      queryParameters["jahr"] = requestParameters["jahr"];
    }

    if (requestParameters["monat"] != null) {
      queryParameters["monat"] = requestParameters["monat"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/lade-auswertung-visum`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LadeAuswertungVisumDTOFromJSON(jsonValue)
    );
  }

  /**
   */
  async ladeAuswertungVisum(
    requestParameters: LadeAuswertungVisumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LadeAuswertungVisumDTO> {
    const response = await this.ladeAuswertungVisumRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async ladeAuswertungZaehlstellenKoordinateRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<
    runtime.ApiResponse<Array<LadeAuswertungZaehlstelleKoordinateDTO>>
  > {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/lade-auswertung-zaehlstellen-koordinate`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(LadeAuswertungZaehlstelleKoordinateDTOFromJSON)
    );
  }

  /**
   */
  async ladeAuswertungZaehlstellenKoordinate(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<LadeAuswertungZaehlstelleKoordinateDTO>> {
    const response =
      await this.ladeAuswertungZaehlstellenKoordinateRaw(initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const LadeAuswertungSpitzenstundeZaehlartEnum = {
  N: "N",
  H: "H",
  Q: "Q",
  Q2: "Q_",
  Qb: "QB",
  Qh: "QH",
  Qi: "QI",
  Qs: "QS",
  Qt: "QT",
  Qr: "QR",
  R: "R",
  Qjs: "QJS",
  Fjs: "FJS",
  Qu: "QU",
  T: "T",
  Tk: "TK",
} as const;
export type LadeAuswertungSpitzenstundeZaehlartEnum =
  (typeof LadeAuswertungSpitzenstundeZaehlartEnum)[keyof typeof LadeAuswertungSpitzenstundeZaehlartEnum];
