/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  GenerateMessstellePdfRequest,
  GeneratePdfAuswertungRequest,
  GeneratePdfReportRequest,
  GenerateZaehlungPdfRequest,
} from "../models/index";

import {
  GenerateMessstellePdfRequestFromJSON,
  GenerateMessstellePdfRequestToJSON,
  GeneratePdfAuswertungRequestFromJSON,
  GeneratePdfAuswertungRequestToJSON,
  GeneratePdfReportRequestFromJSON,
  GeneratePdfReportRequestToJSON,
  GenerateZaehlungPdfRequestFromJSON,
  GenerateZaehlungPdfRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface GenerateMessstellePdfOperationRequest {
  fachId: string;
  charttype: string;
  generateMessstellePdfRequest: GenerateMessstellePdfRequest;
}

export interface GeneratePdfAuswertungOperationRequest {
  generatePdfAuswertungRequest: GeneratePdfAuswertungRequest;
}

export interface GeneratePdfReportOperationRequest {
  generatePdfReportRequest: GeneratePdfReportRequest;
}

export interface GenerateZaehlungPdfOperationRequest {
  fachId: string;
  charttype: string;
  generateZaehlungPdfRequest: GenerateZaehlungPdfRequest;
}

/**
 *
 */
export class GeneratePdfControllerApi extends runtime.BaseAPI {
  /**
   */
  async generateMessstellePdfRaw(
    requestParameters: GenerateMessstellePdfOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["fachId"] == null) {
      throw new runtime.RequiredError(
        "fachId",
        'Required parameter "fachId" was null or undefined when calling generateMessstellePdf().'
      );
    }

    if (requestParameters["charttype"] == null) {
      throw new runtime.RequiredError(
        "charttype",
        'Required parameter "charttype" was null or undefined when calling generateMessstellePdf().'
      );
    }

    if (requestParameters["generateMessstellePdfRequest"] == null) {
      throw new runtime.RequiredError(
        "generateMessstellePdfRequest",
        'Required parameter "generateMessstellePdfRequest" was null or undefined when calling generateMessstellePdf().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["fachId"] != null) {
      queryParameters["fach_id"] = requestParameters["fachId"];
    }

    if (requestParameters["charttype"] != null) {
      queryParameters["charttype"] = requestParameters["charttype"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/messstelle`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GenerateMessstellePdfRequestToJSON(
          requestParameters["generateMessstellePdfRequest"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generateMessstellePdf(
    requestParameters: GenerateMessstellePdfOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generateMessstellePdfRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async generatePdfAuswertungRaw(
    requestParameters: GeneratePdfAuswertungOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["generatePdfAuswertungRequest"] == null) {
      throw new runtime.RequiredError(
        "generatePdfAuswertungRequest",
        'Required parameter "generatePdfAuswertungRequest" was null or undefined when calling generatePdfAuswertung().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/auswertung`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GeneratePdfAuswertungRequestToJSON(
          requestParameters["generatePdfAuswertungRequest"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generatePdfAuswertung(
    requestParameters: GeneratePdfAuswertungOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generatePdfAuswertungRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async generatePdfReportRaw(
    requestParameters: GeneratePdfReportOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["generatePdfReportRequest"] == null) {
      throw new runtime.RequiredError(
        "generatePdfReportRequest",
        'Required parameter "generatePdfReportRequest" was null or undefined when calling generatePdfReport().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/report`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GeneratePdfReportRequestToJSON(
          requestParameters["generatePdfReportRequest"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generatePdfReport(
    requestParameters: GeneratePdfReportOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generatePdfReportRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async generateZaehlungPdfRaw(
    requestParameters: GenerateZaehlungPdfOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["fachId"] == null) {
      throw new runtime.RequiredError(
        "fachId",
        'Required parameter "fachId" was null or undefined when calling generateZaehlungPdf().'
      );
    }

    if (requestParameters["charttype"] == null) {
      throw new runtime.RequiredError(
        "charttype",
        'Required parameter "charttype" was null or undefined when calling generateZaehlungPdf().'
      );
    }

    if (requestParameters["generateZaehlungPdfRequest"] == null) {
      throw new runtime.RequiredError(
        "generateZaehlungPdfRequest",
        'Required parameter "generateZaehlungPdfRequest" was null or undefined when calling generateZaehlungPdf().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["fachId"] != null) {
      queryParameters["fach_id"] = requestParameters["fachId"];
    }

    if (requestParameters["charttype"] != null) {
      queryParameters["charttype"] = requestParameters["charttype"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/zaehlung`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GenerateZaehlungPdfRequestToJSON(
          requestParameters["generateZaehlungPdfRequest"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generateZaehlungPdf(
    requestParameters: GenerateZaehlungPdfOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generateZaehlungPdfRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
