/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  GeneratePdf1Request,
  GeneratePdfAuswertungRequest,
  GeneratePdfReportRequest,
  GeneratePdfRequest,
} from "../models/index";

import {
  GeneratePdf1RequestFromJSON,
  GeneratePdf1RequestToJSON,
  GeneratePdfAuswertungRequestFromJSON,
  GeneratePdfAuswertungRequestToJSON,
  GeneratePdfReportRequestFromJSON,
  GeneratePdfReportRequestToJSON,
  GeneratePdfRequestFromJSON,
  GeneratePdfRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface GeneratePdfOperationRequest {
  fachId: string;
  charttype: string;
  generatePdfRequest: GeneratePdfRequest;
}

export interface GeneratePdf1OperationRequest {
  fachId: string;
  charttype: string;
  generatePdf1Request: GeneratePdf1Request;
}

export interface GeneratePdfAuswertungOperationRequest {
  generatePdfAuswertungRequest: GeneratePdfAuswertungRequest;
}

export interface GeneratePdfReportOperationRequest {
  generatePdfReportRequest: GeneratePdfReportRequest;
}

/**
 *
 */
export class GeneratePdfControllerApi extends runtime.BaseAPI {
  /**
   */
  async generatePdfRaw(
    requestParameters: GeneratePdfOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["fachId"] == null) {
      throw new runtime.RequiredError(
        "fachId",
        'Required parameter "fachId" was null or undefined when calling generatePdf().'
      );
    }

    if (requestParameters["charttype"] == null) {
      throw new runtime.RequiredError(
        "charttype",
        'Required parameter "charttype" was null or undefined when calling generatePdf().'
      );
    }

    if (requestParameters["generatePdfRequest"] == null) {
      throw new runtime.RequiredError(
        "generatePdfRequest",
        'Required parameter "generatePdfRequest" was null or undefined when calling generatePdf().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["fachId"] != null) {
      queryParameters["fach_id"] = requestParameters["fachId"];
    }

    if (requestParameters["charttype"] != null) {
      queryParameters["charttype"] = requestParameters["charttype"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/zaehlung`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GeneratePdfRequestToJSON(requestParameters["generatePdfRequest"]),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generatePdf(
    requestParameters: GeneratePdfOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generatePdfRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async generatePdf1Raw(
    requestParameters: GeneratePdf1OperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["fachId"] == null) {
      throw new runtime.RequiredError(
        "fachId",
        'Required parameter "fachId" was null or undefined when calling generatePdf1().'
      );
    }

    if (requestParameters["charttype"] == null) {
      throw new runtime.RequiredError(
        "charttype",
        'Required parameter "charttype" was null or undefined when calling generatePdf1().'
      );
    }

    if (requestParameters["generatePdf1Request"] == null) {
      throw new runtime.RequiredError(
        "generatePdf1Request",
        'Required parameter "generatePdf1Request" was null or undefined when calling generatePdf1().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["fachId"] != null) {
      queryParameters["fach_id"] = requestParameters["fachId"];
    }

    if (requestParameters["charttype"] != null) {
      queryParameters["charttype"] = requestParameters["charttype"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/messstelle`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GeneratePdf1RequestToJSON(
          requestParameters["generatePdf1Request"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generatePdf1(
    requestParameters: GeneratePdf1OperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generatePdf1Raw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async generatePdfAuswertungRaw(
    requestParameters: GeneratePdfAuswertungOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["generatePdfAuswertungRequest"] == null) {
      throw new runtime.RequiredError(
        "generatePdfAuswertungRequest",
        'Required parameter "generatePdfAuswertungRequest" was null or undefined when calling generatePdfAuswertung().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/auswertung`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GeneratePdfAuswertungRequestToJSON(
          requestParameters["generatePdfAuswertungRequest"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generatePdfAuswertung(
    requestParameters: GeneratePdfAuswertungOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generatePdfAuswertungRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async generatePdfReportRaw(
    requestParameters: GeneratePdfReportOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<string>> {
    if (requestParameters["generatePdfReportRequest"] == null) {
      throw new runtime.RequiredError(
        "generatePdfReportRequest",
        'Required parameter "generatePdfReportRequest" was null or undefined when calling generatePdfReport().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/generate-pdf/report`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: GeneratePdfReportRequestToJSON(
          requestParameters["generatePdfReportRequest"]
        ),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<string>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async generatePdfReport(
    requestParameters: GeneratePdfReportOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<string> {
    const response = await this.generatePdfReportRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
