/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  EntityModelHochrechnungsfaktor,
  HochrechnungsfaktorRequestBody,
  PagedModelEntityModelHochrechnungsfaktor,
} from "../models/index";

import {
  EntityModelHochrechnungsfaktorFromJSON,
  EntityModelHochrechnungsfaktorToJSON,
  HochrechnungsfaktorRequestBodyFromJSON,
  HochrechnungsfaktorRequestBodyToJSON,
  PagedModelEntityModelHochrechnungsfaktorFromJSON,
  PagedModelEntityModelHochrechnungsfaktorToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface DeleteItemResourceHochrechnungsfaktorDeleteRequest {
  id: string;
}

export interface GetCollectionResourceHochrechnungsfaktorGetRequest {
  page?: number;
  size?: number;
  sort?: Array<string>;
}

export interface GetItemResourceHochrechnungsfaktorGetRequest {
  id: string;
}

export interface PatchItemResourceHochrechnungsfaktorPatchRequest {
  id: string;
  hochrechnungsfaktorRequestBody: HochrechnungsfaktorRequestBody;
}

export interface PostCollectionResourceHochrechnungsfaktorPostRequest {
  hochrechnungsfaktorRequestBody: HochrechnungsfaktorRequestBody;
}

export interface PutItemResourceHochrechnungsfaktorPutRequest {
  id: string;
  hochrechnungsfaktorRequestBody: HochrechnungsfaktorRequestBody;
}

/**
 *
 */
export class HochrechnungsfaktorEntityControllerApi extends runtime.BaseAPI {
  /**
   * delete-hochrechnungsfaktor
   */
  async deleteItemResourceHochrechnungsfaktorDeleteRaw(
    requestParameters: DeleteItemResourceHochrechnungsfaktorDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling deleteItemResourceHochrechnungsfaktorDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/hochrechnungsfaktors/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * delete-hochrechnungsfaktor
   */
  async deleteItemResourceHochrechnungsfaktorDelete(
    requestParameters: DeleteItemResourceHochrechnungsfaktorDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteItemResourceHochrechnungsfaktorDeleteRaw(
      requestParameters,
      initOverrides
    );
  }

  /**
   * get-hochrechnungsfaktor
   */
  async getCollectionResourceHochrechnungsfaktorGetRaw(
    requestParameters: GetCollectionResourceHochrechnungsfaktorGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PagedModelEntityModelHochrechnungsfaktor>> {
    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["size"] != null) {
      queryParameters["size"] = requestParameters["size"];
    }

    if (requestParameters["sort"] != null) {
      queryParameters["sort"] = requestParameters["sort"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/hochrechnungsfaktors`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PagedModelEntityModelHochrechnungsfaktorFromJSON(jsonValue)
    );
  }

  /**
   * get-hochrechnungsfaktor
   */
  async getCollectionResourceHochrechnungsfaktorGet(
    requestParameters: GetCollectionResourceHochrechnungsfaktorGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PagedModelEntityModelHochrechnungsfaktor> {
    const response = await this.getCollectionResourceHochrechnungsfaktorGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * get-hochrechnungsfaktor
   */
  async getItemResourceHochrechnungsfaktorGetRaw(
    requestParameters: GetItemResourceHochrechnungsfaktorGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelHochrechnungsfaktor>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getItemResourceHochrechnungsfaktorGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/hochrechnungsfaktors/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelHochrechnungsfaktorFromJSON(jsonValue)
    );
  }

  /**
   * get-hochrechnungsfaktor
   */
  async getItemResourceHochrechnungsfaktorGet(
    requestParameters: GetItemResourceHochrechnungsfaktorGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelHochrechnungsfaktor> {
    const response = await this.getItemResourceHochrechnungsfaktorGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * patch-hochrechnungsfaktor
   */
  async patchItemResourceHochrechnungsfaktorPatchRaw(
    requestParameters: PatchItemResourceHochrechnungsfaktorPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelHochrechnungsfaktor>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling patchItemResourceHochrechnungsfaktorPatch().'
      );
    }

    if (requestParameters["hochrechnungsfaktorRequestBody"] == null) {
      throw new runtime.RequiredError(
        "hochrechnungsfaktorRequestBody",
        'Required parameter "hochrechnungsfaktorRequestBody" was null or undefined when calling patchItemResourceHochrechnungsfaktorPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/hochrechnungsfaktors/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: HochrechnungsfaktorRequestBodyToJSON(
          requestParameters["hochrechnungsfaktorRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelHochrechnungsfaktorFromJSON(jsonValue)
    );
  }

  /**
   * patch-hochrechnungsfaktor
   */
  async patchItemResourceHochrechnungsfaktorPatch(
    requestParameters: PatchItemResourceHochrechnungsfaktorPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelHochrechnungsfaktor | null | undefined> {
    const response = await this.patchItemResourceHochrechnungsfaktorPatchRaw(
      requestParameters,
      initOverrides
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }

  /**
   * create-hochrechnungsfaktor
   */
  async postCollectionResourceHochrechnungsfaktorPostRaw(
    requestParameters: PostCollectionResourceHochrechnungsfaktorPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelHochrechnungsfaktor>> {
    if (requestParameters["hochrechnungsfaktorRequestBody"] == null) {
      throw new runtime.RequiredError(
        "hochrechnungsfaktorRequestBody",
        'Required parameter "hochrechnungsfaktorRequestBody" was null or undefined when calling postCollectionResourceHochrechnungsfaktorPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/hochrechnungsfaktors`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: HochrechnungsfaktorRequestBodyToJSON(
          requestParameters["hochrechnungsfaktorRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelHochrechnungsfaktorFromJSON(jsonValue)
    );
  }

  /**
   * create-hochrechnungsfaktor
   */
  async postCollectionResourceHochrechnungsfaktorPost(
    requestParameters: PostCollectionResourceHochrechnungsfaktorPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelHochrechnungsfaktor> {
    const response =
      await this.postCollectionResourceHochrechnungsfaktorPostRaw(
        requestParameters,
        initOverrides
      );
    return await response.value();
  }

  /**
   * update-hochrechnungsfaktor
   */
  async putItemResourceHochrechnungsfaktorPutRaw(
    requestParameters: PutItemResourceHochrechnungsfaktorPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelHochrechnungsfaktor>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling putItemResourceHochrechnungsfaktorPut().'
      );
    }

    if (requestParameters["hochrechnungsfaktorRequestBody"] == null) {
      throw new runtime.RequiredError(
        "hochrechnungsfaktorRequestBody",
        'Required parameter "hochrechnungsfaktorRequestBody" was null or undefined when calling putItemResourceHochrechnungsfaktorPut().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/hochrechnungsfaktors/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: HochrechnungsfaktorRequestBodyToJSON(
          requestParameters["hochrechnungsfaktorRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelHochrechnungsfaktorFromJSON(jsonValue)
    );
  }

  /**
   * update-hochrechnungsfaktor
   */
  async putItemResourceHochrechnungsfaktorPut(
    requestParameters: PutItemResourceHochrechnungsfaktorPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelHochrechnungsfaktor | null | undefined> {
    const response = await this.putItemResourceHochrechnungsfaktorPutRaw(
      requestParameters,
      initOverrides
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 201:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }
}
