/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InfoMessageDTO } from "../models/index";

import { InfoMessageDTOFromJSON, InfoMessageDTOToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface SaveInfoMessageRequest {
  infoMessageDTO: InfoMessageDTO;
}

/**
 *
 */
export class InfoMessageControllerApi extends runtime.BaseAPI {
  /**
   */
  async getActiveInfoMessageRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<InfoMessageDTO>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/infomessage/active`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      InfoMessageDTOFromJSON(jsonValue)
    );
  }

  /**
   */
  async getActiveInfoMessage(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<InfoMessageDTO> {
    const response = await this.getActiveInfoMessageRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getAllInfoMessagesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<InfoMessageDTO>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/infomessage/all`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(InfoMessageDTOFromJSON)
    );
  }

  /**
   */
  async getAllInfoMessages(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<InfoMessageDTO>> {
    const response = await this.getAllInfoMessagesRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async saveInfoMessageRaw(
    requestParameters: SaveInfoMessageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<InfoMessageDTO>>> {
    if (requestParameters["infoMessageDTO"] == null) {
      throw new runtime.RequiredError(
        "infoMessageDTO",
        'Required parameter "infoMessageDTO" was null or undefined when calling saveInfoMessage().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/infomessage/save`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: InfoMessageDTOToJSON(requestParameters["infoMessageDTO"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(InfoMessageDTOFromJSON)
    );
  }

  /**
   */
  async saveInfoMessage(
    requestParameters: SaveInfoMessageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<InfoMessageDTO>> {
    const response = await this.saveInfoMessageRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async setAllInfoMessagesInactiveRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<object>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/infomessage/set-all-inactive`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async setAllInfoMessagesInactive(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<object> {
    const response = await this.setAllInfoMessagesInactiveRaw(initOverrides);
    return await response.value();
  }
}
