/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  CollectionModelEntityModelKalendertag,
  EntityModelKalendertag,
} from "../models/index";

import {
  CollectionModelEntityModelKalendertagFromJSON,
  CollectionModelEntityModelKalendertagToJSON,
  EntityModelKalendertagFromJSON,
  EntityModelKalendertagToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ExecuteSearchKalendertagGetRequest {
  startDateIncluded?: Date;
  endDateIncluded?: Date;
  tagestypen?: Array<ExecuteSearchKalendertagGetTagestypenEnum>;
}

export interface ExecuteSearchKalendertagGet1Request {
  excludedDates?: Array<Date>;
  latestDate?: Date;
}

export interface ExecuteSearchKalendertagGet2Request {
  datum?: Date;
}

/**
 *
 */
export class KalendertagSearchControllerApi extends runtime.BaseAPI {
  /**
   */
  async executeSearchKalendertagGetRaw(
    requestParameters: ExecuteSearchKalendertagGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<number>> {
    const queryParameters: any = {};

    if (requestParameters["startDateIncluded"] != null) {
      queryParameters["startDateIncluded"] = (
        requestParameters["startDateIncluded"] as any
      )
        .toISOString()
        .substring(0, 10);
    }

    if (requestParameters["endDateIncluded"] != null) {
      queryParameters["endDateIncluded"] = (
        requestParameters["endDateIncluded"] as any
      )
        .toISOString()
        .substring(0, 10);
    }

    if (requestParameters["tagestypen"] != null) {
      queryParameters["tagestypen"] = requestParameters["tagestypen"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/kalendertags/search/countAllByDatumGreaterThanEqualAndDatumLessThanEqualAndTagestypIn`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<number>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async executeSearchKalendertagGet(
    requestParameters: ExecuteSearchKalendertagGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<number> {
    const response = await this.executeSearchKalendertagGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async executeSearchKalendertagGet1Raw(
    requestParameters: ExecuteSearchKalendertagGet1Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<CollectionModelEntityModelKalendertag>> {
    const queryParameters: any = {};

    if (requestParameters["excludedDates"] != null) {
      queryParameters["excludedDates"] = requestParameters["excludedDates"];
    }

    if (requestParameters["latestDate"] != null) {
      queryParameters["latestDate"] = (requestParameters["latestDate"] as any)
        .toISOString()
        .substring(0, 10);
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/kalendertags/search/findAllByDatumNotInAndDatumIsBefore`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CollectionModelEntityModelKalendertagFromJSON(jsonValue)
    );
  }

  /**
   */
  async executeSearchKalendertagGet1(
    requestParameters: ExecuteSearchKalendertagGet1Request = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<CollectionModelEntityModelKalendertag> {
    const response = await this.executeSearchKalendertagGet1Raw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async executeSearchKalendertagGet2Raw(
    requestParameters: ExecuteSearchKalendertagGet2Request,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelKalendertag>> {
    const queryParameters: any = {};

    if (requestParameters["datum"] != null) {
      queryParameters["datum"] = (requestParameters["datum"] as any)
        .toISOString()
        .substring(0, 10);
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/kalendertags/search/findByDatum`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelKalendertagFromJSON(jsonValue)
    );
  }

  /**
   */
  async executeSearchKalendertagGet2(
    requestParameters: ExecuteSearchKalendertagGet2Request = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelKalendertag> {
    const response = await this.executeSearchKalendertagGet2Raw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async executeSearchKalendertagGet3Raw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelKalendertag>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/kalendertags/search/findByNextStartDateToLoadUnauffaelligeTageIsTrue`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelKalendertagFromJSON(jsonValue)
    );
  }

  /**
   */
  async executeSearchKalendertagGet3(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelKalendertag> {
    const response = await this.executeSearchKalendertagGet3Raw(initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const ExecuteSearchKalendertagGetTagestypenEnum = {
  Unspecified: "UNSPECIFIED",
  WerktagDiMiDo: "WERKTAG_DI_MI_DO",
  WerktagMoFr: "WERKTAG_MO_FR",
  Samstag: "SAMSTAG",
  SonntagFeiertag: "SONNTAG_FEIERTAG",
  WerktagFerien: "WERKTAG_FERIEN",
  MoSo: "MO_SO",
} as const;
export type ExecuteSearchKalendertagGetTagestypenEnum =
  (typeof ExecuteSearchKalendertagGetTagestypenEnum)[keyof typeof ExecuteSearchKalendertagGetTagestypenEnum];
