/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DocumentDto } from "../models/index";

import { DocumentDtoFromJSON, DocumentDtoToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface LoadLageplanRequest {
  mstId: string;
}

/**
 *
 */
export class LageplanControllerApi extends runtime.BaseAPI {
  /**
   */
  async loadLageplanRaw(
    requestParameters: LoadLageplanRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<DocumentDto>> {
    if (requestParameters["mstId"] == null) {
      throw new runtime.RequiredError(
        "mstId",
        'Required parameter "mstId" was null or undefined when calling loadLageplan().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["mstId"] != null) {
      queryParameters["mstId"] = requestParameters["mstId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/lageplan`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DocumentDtoFromJSON(jsonValue)
    );
  }

  /**
   */
  async loadLageplan(
    requestParameters: LoadLageplanRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<DocumentDto> {
    const response = await this.loadLageplanRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
