/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelMessstelle,
  MessstelleRequestBody,
  PagedModelEntityModelMessstelle,
} from '../models/index';
import {
    EntityModelMessstelleFromJSON,
    EntityModelMessstelleToJSON,
    MessstelleRequestBodyFromJSON,
    MessstelleRequestBodyToJSON,
    PagedModelEntityModelMessstelleFromJSON,
    PagedModelEntityModelMessstelleToJSON,
} from '../models/index';

export interface DeleteItemResourceMessstelleDeleteRequest {
    id: string;
}

export interface GetCollectionResourceMessstelleGetRequest {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceMessstelleGetRequest {
    id: string;
}

export interface PatchItemResourceMessstellePatchRequest {
    id: string;
    messstelleRequestBody: MessstelleRequestBody;
}

export interface PostCollectionResourceMessstellePostRequest {
    messstelleRequestBody: MessstelleRequestBody;
}

export interface PutItemResourceMessstellePutRequest {
    id: string;
    messstelleRequestBody: MessstelleRequestBody;
}

/**
 * 
 */
export class MessstelleEntityControllerApi extends runtime.BaseAPI {

    /**
     * delete-messstelle
     */
    async deleteItemResourceMessstelleDeleteRaw(requestParameters: DeleteItemResourceMessstelleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceMessstelleDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/messstelles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-messstelle
     */
    async deleteItemResourceMessstelleDelete(requestParameters: DeleteItemResourceMessstelleDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceMessstelleDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * get-messstelle
     */
    async getCollectionResourceMessstelleGetRaw(requestParameters: GetCollectionResourceMessstelleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelMessstelle>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/messstelles`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelMessstelleFromJSON(jsonValue));
    }

    /**
     * get-messstelle
     */
    async getCollectionResourceMessstelleGet(requestParameters: GetCollectionResourceMessstelleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelMessstelle> {
        const response = await this.getCollectionResourceMessstelleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get-messstelle
     */
    async getItemResourceMessstelleGetRaw(requestParameters: GetItemResourceMessstelleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelMessstelle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceMessstelleGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/messstelles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelMessstelleFromJSON(jsonValue));
    }

    /**
     * get-messstelle
     */
    async getItemResourceMessstelleGet(requestParameters: GetItemResourceMessstelleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelMessstelle> {
        const response = await this.getItemResourceMessstelleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * patch-messstelle
     */
    async patchItemResourceMessstellePatchRaw(requestParameters: PatchItemResourceMessstellePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelMessstelle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceMessstellePatch().'
            );
        }

        if (requestParameters['messstelleRequestBody'] == null) {
            throw new runtime.RequiredError(
                'messstelleRequestBody',
                'Required parameter "messstelleRequestBody" was null or undefined when calling patchItemResourceMessstellePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/messstelles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MessstelleRequestBodyToJSON(requestParameters['messstelleRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelMessstelleFromJSON(jsonValue));
    }

    /**
     * patch-messstelle
     */
    async patchItemResourceMessstellePatch(requestParameters: PatchItemResourceMessstellePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelMessstelle | null | undefined > {
        const response = await this.patchItemResourceMessstellePatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * create-messstelle
     */
    async postCollectionResourceMessstellePostRaw(requestParameters: PostCollectionResourceMessstellePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelMessstelle>> {
        if (requestParameters['messstelleRequestBody'] == null) {
            throw new runtime.RequiredError(
                'messstelleRequestBody',
                'Required parameter "messstelleRequestBody" was null or undefined when calling postCollectionResourceMessstellePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/messstelles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessstelleRequestBodyToJSON(requestParameters['messstelleRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelMessstelleFromJSON(jsonValue));
    }

    /**
     * create-messstelle
     */
    async postCollectionResourceMessstellePost(requestParameters: PostCollectionResourceMessstellePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelMessstelle> {
        const response = await this.postCollectionResourceMessstellePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * update-messstelle
     */
    async putItemResourceMessstellePutRaw(requestParameters: PutItemResourceMessstellePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelMessstelle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceMessstellePut().'
            );
        }

        if (requestParameters['messstelleRequestBody'] == null) {
            throw new runtime.RequiredError(
                'messstelleRequestBody',
                'Required parameter "messstelleRequestBody" was null or undefined when calling putItemResourceMessstellePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/messstelles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MessstelleRequestBodyToJSON(requestParameters['messstelleRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelMessstelleFromJSON(jsonValue));
    }

    /**
     * update-messstelle
     */
    async putItemResourceMessstellePut(requestParameters: PutItemResourceMessstellePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelMessstelle | null | undefined > {
        const response = await this.putItemResourceMessstellePutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
