/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BackendIdDTO,
  EditMessstelleDTO,
  MessstelleOverviewDTO,
  ReadMessstelleInfoDTO,
} from '../models/index';
import {
    BackendIdDTOFromJSON,
    BackendIdDTOToJSON,
    EditMessstelleDTOFromJSON,
    EditMessstelleDTOToJSON,
    MessstelleOverviewDTOFromJSON,
    MessstelleOverviewDTOToJSON,
    ReadMessstelleInfoDTOFromJSON,
    ReadMessstelleInfoDTOToJSON,
} from '../models/index';

export interface GetBearbeiteMessstelleRequest {
    id: string;
}

export interface ReadMessstelleInfoByMstIdRequest {
    mstid: string;
    id: string;
}

export interface UpdateMessstelleRequest {
    editMessstelleDTO: EditMessstelleDTO;
}

/**
 * 
 */
export class MessstelleControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllMessstellenForOverviewRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MessstelleOverviewDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/messstelle/loadAllMessstellenForOverview`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MessstelleOverviewDTOFromJSON));
    }

    /**
     */
    async getAllMessstellenForOverview(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MessstelleOverviewDTO>> {
        const response = await this.getAllMessstellenForOverviewRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getBearbeiteMessstelleRaw(requestParameters: GetBearbeiteMessstelleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EditMessstelleDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBearbeiteMessstelle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/messstelle/edit`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EditMessstelleDTOFromJSON(jsonValue));
    }

    /**
     */
    async getBearbeiteMessstelle(requestParameters: GetBearbeiteMessstelleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EditMessstelleDTO> {
        const response = await this.getBearbeiteMessstelleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async readMessstelleInfoByMstIdRaw(requestParameters: ReadMessstelleInfoByMstIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadMessstelleInfoDTO>> {
        if (requestParameters['mstid'] == null) {
            throw new runtime.RequiredError(
                'mstid',
                'Required parameter "mstid" was null or undefined when calling readMessstelleInfoByMstId().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readMessstelleInfoByMstId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mstid'] != null) {
            queryParameters['mstid'] = requestParameters['mstid'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/messstelle/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadMessstelleInfoDTOFromJSON(jsonValue));
    }

    /**
     */
    async readMessstelleInfoByMstId(requestParameters: ReadMessstelleInfoByMstIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadMessstelleInfoDTO> {
        const response = await this.readMessstelleInfoByMstIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateMessstelleRaw(requestParameters: UpdateMessstelleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackendIdDTO>> {
        if (requestParameters['editMessstelleDTO'] == null) {
            throw new runtime.RequiredError(
                'editMessstelleDTO',
                'Required parameter "editMessstelleDTO" was null or undefined when calling updateMessstelle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/messstelle/update`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EditMessstelleDTOToJSON(requestParameters['editMessstelleDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackendIdDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateMessstelle(requestParameters: UpdateMessstelleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackendIdDTO> {
        const response = await this.updateMessstelleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
