/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  EntityModelOptionsmenueSettings,
  OptionsmenueSettingsRequestBody,
  PagedModelEntityModelOptionsmenueSettings,
} from "../models/index";

import {
  EntityModelOptionsmenueSettingsFromJSON,
  EntityModelOptionsmenueSettingsToJSON,
  OptionsmenueSettingsRequestBodyFromJSON,
  OptionsmenueSettingsRequestBodyToJSON,
  PagedModelEntityModelOptionsmenueSettingsFromJSON,
  PagedModelEntityModelOptionsmenueSettingsToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface DeleteItemResourceOptionsmenuesettingsDeleteRequest {
  id: string;
}

export interface GetCollectionResourceOptionsmenuesettingsGetRequest {
  page?: number;
  size?: number;
  sort?: Array<string>;
}

export interface GetItemResourceOptionsmenuesettingsGetRequest {
  id: string;
}

export interface PatchItemResourceOptionsmenuesettingsPatchRequest {
  id: string;
  optionsmenueSettingsRequestBody: OptionsmenueSettingsRequestBody;
}

export interface PostCollectionResourceOptionsmenuesettingsPostRequest {
  optionsmenueSettingsRequestBody: OptionsmenueSettingsRequestBody;
}

export interface PutItemResourceOptionsmenuesettingsPutRequest {
  id: string;
  optionsmenueSettingsRequestBody: OptionsmenueSettingsRequestBody;
}

/**
 *
 */
export class OptionsmenueSettingsEntityControllerApi extends runtime.BaseAPI {
  /**
   * delete-optionsmenuesettings
   */
  async deleteItemResourceOptionsmenuesettingsDeleteRaw(
    requestParameters: DeleteItemResourceOptionsmenuesettingsDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling deleteItemResourceOptionsmenuesettingsDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/optionsmenueSettingses/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * delete-optionsmenuesettings
   */
  async deleteItemResourceOptionsmenuesettingsDelete(
    requestParameters: DeleteItemResourceOptionsmenuesettingsDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteItemResourceOptionsmenuesettingsDeleteRaw(
      requestParameters,
      initOverrides
    );
  }

  /**
   * get-optionsmenuesettings
   */
  async getCollectionResourceOptionsmenuesettingsGetRaw(
    requestParameters: GetCollectionResourceOptionsmenuesettingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PagedModelEntityModelOptionsmenueSettings>> {
    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["size"] != null) {
      queryParameters["size"] = requestParameters["size"];
    }

    if (requestParameters["sort"] != null) {
      queryParameters["sort"] = requestParameters["sort"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/optionsmenueSettingses`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PagedModelEntityModelOptionsmenueSettingsFromJSON(jsonValue)
    );
  }

  /**
   * get-optionsmenuesettings
   */
  async getCollectionResourceOptionsmenuesettingsGet(
    requestParameters: GetCollectionResourceOptionsmenuesettingsGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PagedModelEntityModelOptionsmenueSettings> {
    const response = await this.getCollectionResourceOptionsmenuesettingsGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * get-optionsmenuesettings
   */
  async getItemResourceOptionsmenuesettingsGetRaw(
    requestParameters: GetItemResourceOptionsmenuesettingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelOptionsmenueSettings>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getItemResourceOptionsmenuesettingsGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/optionsmenueSettingses/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelOptionsmenueSettingsFromJSON(jsonValue)
    );
  }

  /**
   * get-optionsmenuesettings
   */
  async getItemResourceOptionsmenuesettingsGet(
    requestParameters: GetItemResourceOptionsmenuesettingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelOptionsmenueSettings> {
    const response = await this.getItemResourceOptionsmenuesettingsGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * patch-optionsmenuesettings
   */
  async patchItemResourceOptionsmenuesettingsPatchRaw(
    requestParameters: PatchItemResourceOptionsmenuesettingsPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelOptionsmenueSettings>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling patchItemResourceOptionsmenuesettingsPatch().'
      );
    }

    if (requestParameters["optionsmenueSettingsRequestBody"] == null) {
      throw new runtime.RequiredError(
        "optionsmenueSettingsRequestBody",
        'Required parameter "optionsmenueSettingsRequestBody" was null or undefined when calling patchItemResourceOptionsmenuesettingsPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/optionsmenueSettingses/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: OptionsmenueSettingsRequestBodyToJSON(
          requestParameters["optionsmenueSettingsRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelOptionsmenueSettingsFromJSON(jsonValue)
    );
  }

  /**
   * patch-optionsmenuesettings
   */
  async patchItemResourceOptionsmenuesettingsPatch(
    requestParameters: PatchItemResourceOptionsmenuesettingsPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelOptionsmenueSettings | null | undefined> {
    const response = await this.patchItemResourceOptionsmenuesettingsPatchRaw(
      requestParameters,
      initOverrides
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }

  /**
   * create-optionsmenuesettings
   */
  async postCollectionResourceOptionsmenuesettingsPostRaw(
    requestParameters: PostCollectionResourceOptionsmenuesettingsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelOptionsmenueSettings>> {
    if (requestParameters["optionsmenueSettingsRequestBody"] == null) {
      throw new runtime.RequiredError(
        "optionsmenueSettingsRequestBody",
        'Required parameter "optionsmenueSettingsRequestBody" was null or undefined when calling postCollectionResourceOptionsmenuesettingsPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/optionsmenueSettingses`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: OptionsmenueSettingsRequestBodyToJSON(
          requestParameters["optionsmenueSettingsRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelOptionsmenueSettingsFromJSON(jsonValue)
    );
  }

  /**
   * create-optionsmenuesettings
   */
  async postCollectionResourceOptionsmenuesettingsPost(
    requestParameters: PostCollectionResourceOptionsmenuesettingsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelOptionsmenueSettings> {
    const response =
      await this.postCollectionResourceOptionsmenuesettingsPostRaw(
        requestParameters,
        initOverrides
      );
    return await response.value();
  }

  /**
   * update-optionsmenuesettings
   */
  async putItemResourceOptionsmenuesettingsPutRaw(
    requestParameters: PutItemResourceOptionsmenuesettingsPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelOptionsmenueSettings>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling putItemResourceOptionsmenuesettingsPut().'
      );
    }

    if (requestParameters["optionsmenueSettingsRequestBody"] == null) {
      throw new runtime.RequiredError(
        "optionsmenueSettingsRequestBody",
        'Required parameter "optionsmenueSettingsRequestBody" was null or undefined when calling putItemResourceOptionsmenuesettingsPut().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/optionsmenueSettingses/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: OptionsmenueSettingsRequestBodyToJSON(
          requestParameters["optionsmenueSettingsRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelOptionsmenueSettingsFromJSON(jsonValue)
    );
  }

  /**
   * update-optionsmenuesettings
   */
  async putItemResourceOptionsmenuesettingsPut(
    requestParameters: PutItemResourceOptionsmenuesettingsPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelOptionsmenueSettings | null | undefined> {
    const response = await this.putItemResourceOptionsmenuesettingsPutRaw(
      requestParameters,
      initOverrides
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 201:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }
}
