/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelPkwEinheit,
} from '../models/index';
import {
    EntityModelPkwEinheitFromJSON,
    EntityModelPkwEinheitToJSON,
} from '../models/index';

/**
 * 
 */
export class PkwEinheitSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchPkweinheitGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPkwEinheit>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pkwEinheits/search/findTopByOrderByCreatedTimeDesc`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPkwEinheitFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchPkweinheitGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPkwEinheit> {
        const response = await this.executeSearchPkweinheitGetRaw(initOverrides);
        return await response.value();
    }

}
