/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PkwEinheitDTO,
} from '../models/index';
import {
    PkwEinheitDTOFromJSON,
    PkwEinheitDTOToJSON,
} from '../models/index';

export interface SavePkwEinheitRequest {
    pkwEinheitDTO: PkwEinheitDTO;
}

/**
 * 
 */
export class PkwEinheitControllerApi extends runtime.BaseAPI {

    /**
     */
    async getLatestPkwEinheitenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PkwEinheitDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pkw-einheit/latest`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PkwEinheitDTOFromJSON(jsonValue));
    }

    /**
     */
    async getLatestPkwEinheiten(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PkwEinheitDTO> {
        const response = await this.getLatestPkwEinheitenRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async savePkwEinheitRaw(requestParameters: SavePkwEinheitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PkwEinheitDTO>> {
        if (requestParameters['pkwEinheitDTO'] == null) {
            throw new runtime.RequiredError(
                'pkwEinheitDTO',
                'Required parameter "pkwEinheitDTO" was null or undefined when calling savePkwEinheit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pkw-einheit/save`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PkwEinheitDTOToJSON(requestParameters['pkwEinheitDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PkwEinheitDTOFromJSON(jsonValue));
    }

    /**
     */
    async savePkwEinheit(requestParameters: SavePkwEinheitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PkwEinheitDTO> {
        const response = await this.savePkwEinheitRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
