/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  EntityModelPkwEinheit,
  PagedModelEntityModelPkwEinheit,
  PkwEinheitRequestBody,
} from "../models/index";

import {
  EntityModelPkwEinheitFromJSON,
  EntityModelPkwEinheitToJSON,
  PagedModelEntityModelPkwEinheitFromJSON,
  PagedModelEntityModelPkwEinheitToJSON,
  PkwEinheitRequestBodyFromJSON,
  PkwEinheitRequestBodyToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface DeleteItemResourcePkweinheitDeleteRequest {
  id: string;
}

export interface GetCollectionResourcePkweinheitGetRequest {
  page?: number;
  size?: number;
  sort?: Array<string>;
}

export interface GetItemResourcePkweinheitGetRequest {
  id: string;
}

export interface PatchItemResourcePkweinheitPatchRequest {
  id: string;
  pkwEinheitRequestBody: PkwEinheitRequestBody;
}

export interface PostCollectionResourcePkweinheitPostRequest {
  pkwEinheitRequestBody: PkwEinheitRequestBody;
}

export interface PutItemResourcePkweinheitPutRequest {
  id: string;
  pkwEinheitRequestBody: PkwEinheitRequestBody;
}

/**
 *
 */
export class PkwEinheitEntityControllerApi extends runtime.BaseAPI {
  /**
   * delete-pkweinheit
   */
  async deleteItemResourcePkweinheitDeleteRaw(
    requestParameters: DeleteItemResourcePkweinheitDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling deleteItemResourcePkweinheitDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/pkwEinheits/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * delete-pkweinheit
   */
  async deleteItemResourcePkweinheitDelete(
    requestParameters: DeleteItemResourcePkweinheitDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteItemResourcePkweinheitDeleteRaw(
      requestParameters,
      initOverrides
    );
  }

  /**
   * get-pkweinheit
   */
  async getCollectionResourcePkweinheitGetRaw(
    requestParameters: GetCollectionResourcePkweinheitGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PagedModelEntityModelPkwEinheit>> {
    const queryParameters: any = {};

    if (requestParameters["page"] != null) {
      queryParameters["page"] = requestParameters["page"];
    }

    if (requestParameters["size"] != null) {
      queryParameters["size"] = requestParameters["size"];
    }

    if (requestParameters["sort"] != null) {
      queryParameters["sort"] = requestParameters["sort"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/pkwEinheits`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PagedModelEntityModelPkwEinheitFromJSON(jsonValue)
    );
  }

  /**
   * get-pkweinheit
   */
  async getCollectionResourcePkweinheitGet(
    requestParameters: GetCollectionResourcePkweinheitGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PagedModelEntityModelPkwEinheit> {
    const response = await this.getCollectionResourcePkweinheitGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * get-pkweinheit
   */
  async getItemResourcePkweinheitGetRaw(
    requestParameters: GetItemResourcePkweinheitGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelPkwEinheit>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getItemResourcePkweinheitGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/pkwEinheits/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelPkwEinheitFromJSON(jsonValue)
    );
  }

  /**
   * get-pkweinheit
   */
  async getItemResourcePkweinheitGet(
    requestParameters: GetItemResourcePkweinheitGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelPkwEinheit> {
    const response = await this.getItemResourcePkweinheitGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * patch-pkweinheit
   */
  async patchItemResourcePkweinheitPatchRaw(
    requestParameters: PatchItemResourcePkweinheitPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelPkwEinheit>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling patchItemResourcePkweinheitPatch().'
      );
    }

    if (requestParameters["pkwEinheitRequestBody"] == null) {
      throw new runtime.RequiredError(
        "pkwEinheitRequestBody",
        'Required parameter "pkwEinheitRequestBody" was null or undefined when calling patchItemResourcePkweinheitPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/pkwEinheits/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: PkwEinheitRequestBodyToJSON(
          requestParameters["pkwEinheitRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelPkwEinheitFromJSON(jsonValue)
    );
  }

  /**
   * patch-pkweinheit
   */
  async patchItemResourcePkweinheitPatch(
    requestParameters: PatchItemResourcePkweinheitPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelPkwEinheit | null | undefined> {
    const response = await this.patchItemResourcePkweinheitPatchRaw(
      requestParameters,
      initOverrides
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }

  /**
   * create-pkweinheit
   */
  async postCollectionResourcePkweinheitPostRaw(
    requestParameters: PostCollectionResourcePkweinheitPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelPkwEinheit>> {
    if (requestParameters["pkwEinheitRequestBody"] == null) {
      throw new runtime.RequiredError(
        "pkwEinheitRequestBody",
        'Required parameter "pkwEinheitRequestBody" was null or undefined when calling postCollectionResourcePkweinheitPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/pkwEinheits`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: PkwEinheitRequestBodyToJSON(
          requestParameters["pkwEinheitRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelPkwEinheitFromJSON(jsonValue)
    );
  }

  /**
   * create-pkweinheit
   */
  async postCollectionResourcePkweinheitPost(
    requestParameters: PostCollectionResourcePkweinheitPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelPkwEinheit> {
    const response = await this.postCollectionResourcePkweinheitPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * update-pkweinheit
   */
  async putItemResourcePkweinheitPutRaw(
    requestParameters: PutItemResourcePkweinheitPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EntityModelPkwEinheit>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling putItemResourcePkweinheitPut().'
      );
    }

    if (requestParameters["pkwEinheitRequestBody"] == null) {
      throw new runtime.RequiredError(
        "pkwEinheitRequestBody",
        'Required parameter "pkwEinheitRequestBody" was null or undefined when calling putItemResourcePkweinheitPut().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/pkwEinheits/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"]))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: PkwEinheitRequestBodyToJSON(
          requestParameters["pkwEinheitRequestBody"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EntityModelPkwEinheitFromJSON(jsonValue)
    );
  }

  /**
   * update-pkweinheit
   */
  async putItemResourcePkweinheitPut(
    requestParameters: PutItemResourcePkweinheitPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EntityModelPkwEinheit | null | undefined> {
    const response = await this.putItemResourcePkweinheitPutRaw(
      requestParameters,
      initOverrides
    );
    switch (response.raw.status) {
      case 200:
        return await response.value();
      case 201:
        return await response.value();
      case 204:
        return null;
      default:
        return await response.value();
    }
  }
}
