/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  BackendIdDTO,
  BearbeiteZaehlungDTO,
  DienstleisterDTO,
  ExternalZaehlungDTO,
  OpenZaehlungDTO,
  UpdateStatusDTO,
} from "../models/index";

import {
  BackendIdDTOFromJSON,
  BackendIdDTOToJSON,
  BearbeiteZaehlungDTOFromJSON,
  BearbeiteZaehlungDTOToJSON,
  DienstleisterDTOFromJSON,
  DienstleisterDTOToJSON,
  ExternalZaehlungDTOFromJSON,
  ExternalZaehlungDTOToJSON,
  OpenZaehlungDTOFromJSON,
  OpenZaehlungDTOToJSON,
  UpdateStatusDTOFromJSON,
  UpdateStatusDTOToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface DeleteZaehlungRequest {
  zaehlungId: string;
}

export interface SaveExternalZaehlungRequest {
  externalZaehlungDTO: ExternalZaehlungDTO;
}

export interface SaveZaehlungRequest {
  zaehlstelleId: string;
  bearbeiteZaehlungDTO: BearbeiteZaehlungDTO;
}

export interface UpdateDienstleisterkennungRequest {
  zaehlungId: string;
  dienstleisterDTO: DienstleisterDTO;
}

export interface UpdateStatusRequest {
  updateStatusDTO: UpdateStatusDTO;
}

/**
 *
 */
export class ZaehlungControllerApi extends runtime.BaseAPI {
  /**
   */
  async deleteZaehlungRaw(
    requestParameters: DeleteZaehlungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<boolean>> {
    if (requestParameters["zaehlungId"] == null) {
      throw new runtime.RequiredError(
        "zaehlungId",
        'Required parameter "zaehlungId" was null or undefined when calling deleteZaehlung().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["zaehlungId"] != null) {
      queryParameters["zaehlung_id"] = requestParameters["zaehlungId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/zaehlung/delete`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<boolean>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async deleteZaehlung(
    requestParameters: DeleteZaehlungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<boolean> {
    const response = await this.deleteZaehlungRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async getZaehlungenForExternalRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<ExternalZaehlungDTO>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/zaehlung/getZaehlungenForExternal`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(ExternalZaehlungDTOFromJSON)
    );
  }

  /**
   */
  async getZaehlungenForExternal(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<ExternalZaehlungDTO>> {
    const response = await this.getZaehlungenForExternalRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async loadAllOpenZaehlungenRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<OpenZaehlungDTO>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/zaehlung/loadAllOpenZaehlungen`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(OpenZaehlungDTOFromJSON)
    );
  }

  /**
   */
  async loadAllOpenZaehlungen(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<OpenZaehlungDTO>> {
    const response = await this.loadAllOpenZaehlungenRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async saveExternalZaehlungRaw(
    requestParameters: SaveExternalZaehlungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<BackendIdDTO>> {
    if (requestParameters["externalZaehlungDTO"] == null) {
      throw new runtime.RequiredError(
        "externalZaehlungDTO",
        'Required parameter "externalZaehlungDTO" was null or undefined when calling saveExternalZaehlung().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/zaehlung/saveExternal`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: ExternalZaehlungDTOToJSON(
          requestParameters["externalZaehlungDTO"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BackendIdDTOFromJSON(jsonValue)
    );
  }

  /**
   */
  async saveExternalZaehlung(
    requestParameters: SaveExternalZaehlungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<BackendIdDTO> {
    const response = await this.saveExternalZaehlungRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async saveZaehlungRaw(
    requestParameters: SaveZaehlungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<BackendIdDTO>> {
    if (requestParameters["zaehlstelleId"] == null) {
      throw new runtime.RequiredError(
        "zaehlstelleId",
        'Required parameter "zaehlstelleId" was null or undefined when calling saveZaehlung().'
      );
    }

    if (requestParameters["bearbeiteZaehlungDTO"] == null) {
      throw new runtime.RequiredError(
        "bearbeiteZaehlungDTO",
        'Required parameter "bearbeiteZaehlungDTO" was null or undefined when calling saveZaehlung().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["zaehlstelleId"] != null) {
      queryParameters["zaehlstelle_id"] = requestParameters["zaehlstelleId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/zaehlung/save`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: BearbeiteZaehlungDTOToJSON(
          requestParameters["bearbeiteZaehlungDTO"]
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BackendIdDTOFromJSON(jsonValue)
    );
  }

  /**
   */
  async saveZaehlung(
    requestParameters: SaveZaehlungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<BackendIdDTO> {
    const response = await this.saveZaehlungRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async updateDienstleisterkennungRaw(
    requestParameters: UpdateDienstleisterkennungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<BackendIdDTO>> {
    if (requestParameters["zaehlungId"] == null) {
      throw new runtime.RequiredError(
        "zaehlungId",
        'Required parameter "zaehlungId" was null or undefined when calling updateDienstleisterkennung().'
      );
    }

    if (requestParameters["dienstleisterDTO"] == null) {
      throw new runtime.RequiredError(
        "dienstleisterDTO",
        'Required parameter "dienstleisterDTO" was null or undefined when calling updateDienstleisterkennung().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["zaehlungId"] != null) {
      queryParameters["zaehlung_id"] = requestParameters["zaehlungId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/zaehlung/updateDienstleisterkennung`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: DienstleisterDTOToJSON(requestParameters["dienstleisterDTO"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BackendIdDTOFromJSON(jsonValue)
    );
  }

  /**
   */
  async updateDienstleisterkennung(
    requestParameters: UpdateDienstleisterkennungRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<BackendIdDTO> {
    const response = await this.updateDienstleisterkennungRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   */
  async updateStatusRaw(
    requestParameters: UpdateStatusRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<BackendIdDTO>> {
    if (requestParameters["updateStatusDTO"] == null) {
      throw new runtime.RequiredError(
        "updateStatusDTO",
        'Required parameter "updateStatusDTO" was null or undefined when calling updateStatus().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/zaehlung/updateStatus`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateStatusDTOToJSON(requestParameters["updateStatusDTO"]),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BackendIdDTOFromJSON(jsonValue)
    );
  }

  /**
   */
  async updateStatus(
    requestParameters: UpdateStatusRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<BackendIdDTO> {
    const response = await this.updateStatusRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
