/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HochrechnungsfaktorDTO } from './HochrechnungsfaktorDTO';
import {
    HochrechnungsfaktorDTOFromJSON,
    HochrechnungsfaktorDTOFromJSONTyped,
    HochrechnungsfaktorDTOToJSON,
    HochrechnungsfaktorDTOToJSONTyped,
} from './HochrechnungsfaktorDTO';
import type { ZeitintervallDTO } from './ZeitintervallDTO';
import {
    ZeitintervallDTOFromJSON,
    ZeitintervallDTOFromJSONTyped,
    ZeitintervallDTOToJSON,
    ZeitintervallDTOToJSONTyped,
} from './ZeitintervallDTO';

/**
 * 
 * @export
 * @interface BearbeiteVerkehrsbeziehungDTO
 */
export interface BearbeiteVerkehrsbeziehungDTO {
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    id?: string;
    /**
     * 
     * @type {Array<ZeitintervallDTO>}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    zeitintervalle?: Array<ZeitintervallDTO>;
    /**
     * 
     * @type {HochrechnungsfaktorDTO}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    hochrechnungsfaktor?: HochrechnungsfaktorDTO;
    /**
     * 
     * @type {boolean}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    isKreuzung?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    von?: number;
    /**
     * 
     * @type {number}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    nach?: number;
    /**
     * 
     * @type {number}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    knotenarm?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    hinein?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    heraus?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    vorbei?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    strassenseite?: BearbeiteVerkehrsbeziehungDTOStrassenseiteEnum;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    vonknotvonstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    nachknotvonstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    vonStrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    vonknotennachstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    nachknotnachstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof BearbeiteVerkehrsbeziehungDTO
     */
    nachStrnr?: string;
}


/**
 * @export
 */
export const BearbeiteVerkehrsbeziehungDTOStrassenseiteEnum = {
    N: 'N',
    No: 'NO',
    O: 'O',
    So: 'SO',
    S: 'S',
    Sw: 'SW',
    W: 'W',
    Nw: 'NW'
} as const;
export type BearbeiteVerkehrsbeziehungDTOStrassenseiteEnum = typeof BearbeiteVerkehrsbeziehungDTOStrassenseiteEnum[keyof typeof BearbeiteVerkehrsbeziehungDTOStrassenseiteEnum];


/**
 * Check if a given object implements the BearbeiteVerkehrsbeziehungDTO interface.
 */
export function instanceOfBearbeiteVerkehrsbeziehungDTO(value: object): value is BearbeiteVerkehrsbeziehungDTO {
    return true;
}

export function BearbeiteVerkehrsbeziehungDTOFromJSON(json: any): BearbeiteVerkehrsbeziehungDTO {
    return BearbeiteVerkehrsbeziehungDTOFromJSONTyped(json, false);
}

export function BearbeiteVerkehrsbeziehungDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BearbeiteVerkehrsbeziehungDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'zeitintervalle': json['zeitintervalle'] == null ? undefined : ((json['zeitintervalle'] as Array<any>).map(ZeitintervallDTOFromJSON)),
        'hochrechnungsfaktor': json['hochrechnungsfaktor'] == null ? undefined : HochrechnungsfaktorDTOFromJSON(json['hochrechnungsfaktor']),
        'isKreuzung': json['isKreuzung'] == null ? undefined : json['isKreuzung'],
        'von': json['von'] == null ? undefined : json['von'],
        'nach': json['nach'] == null ? undefined : json['nach'],
        'knotenarm': json['knotenarm'] == null ? undefined : json['knotenarm'],
        'hinein': json['hinein'] == null ? undefined : json['hinein'],
        'heraus': json['heraus'] == null ? undefined : json['heraus'],
        'vorbei': json['vorbei'] == null ? undefined : json['vorbei'],
        'strassenseite': json['strassenseite'] == null ? undefined : json['strassenseite'],
        'vonknotvonstrnr': json['vonknotvonstrnr'] == null ? undefined : json['vonknotvonstrnr'],
        'nachknotvonstrnr': json['nachknotvonstrnr'] == null ? undefined : json['nachknotvonstrnr'],
        'vonStrnr': json['von_strnr'] == null ? undefined : json['von_strnr'],
        'vonknotennachstrnr': json['vonknotennachstrnr'] == null ? undefined : json['vonknotennachstrnr'],
        'nachknotnachstrnr': json['nachknotnachstrnr'] == null ? undefined : json['nachknotnachstrnr'],
        'nachStrnr': json['nach_strnr'] == null ? undefined : json['nach_strnr'],
    };
}

export function BearbeiteVerkehrsbeziehungDTOToJSON(json: any): BearbeiteVerkehrsbeziehungDTO {
    return BearbeiteVerkehrsbeziehungDTOToJSONTyped(json, false);
}

export function BearbeiteVerkehrsbeziehungDTOToJSONTyped(value?: BearbeiteVerkehrsbeziehungDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'zeitintervalle': value['zeitintervalle'] == null ? undefined : ((value['zeitintervalle'] as Array<any>).map(ZeitintervallDTOToJSON)),
        'hochrechnungsfaktor': HochrechnungsfaktorDTOToJSON(value['hochrechnungsfaktor']),
        'isKreuzung': value['isKreuzung'],
        'von': value['von'],
        'nach': value['nach'],
        'knotenarm': value['knotenarm'],
        'hinein': value['hinein'],
        'heraus': value['heraus'],
        'vorbei': value['vorbei'],
        'strassenseite': value['strassenseite'],
        'vonknotvonstrnr': value['vonknotvonstrnr'],
        'nachknotvonstrnr': value['nachknotvonstrnr'],
        'von_strnr': value['vonStrnr'],
        'vonknotennachstrnr': value['vonknotennachstrnr'],
        'nachknotnachstrnr': value['nachknotnachstrnr'],
        'nach_strnr': value['nachStrnr'],
    };
}

