/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface BearbeiteKnotenarmDTO
 */
export interface BearbeiteKnotenarmDTO {
  /**
   *
   * @type {number}
   * @memberof BearbeiteKnotenarmDTO
   */
  nummer?: number;
  /**
   *
   * @type {string}
   * @memberof BearbeiteKnotenarmDTO
   */
  strassenname?: string;
}

/**
 * Check if a given object implements the BearbeiteKnotenarmDTO interface.
 */
export function instanceOfBearbeiteKnotenarmDTO(
  value: object
): value is BearbeiteKnotenarmDTO {
  return true;
}

export function BearbeiteKnotenarmDTOFromJSON(
  json: any
): BearbeiteKnotenarmDTO {
  return BearbeiteKnotenarmDTOFromJSONTyped(json, false);
}

export function BearbeiteKnotenarmDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BearbeiteKnotenarmDTO {
  if (json == null) {
    return json;
  }
  return {
    nummer: json["nummer"] == null ? undefined : json["nummer"],
    strassenname:
      json["strassenname"] == null ? undefined : json["strassenname"],
  };
}

export function BearbeiteKnotenarmDTOToJSON(json: any): BearbeiteKnotenarmDTO {
  return BearbeiteKnotenarmDTOToJSONTyped(json, false);
}

export function BearbeiteKnotenarmDTOToJSONTyped(
  value?: BearbeiteKnotenarmDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    nummer: value["nummer"],
    strassenname: value["strassenname"],
  };
}
