/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BelastungsplanDataDTO
 */
export interface BelastungsplanDataDTO {
    /**
     * 
     * @type {string}
     * @memberof BelastungsplanDataDTO
     */
    label?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BelastungsplanDataDTO
     */
    filled?: boolean;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof BelastungsplanDataDTO
     */
    values?: Array<Array<number>>;
    /**
     * 
     * @type {boolean}
     * @memberof BelastungsplanDataDTO
     */
    percent?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof BelastungsplanDataDTO
     */
    sumIn?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BelastungsplanDataDTO
     */
    sumOut?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BelastungsplanDataDTO
     */
    sum?: Array<number>;
}

/**
 * Check if a given object implements the BelastungsplanDataDTO interface.
 */
export function instanceOfBelastungsplanDataDTO(value: object): value is BelastungsplanDataDTO {
    return true;
}

export function BelastungsplanDataDTOFromJSON(json: any): BelastungsplanDataDTO {
    return BelastungsplanDataDTOFromJSONTyped(json, false);
}

export function BelastungsplanDataDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BelastungsplanDataDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'] == null ? undefined : json['label'],
        'filled': json['filled'] == null ? undefined : json['filled'],
        'values': json['values'] == null ? undefined : json['values'],
        'percent': json['percent'] == null ? undefined : json['percent'],
        'sumIn': json['sumIn'] == null ? undefined : json['sumIn'],
        'sumOut': json['sumOut'] == null ? undefined : json['sumOut'],
        'sum': json['sum'] == null ? undefined : json['sum'],
    };
}

export function BelastungsplanDataDTOToJSON(json: any): BelastungsplanDataDTO {
    return BelastungsplanDataDTOToJSONTyped(json, false);
}

export function BelastungsplanDataDTOToJSONTyped(value?: BelastungsplanDataDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'filled': value['filled'],
        'values': value['values'],
        'percent': value['percent'],
        'sumIn': value['sumIn'],
        'sumOut': value['sumOut'],
        'sum': value['sum'],
    };
}

