/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KnotenarmValue } from "./KnotenarmValue";

import { mapValues } from "../runtime";
import {
  KnotenarmValueFromJSON,
  KnotenarmValueFromJSONTyped,
  KnotenarmValueToJSON,
  KnotenarmValueToJSONTyped,
} from "./KnotenarmValue";

/**
 *
 * @export
 * @interface BelastungsplanQuDataDTO
 */
export interface BelastungsplanQuDataDTO {
  /**
   *
   * @type {string}
   * @memberof BelastungsplanQuDataDTO
   */
  label: string;
  /**
   *
   * @type {boolean}
   * @memberof BelastungsplanQuDataDTO
   */
  filled: boolean;
  /**
   *
   * @type {Array<KnotenarmValue>}
   * @memberof BelastungsplanQuDataDTO
   */
  valuesKnotenarme: Array<KnotenarmValue>;
}

/**
 * Check if a given object implements the BelastungsplanQuDataDTO interface.
 */
export function instanceOfBelastungsplanQuDataDTO(
  value: object
): value is BelastungsplanQuDataDTO {
  if (!("label" in value) || value["label"] === undefined) return false;
  if (!("filled" in value) || value["filled"] === undefined) return false;
  if (!("valuesKnotenarme" in value) || value["valuesKnotenarme"] === undefined)
    return false;
  return true;
}

export function BelastungsplanQuDataDTOFromJSON(
  json: any
): BelastungsplanQuDataDTO {
  return BelastungsplanQuDataDTOFromJSONTyped(json, false);
}

export function BelastungsplanQuDataDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BelastungsplanQuDataDTO {
  if (json == null) {
    return json;
  }
  return {
    label: json["label"],
    filled: json["filled"],
    valuesKnotenarme: (json["valuesKnotenarme"] as Array<any>).map(
      KnotenarmValueFromJSON
    ),
  };
}

export function BelastungsplanQuDataDTOToJSON(
  json: any
): BelastungsplanQuDataDTO {
  return BelastungsplanQuDataDTOToJSONTyped(json, false);
}

export function BelastungsplanQuDataDTOToJSONTyped(
  value?: BelastungsplanQuDataDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    label: value["label"],
    filled: value["filled"],
    valuesKnotenarme: (value["valuesKnotenarme"] as Array<any>).map(
      KnotenarmValueToJSON
    ),
  };
}
