/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ChatMessageRequestBody
 */
export interface ChatMessageRequestBody {
  /**
   *
   * @type {string}
   * @memberof ChatMessageRequestBody
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof ChatMessageRequestBody
   */
  createdTime?: Date;
  /**
   *
   * @type {number}
   * @memberof ChatMessageRequestBody
   */
  version?: number;
  /**
   *
   * @type {string}
   * @memberof ChatMessageRequestBody
   */
  zaehlungId?: string;
  /**
   *
   * @type {string}
   * @memberof ChatMessageRequestBody
   */
  content?: string;
  /**
   *
   * @type {number}
   * @memberof ChatMessageRequestBody
   */
  participantId?: number;
  /**
   *
   * @type {Date}
   * @memberof ChatMessageRequestBody
   */
  timestamp?: Date;
  /**
   *
   * @type {string}
   * @memberof ChatMessageRequestBody
   */
  type?: string;
  /**
   *
   * @type {boolean}
   * @memberof ChatMessageRequestBody
   */
  uploaded?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ChatMessageRequestBody
   */
  viewed?: boolean;
  /**
   *
   * @type {number}
   * @memberof ChatMessageRequestBody
   */
  entityVersion?: number;
}

/**
 * Check if a given object implements the ChatMessageRequestBody interface.
 */
export function instanceOfChatMessageRequestBody(
  value: object
): value is ChatMessageRequestBody {
  return true;
}

export function ChatMessageRequestBodyFromJSON(
  json: any
): ChatMessageRequestBody {
  return ChatMessageRequestBodyFromJSONTyped(json, false);
}

export function ChatMessageRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ChatMessageRequestBody {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdTime:
      json["createdTime"] == null ? undefined : new Date(json["createdTime"]),
    version: json["version"] == null ? undefined : json["version"],
    zaehlungId: json["zaehlungId"] == null ? undefined : json["zaehlungId"],
    content: json["content"] == null ? undefined : json["content"],
    participantId:
      json["participantId"] == null ? undefined : json["participantId"],
    timestamp:
      json["timestamp"] == null ? undefined : new Date(json["timestamp"]),
    type: json["type"] == null ? undefined : json["type"],
    uploaded: json["uploaded"] == null ? undefined : json["uploaded"],
    viewed: json["viewed"] == null ? undefined : json["viewed"],
    entityVersion:
      json["entityVersion"] == null ? undefined : json["entityVersion"],
  };
}

export function ChatMessageRequestBodyToJSON(
  json: any
): ChatMessageRequestBody {
  return ChatMessageRequestBodyToJSONTyped(json, false);
}

export function ChatMessageRequestBodyToJSONTyped(
  value?: ChatMessageRequestBody | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    createdTime:
      value["createdTime"] == null
        ? undefined
        : value["createdTime"].toISOString(),
    version: value["version"],
    zaehlungId: value["zaehlungId"],
    content: value["content"],
    participantId: value["participantId"],
    timestamp:
      value["timestamp"] == null ? undefined : value["timestamp"].toISOString(),
    type: value["type"],
    uploaded: value["uploaded"],
    viewed: value["viewed"],
    entityVersion: value["entityVersion"],
  };
}
