/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageDTO
 */
export interface ChatMessageDTO {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    zaehlungId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatMessageDTO
     */
    participantId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageDTO
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDTO
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChatMessageDTO
     */
    uploaded?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChatMessageDTO
     */
    viewed?: boolean;
}

/**
 * Check if a given object implements the ChatMessageDTO interface.
 */
export function instanceOfChatMessageDTO(value: object): value is ChatMessageDTO {
    return true;
}

export function ChatMessageDTOFromJSON(json: any): ChatMessageDTO {
    return ChatMessageDTOFromJSONTyped(json, false);
}

export function ChatMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'zaehlungId': json['zaehlungId'] == null ? undefined : json['zaehlungId'],
        'content': json['content'] == null ? undefined : json['content'],
        'participantId': json['participantId'] == null ? undefined : json['participantId'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'type': json['type'] == null ? undefined : json['type'],
        'uploaded': json['uploaded'] == null ? undefined : json['uploaded'],
        'viewed': json['viewed'] == null ? undefined : json['viewed'],
    };
}

export function ChatMessageDTOToJSON(json: any): ChatMessageDTO {
    return ChatMessageDTOToJSONTyped(json, false);
}

export function ChatMessageDTOToJSONTyped(value?: ChatMessageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'zaehlungId': value['zaehlungId'],
        'content': value['content'],
        'participantId': value['participantId'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'type': value['type'],
        'uploaded': value['uploaded'],
        'viewed': value['viewed'],
    };
}

