/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedModelEntityModelUnauffaelligerTagEmbedded } from './PagedModelEntityModelUnauffaelligerTagEmbedded';
import {
    PagedModelEntityModelUnauffaelligerTagEmbeddedFromJSON,
    PagedModelEntityModelUnauffaelligerTagEmbeddedFromJSONTyped,
    PagedModelEntityModelUnauffaelligerTagEmbeddedToJSON,
    PagedModelEntityModelUnauffaelligerTagEmbeddedToJSONTyped,
} from './PagedModelEntityModelUnauffaelligerTagEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelEntityModelUnauffaelligerTag
 */
export interface CollectionModelEntityModelUnauffaelligerTag {
    /**
     * 
     * @type {PagedModelEntityModelUnauffaelligerTagEmbedded}
     * @memberof CollectionModelEntityModelUnauffaelligerTag
     */
    embedded?: PagedModelEntityModelUnauffaelligerTagEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelEntityModelUnauffaelligerTag
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelEntityModelUnauffaelligerTag interface.
 */
export function instanceOfCollectionModelEntityModelUnauffaelligerTag(value: object): value is CollectionModelEntityModelUnauffaelligerTag {
    return true;
}

export function CollectionModelEntityModelUnauffaelligerTagFromJSON(json: any): CollectionModelEntityModelUnauffaelligerTag {
    return CollectionModelEntityModelUnauffaelligerTagFromJSONTyped(json, false);
}

export function CollectionModelEntityModelUnauffaelligerTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEntityModelUnauffaelligerTag {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelUnauffaelligerTagEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelEntityModelUnauffaelligerTagToJSON(json: any): CollectionModelEntityModelUnauffaelligerTag {
    return CollectionModelEntityModelUnauffaelligerTagToJSONTyped(json, false);
}

export function CollectionModelEntityModelUnauffaelligerTagToJSONTyped(value?: CollectionModelEntityModelUnauffaelligerTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelUnauffaelligerTagEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

