/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedModelEntityModelMessstelleEmbedded } from './PagedModelEntityModelMessstelleEmbedded';
import {
    PagedModelEntityModelMessstelleEmbeddedFromJSON,
    PagedModelEntityModelMessstelleEmbeddedFromJSONTyped,
    PagedModelEntityModelMessstelleEmbeddedToJSON,
    PagedModelEntityModelMessstelleEmbeddedToJSONTyped,
} from './PagedModelEntityModelMessstelleEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelEntityModelMessstelle
 */
export interface CollectionModelEntityModelMessstelle {
    /**
     * 
     * @type {PagedModelEntityModelMessstelleEmbedded}
     * @memberof CollectionModelEntityModelMessstelle
     */
    embedded?: PagedModelEntityModelMessstelleEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelEntityModelMessstelle
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelEntityModelMessstelle interface.
 */
export function instanceOfCollectionModelEntityModelMessstelle(value: object): value is CollectionModelEntityModelMessstelle {
    return true;
}

export function CollectionModelEntityModelMessstelleFromJSON(json: any): CollectionModelEntityModelMessstelle {
    return CollectionModelEntityModelMessstelleFromJSONTyped(json, false);
}

export function CollectionModelEntityModelMessstelleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEntityModelMessstelle {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelMessstelleEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelEntityModelMessstelleToJSON(json: any): CollectionModelEntityModelMessstelle {
    return CollectionModelEntityModelMessstelleToJSONTyped(json, false);
}

export function CollectionModelEntityModelMessstelleToJSONTyped(value?: CollectionModelEntityModelMessstelle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelMessstelleEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

