/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedModelEntityModelDienstleisterEmbedded } from './PagedModelEntityModelDienstleisterEmbedded';
import {
    PagedModelEntityModelDienstleisterEmbeddedFromJSON,
    PagedModelEntityModelDienstleisterEmbeddedFromJSONTyped,
    PagedModelEntityModelDienstleisterEmbeddedToJSON,
    PagedModelEntityModelDienstleisterEmbeddedToJSONTyped,
} from './PagedModelEntityModelDienstleisterEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CollectionModelEntityModelDienstleister
 */
export interface CollectionModelEntityModelDienstleister {
    /**
     * 
     * @type {PagedModelEntityModelDienstleisterEmbedded}
     * @memberof CollectionModelEntityModelDienstleister
     */
    embedded?: PagedModelEntityModelDienstleisterEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof CollectionModelEntityModelDienstleister
     */
    links?: { [key: string]: Link; };
}

/**
 * Check if a given object implements the CollectionModelEntityModelDienstleister interface.
 */
export function instanceOfCollectionModelEntityModelDienstleister(value: object): value is CollectionModelEntityModelDienstleister {
    return true;
}

export function CollectionModelEntityModelDienstleisterFromJSON(json: any): CollectionModelEntityModelDienstleister {
    return CollectionModelEntityModelDienstleisterFromJSONTyped(json, false);
}

export function CollectionModelEntityModelDienstleisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionModelEntityModelDienstleister {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelDienstleisterEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function CollectionModelEntityModelDienstleisterToJSON(json: any): CollectionModelEntityModelDienstleister {
    return CollectionModelEntityModelDienstleisterToJSONTyped(json, false);
}

export function CollectionModelEntityModelDienstleisterToJSONTyped(value?: CollectionModelEntityModelDienstleister | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelDienstleisterEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

