/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TenantConfigurationDTO } from "./TenantConfigurationDTO";
import type { ZaehlstelleConfigurationDTO } from "./ZaehlstelleConfigurationDTO";

import { mapValues } from "../runtime";
import {
  TenantConfigurationDTOFromJSON,
  TenantConfigurationDTOFromJSONTyped,
  TenantConfigurationDTOToJSON,
  TenantConfigurationDTOToJSONTyped,
} from "./TenantConfigurationDTO";
import {
  ZaehlstelleConfigurationDTOFromJSON,
  ZaehlstelleConfigurationDTOFromJSONTyped,
  ZaehlstelleConfigurationDTOToJSON,
  ZaehlstelleConfigurationDTOToJSONTyped,
} from "./ZaehlstelleConfigurationDTO";

/**
 *
 * @export
 * @interface ConfigurationDTO
 */
export interface ConfigurationDTO {
  /**
   *
   * @type {ZaehlstelleConfigurationDTO}
   * @memberof ConfigurationDTO
   */
  zaehlstelle?: ZaehlstelleConfigurationDTO;
  /**
   *
   * @type {TenantConfigurationDTO}
   * @memberof ConfigurationDTO
   */
  tenant?: TenantConfigurationDTO;
}

/**
 * Check if a given object implements the ConfigurationDTO interface.
 */
export function instanceOfConfigurationDTO(
  value: object
): value is ConfigurationDTO {
  return true;
}

export function ConfigurationDTOFromJSON(json: any): ConfigurationDTO {
  return ConfigurationDTOFromJSONTyped(json, false);
}

export function ConfigurationDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ConfigurationDTO {
  if (json == null) {
    return json;
  }
  return {
    zaehlstelle:
      json["zaehlstelle"] == null
        ? undefined
        : ZaehlstelleConfigurationDTOFromJSON(json["zaehlstelle"]),
    tenant:
      json["tenant"] == null
        ? undefined
        : TenantConfigurationDTOFromJSON(json["tenant"]),
  };
}

export function ConfigurationDTOToJSON(json: any): ConfigurationDTO {
  return ConfigurationDTOToJSONTyped(json, false);
}

export function ConfigurationDTOToJSONTyped(
  value?: ConfigurationDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    zaehlstelle: ZaehlstelleConfigurationDTOToJSON(value["zaehlstelle"]),
    tenant: TenantConfigurationDTOToJSON(value["tenant"]),
  };
}
