/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CsvDTO
 */
export interface CsvDTO {
  /**
   *
   * @type {string}
   * @memberof CsvDTO
   */
  csvAsString?: string;
}

/**
 * Check if a given object implements the CsvDTO interface.
 */
export function instanceOfCsvDTO(value: object): value is CsvDTO {
  return true;
}

export function CsvDTOFromJSON(json: any): CsvDTO {
  return CsvDTOFromJSONTyped(json, false);
}

export function CsvDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CsvDTO {
  if (json == null) {
    return json;
  }
  return {
    csvAsString: json["csvAsString"] == null ? undefined : json["csvAsString"],
  };
}

export function CsvDTOToJSON(json: any): CsvDTO {
  return CsvDTOToJSONTyped(json, false);
}

export function CsvDTOToJSONTyped(
  value?: CsvDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    csvAsString: value["csvAsString"],
  };
}
