/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BaseAsset } from "./BaseAsset";
import type { DatentabellePdfZaehldaten } from "./DatentabellePdfZaehldaten";
import type { OptionsDTO } from "./OptionsDTO";

import { mapValues } from "../runtime";
import {
  BaseAssetFromJSON,
  BaseAssetFromJSONTyped,
  BaseAssetToJSON,
  BaseAssetToJSONTyped,
} from "./BaseAsset";
import {
  DatentabellePdfZaehldatenFromJSON,
  DatentabellePdfZaehldatenFromJSONTyped,
  DatentabellePdfZaehldatenToJSON,
  DatentabellePdfZaehldatenToJSONTyped,
} from "./DatentabellePdfZaehldaten";
import {
  OptionsDTOFromJSON,
  OptionsDTOFromJSONTyped,
  OptionsDTOToJSON,
  OptionsDTOToJSONTyped,
} from "./OptionsDTO";

/**
 *
 * @export
 * @interface DatatableAsset
 */
export interface DatatableAsset extends BaseAsset {
  /**
   *
   * @type {DatentabellePdfZaehldaten}
   * @memberof DatatableAsset
   */
  datentabelleZaehldaten?: DatentabellePdfZaehldaten;
  /**
   *
   * @type {string}
   * @memberof DatatableAsset
   */
  randomTableId?: string;
  /**
   *
   * @type {string}
   * @memberof DatatableAsset
   */
  text?: string;
  /**
   *
   * @type {OptionsDTO}
   * @memberof DatatableAsset
   */
  options?: OptionsDTO;
  /**
   *
   * @type {string}
   * @memberof DatatableAsset
   */
  zaehlungId?: string;
}

/**
 * Check if a given object implements the DatatableAsset interface.
 */
export function instanceOfDatatableAsset(
  value: object
): value is DatatableAsset {
  return true;
}

export function DatatableAssetFromJSON(json: any): DatatableAsset {
  return DatatableAssetFromJSONTyped(json, false);
}

export function DatatableAssetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatatableAsset {
  if (json == null) {
    return json;
  }
  return {
    ...BaseAssetFromJSONTyped(json, true),
    datentabelleZaehldaten:
      json["datentabelleZaehldaten"] == null
        ? undefined
        : DatentabellePdfZaehldatenFromJSON(json["datentabelleZaehldaten"]),
    randomTableId:
      json["randomTableId"] == null ? undefined : json["randomTableId"],
    text: json["text"] == null ? undefined : json["text"],
    options:
      json["options"] == null ? undefined : OptionsDTOFromJSON(json["options"]),
    zaehlungId: json["zaehlungId"] == null ? undefined : json["zaehlungId"],
  };
}

export function DatatableAssetToJSON(json: any): DatatableAsset {
  return DatatableAssetToJSONTyped(json, false);
}

export function DatatableAssetToJSONTyped(
  value?: DatatableAsset | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ...BaseAssetToJSONTyped(value, true),
    datentabelleZaehldaten: DatentabellePdfZaehldatenToJSON(
      value["datentabelleZaehldaten"]
    ),
    randomTableId: value["randomTableId"],
    text: value["text"],
    options: OptionsDTOToJSON(value["options"]),
    zaehlungId: value["zaehlungId"],
  };
}
