/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface DatentabellePdfZaehldatum
 */
export interface DatentabellePdfZaehldatum {
  /**
   *
   * @type {string}
   * @memberof DatentabellePdfZaehldatum
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof DatentabellePdfZaehldatum
   */
  startUhrzeit?: string;
  /**
   *
   * @type {string}
   * @memberof DatentabellePdfZaehldatum
   */
  endeUhrzeit?: string;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  pkw?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  lkw?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  lastzuege?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  lfw?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  busse?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  kraftraeder?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  fahrradfahrer?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  fussgaenger?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  pkwEinheiten?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  gesamt?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  kfz?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  schwerverkehr?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  gueterverkehr?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  anteilSchwerverkehrAnKfzProzent?: number;
  /**
   *
   * @type {number}
   * @memberof DatentabellePdfZaehldatum
   */
  anteilGueterverkehrAnKfzProzent?: number;
}

/**
 * Check if a given object implements the DatentabellePdfZaehldatum interface.
 */
export function instanceOfDatentabellePdfZaehldatum(
  value: object
): value is DatentabellePdfZaehldatum {
  return true;
}

export function DatentabellePdfZaehldatumFromJSON(
  json: any
): DatentabellePdfZaehldatum {
  return DatentabellePdfZaehldatumFromJSONTyped(json, false);
}

export function DatentabellePdfZaehldatumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DatentabellePdfZaehldatum {
  if (json == null) {
    return json;
  }
  return {
    type: json["type"] == null ? undefined : json["type"],
    startUhrzeit:
      json["startUhrzeit"] == null ? undefined : json["startUhrzeit"],
    endeUhrzeit: json["endeUhrzeit"] == null ? undefined : json["endeUhrzeit"],
    pkw: json["pkw"] == null ? undefined : json["pkw"],
    lkw: json["lkw"] == null ? undefined : json["lkw"],
    lastzuege: json["lastzuege"] == null ? undefined : json["lastzuege"],
    lfw: json["lfw"] == null ? undefined : json["lfw"],
    busse: json["busse"] == null ? undefined : json["busse"],
    kraftraeder: json["kraftraeder"] == null ? undefined : json["kraftraeder"],
    fahrradfahrer:
      json["fahrradfahrer"] == null ? undefined : json["fahrradfahrer"],
    fussgaenger: json["fussgaenger"] == null ? undefined : json["fussgaenger"],
    pkwEinheiten:
      json["pkwEinheiten"] == null ? undefined : json["pkwEinheiten"],
    gesamt: json["gesamt"] == null ? undefined : json["gesamt"],
    kfz: json["kfz"] == null ? undefined : json["kfz"],
    schwerverkehr:
      json["schwerverkehr"] == null ? undefined : json["schwerverkehr"],
    gueterverkehr:
      json["gueterverkehr"] == null ? undefined : json["gueterverkehr"],
    anteilSchwerverkehrAnKfzProzent:
      json["anteilSchwerverkehrAnKfzProzent"] == null
        ? undefined
        : json["anteilSchwerverkehrAnKfzProzent"],
    anteilGueterverkehrAnKfzProzent:
      json["anteilGueterverkehrAnKfzProzent"] == null
        ? undefined
        : json["anteilGueterverkehrAnKfzProzent"],
  };
}

export function DatentabellePdfZaehldatumToJSON(
  json: any
): DatentabellePdfZaehldatum {
  return DatentabellePdfZaehldatumToJSONTyped(json, false);
}

export function DatentabellePdfZaehldatumToJSONTyped(
  value?: DatentabellePdfZaehldatum | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value["type"],
    startUhrzeit: value["startUhrzeit"],
    endeUhrzeit: value["endeUhrzeit"],
    pkw: value["pkw"],
    lkw: value["lkw"],
    lastzuege: value["lastzuege"],
    lfw: value["lfw"],
    busse: value["busse"],
    kraftraeder: value["kraftraeder"],
    fahrradfahrer: value["fahrradfahrer"],
    fussgaenger: value["fussgaenger"],
    pkwEinheiten: value["pkwEinheiten"],
    gesamt: value["gesamt"],
    kfz: value["kfz"],
    schwerverkehr: value["schwerverkehr"],
    gueterverkehr: value["gueterverkehr"],
    anteilSchwerverkehrAnKfzProzent: value["anteilSchwerverkehrAnKfzProzent"],
    anteilGueterverkehrAnKfzProzent: value["anteilGueterverkehrAnKfzProzent"],
  };
}
