/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Fahrzeugklasse } from "./Fahrzeugklasse";
import type { ZaehldatenIntervall } from "./ZaehldatenIntervall";

import { mapValues } from "../runtime";
import {
  FahrzeugklasseFromJSON,
  FahrzeugklasseFromJSONTyped,
  FahrzeugklasseToJSON,
  FahrzeugklasseToJSONTyped,
} from "./Fahrzeugklasse";
import {
  ZaehldatenIntervallFromJSON,
  ZaehldatenIntervallFromJSONTyped,
  ZaehldatenIntervallToJSON,
  ZaehldatenIntervallToJSONTyped,
} from "./ZaehldatenIntervall";

/**
 *
 * @export
 * @interface EditMessfaehigkeitDTO
 */
export interface EditMessfaehigkeitDTO {
  /**
   *
   * @type {string}
   * @memberof EditMessfaehigkeitDTO
   */
  gueltigBis?: string;
  /**
   *
   * @type {string}
   * @memberof EditMessfaehigkeitDTO
   */
  gueltigAb?: string;
  /**
   *
   * @type {Fahrzeugklasse}
   * @memberof EditMessfaehigkeitDTO
   */
  fahrzeugklasse?: Fahrzeugklasse;
  /**
   *
   * @type {ZaehldatenIntervall}
   * @memberof EditMessfaehigkeitDTO
   */
  intervall?: ZaehldatenIntervall;
}

/**
 * Check if a given object implements the EditMessfaehigkeitDTO interface.
 */
export function instanceOfEditMessfaehigkeitDTO(
  value: object
): value is EditMessfaehigkeitDTO {
  return true;
}

export function EditMessfaehigkeitDTOFromJSON(
  json: any
): EditMessfaehigkeitDTO {
  return EditMessfaehigkeitDTOFromJSONTyped(json, false);
}

export function EditMessfaehigkeitDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EditMessfaehigkeitDTO {
  if (json == null) {
    return json;
  }
  return {
    gueltigBis: json["gueltigBis"] == null ? undefined : json["gueltigBis"],
    gueltigAb: json["gueltigAb"] == null ? undefined : json["gueltigAb"],
    fahrzeugklasse:
      json["fahrzeugklasse"] == null
        ? undefined
        : FahrzeugklasseFromJSON(json["fahrzeugklasse"]),
    intervall:
      json["intervall"] == null
        ? undefined
        : ZaehldatenIntervallFromJSON(json["intervall"]),
  };
}

export function EditMessfaehigkeitDTOToJSON(json: any): EditMessfaehigkeitDTO {
  return EditMessfaehigkeitDTOToJSONTyped(json, false);
}

export function EditMessfaehigkeitDTOToJSONTyped(
  value?: EditMessfaehigkeitDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    gueltigBis: value["gueltigBis"],
    gueltigAb: value["gueltigAb"],
    fahrzeugklasse: FahrzeugklasseToJSON(value["fahrzeugklasse"]),
    intervall: ZaehldatenIntervallToJSON(value["intervall"]),
  };
}
