/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Link } from "./Link";

import { mapValues } from "../runtime";
import {
  LinkFromJSON,
  LinkFromJSONTyped,
  LinkToJSON,
  LinkToJSONTyped,
} from "./Link";

/**
 *
 * @export
 * @interface EntityModelHochrechnungsfaktor
 */
export interface EntityModelHochrechnungsfaktor {
  /**
   *
   * @type {string}
   * @memberof EntityModelHochrechnungsfaktor
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof EntityModelHochrechnungsfaktor
   */
  createdTime?: Date;
  /**
   *
   * @type {number}
   * @memberof EntityModelHochrechnungsfaktor
   */
  version?: number;
  /**
   *
   * @type {string}
   * @memberof EntityModelHochrechnungsfaktor
   */
  matrix?: string;
  /**
   *
   * @type {number}
   * @memberof EntityModelHochrechnungsfaktor
   */
  kfz?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelHochrechnungsfaktor
   */
  sv?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelHochrechnungsfaktor
   */
  gv?: number;
  /**
   *
   * @type {boolean}
   * @memberof EntityModelHochrechnungsfaktor
   */
  active?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EntityModelHochrechnungsfaktor
   */
  defaultFaktor?: boolean;
  /**
   *
   * @type {number}
   * @memberof EntityModelHochrechnungsfaktor
   */
  entityVersion?: number;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof EntityModelHochrechnungsfaktor
   */
  links?: { [key: string]: Link };
}

/**
 * Check if a given object implements the EntityModelHochrechnungsfaktor interface.
 */
export function instanceOfEntityModelHochrechnungsfaktor(
  value: object
): value is EntityModelHochrechnungsfaktor {
  return true;
}

export function EntityModelHochrechnungsfaktorFromJSON(
  json: any
): EntityModelHochrechnungsfaktor {
  return EntityModelHochrechnungsfaktorFromJSONTyped(json, false);
}

export function EntityModelHochrechnungsfaktorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityModelHochrechnungsfaktor {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdTime:
      json["createdTime"] == null ? undefined : new Date(json["createdTime"]),
    version: json["version"] == null ? undefined : json["version"],
    matrix: json["matrix"] == null ? undefined : json["matrix"],
    kfz: json["kfz"] == null ? undefined : json["kfz"],
    sv: json["sv"] == null ? undefined : json["sv"],
    gv: json["gv"] == null ? undefined : json["gv"],
    active: json["active"] == null ? undefined : json["active"],
    defaultFaktor:
      json["defaultFaktor"] == null ? undefined : json["defaultFaktor"],
    entityVersion:
      json["entityVersion"] == null ? undefined : json["entityVersion"],
    links:
      json["_links"] == null
        ? undefined
        : mapValues(json["_links"], LinkFromJSON),
  };
}

export function EntityModelHochrechnungsfaktorToJSON(
  json: any
): EntityModelHochrechnungsfaktor {
  return EntityModelHochrechnungsfaktorToJSONTyped(json, false);
}

export function EntityModelHochrechnungsfaktorToJSONTyped(
  value?: EntityModelHochrechnungsfaktor | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    createdTime:
      value["createdTime"] == null
        ? undefined
        : value["createdTime"].toISOString(),
    version: value["version"],
    matrix: value["matrix"],
    kfz: value["kfz"],
    sv: value["sv"],
    gv: value["gv"],
    active: value["active"],
    defaultFaktor: value["defaultFaktor"],
    entityVersion: value["entityVersion"],
    _links:
      value["links"] == null
        ? undefined
        : mapValues(value["links"], LinkToJSON),
  };
}
