/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Link } from "./Link";

import { mapValues } from "../runtime";
import {
  LinkFromJSON,
  LinkFromJSONTyped,
  LinkToJSON,
  LinkToJSONTyped,
} from "./Link";

/**
 *
 * @export
 * @interface EntityModelChatMessage
 */
export interface EntityModelChatMessage {
  /**
   *
   * @type {string}
   * @memberof EntityModelChatMessage
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof EntityModelChatMessage
   */
  createdTime?: Date;
  /**
   *
   * @type {number}
   * @memberof EntityModelChatMessage
   */
  version?: number;
  /**
   *
   * @type {string}
   * @memberof EntityModelChatMessage
   */
  zaehlungId?: string;
  /**
   *
   * @type {string}
   * @memberof EntityModelChatMessage
   */
  content?: string;
  /**
   *
   * @type {number}
   * @memberof EntityModelChatMessage
   */
  participantId?: number;
  /**
   *
   * @type {Date}
   * @memberof EntityModelChatMessage
   */
  timestamp?: Date;
  /**
   *
   * @type {string}
   * @memberof EntityModelChatMessage
   */
  type?: string;
  /**
   *
   * @type {boolean}
   * @memberof EntityModelChatMessage
   */
  uploaded?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EntityModelChatMessage
   */
  viewed?: boolean;
  /**
   *
   * @type {number}
   * @memberof EntityModelChatMessage
   */
  entityVersion?: number;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof EntityModelChatMessage
   */
  links?: { [key: string]: Link };
}

/**
 * Check if a given object implements the EntityModelChatMessage interface.
 */
export function instanceOfEntityModelChatMessage(
  value: object
): value is EntityModelChatMessage {
  return true;
}

export function EntityModelChatMessageFromJSON(
  json: any
): EntityModelChatMessage {
  return EntityModelChatMessageFromJSONTyped(json, false);
}

export function EntityModelChatMessageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityModelChatMessage {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdTime:
      json["createdTime"] == null ? undefined : new Date(json["createdTime"]),
    version: json["version"] == null ? undefined : json["version"],
    zaehlungId: json["zaehlungId"] == null ? undefined : json["zaehlungId"],
    content: json["content"] == null ? undefined : json["content"],
    participantId:
      json["participantId"] == null ? undefined : json["participantId"],
    timestamp:
      json["timestamp"] == null ? undefined : new Date(json["timestamp"]),
    type: json["type"] == null ? undefined : json["type"],
    uploaded: json["uploaded"] == null ? undefined : json["uploaded"],
    viewed: json["viewed"] == null ? undefined : json["viewed"],
    entityVersion:
      json["entityVersion"] == null ? undefined : json["entityVersion"],
    links:
      json["_links"] == null
        ? undefined
        : mapValues(json["_links"], LinkFromJSON),
  };
}

export function EntityModelChatMessageToJSON(
  json: any
): EntityModelChatMessage {
  return EntityModelChatMessageToJSONTyped(json, false);
}

export function EntityModelChatMessageToJSONTyped(
  value?: EntityModelChatMessage | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    createdTime:
      value["createdTime"] == null
        ? undefined
        : value["createdTime"].toISOString(),
    version: value["version"],
    zaehlungId: value["zaehlungId"],
    content: value["content"],
    participantId: value["participantId"],
    timestamp:
      value["timestamp"] == null ? undefined : value["timestamp"].toISOString(),
    type: value["type"],
    uploaded: value["uploaded"],
    viewed: value["viewed"],
    entityVersion: value["entityVersion"],
    _links:
      value["links"] == null
        ? undefined
        : mapValues(value["links"], LinkToJSON),
  };
}
