/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Hochrechnung } from "./Hochrechnung";
import type { Laengsverkehr } from "./Laengsverkehr";
import type { Link } from "./Link";
import type { Querungsverkehr } from "./Querungsverkehr";
import type { Verkehrsbeziehung } from "./Verkehrsbeziehung";

import { mapValues } from "../runtime";
import {
  HochrechnungFromJSON,
  HochrechnungFromJSONTyped,
  HochrechnungToJSON,
  HochrechnungToJSONTyped,
} from "./Hochrechnung";
import {
  LaengsverkehrFromJSON,
  LaengsverkehrFromJSONTyped,
  LaengsverkehrToJSON,
  LaengsverkehrToJSONTyped,
} from "./Laengsverkehr";
import {
  LinkFromJSON,
  LinkFromJSONTyped,
  LinkToJSON,
  LinkToJSONTyped,
} from "./Link";
import {
  QuerungsverkehrFromJSON,
  QuerungsverkehrFromJSONTyped,
  QuerungsverkehrToJSON,
  QuerungsverkehrToJSONTyped,
} from "./Querungsverkehr";
import {
  VerkehrsbeziehungFromJSON,
  VerkehrsbeziehungFromJSONTyped,
  VerkehrsbeziehungToJSON,
  VerkehrsbeziehungToJSONTyped,
} from "./Verkehrsbeziehung";

/**
 *
 * @export
 * @interface EntityModelZeitintervall
 */
export interface EntityModelZeitintervall {
  /**
   *
   * @type {string}
   * @memberof EntityModelZeitintervall
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof EntityModelZeitintervall
   */
  createdTime?: Date;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  version?: number;
  /**
   *
   * @type {string}
   * @memberof EntityModelZeitintervall
   */
  zaehlungId?: string;
  /**
   *
   * @type {string}
   * @memberof EntityModelZeitintervall
   */
  bewegungsbeziehungId?: string;
  /**
   *
   * @type {Date}
   * @memberof EntityModelZeitintervall
   */
  startUhrzeit: Date;
  /**
   *
   * @type {Date}
   * @memberof EntityModelZeitintervall
   */
  endeUhrzeit: Date;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  sortingIndex?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  pkw?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  lkw?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  lastzuege?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  busse?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  kraftraeder?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  fahrradfahrer?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  fussgaenger?: number;
  /**
   *
   * @type {string}
   * @memberof EntityModelZeitintervall
   */
  type: EntityModelZeitintervallTypeEnum;
  /**
   *
   * @type {Hochrechnung}
   * @memberof EntityModelZeitintervall
   */
  hochrechnung?: Hochrechnung;
  /**
   *
   * @type {Querungsverkehr}
   * @memberof EntityModelZeitintervall
   */
  querungsverkehr?: Querungsverkehr;
  /**
   *
   * @type {Laengsverkehr}
   * @memberof EntityModelZeitintervall
   */
  laengsverkehr?: Laengsverkehr;
  /**
   *
   * @type {Verkehrsbeziehung}
   * @memberof EntityModelZeitintervall
   */
  verkehrsbeziehung?: Verkehrsbeziehung;
  /**
   *
   * @type {number}
   * @memberof EntityModelZeitintervall
   */
  entityVersion?: number;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof EntityModelZeitintervall
   */
  links?: { [key: string]: Link };
}

/**
 * @export
 */
export const EntityModelZeitintervallTypeEnum = {
  Block: "BLOCK",
  BlockSpezial: "BLOCK_SPEZIAL",
  Gesamt: "GESAMT",
  GesamtKi: "GESAMT_KI",
  SpitzenstundeKfz: "SPITZENSTUNDE_KFZ",
  SpitzenstundeRad: "SPITZENSTUNDE_RAD",
  SpitzenstundeFuss: "SPITZENSTUNDE_FUSS",
  StundeViertel: "STUNDE_VIERTEL",
  StundeHalb: "STUNDE_HALB",
  StundeKomplett: "STUNDE_KOMPLETT",
} as const;
export type EntityModelZeitintervallTypeEnum =
  (typeof EntityModelZeitintervallTypeEnum)[keyof typeof EntityModelZeitintervallTypeEnum];

/**
 * Check if a given object implements the EntityModelZeitintervall interface.
 */
export function instanceOfEntityModelZeitintervall(
  value: object
): value is EntityModelZeitintervall {
  if (!("startUhrzeit" in value) || value["startUhrzeit"] === undefined)
    return false;
  if (!("endeUhrzeit" in value) || value["endeUhrzeit"] === undefined)
    return false;
  if (!("type" in value) || value["type"] === undefined) return false;
  return true;
}

export function EntityModelZeitintervallFromJSON(
  json: any
): EntityModelZeitintervall {
  return EntityModelZeitintervallFromJSONTyped(json, false);
}

export function EntityModelZeitintervallFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityModelZeitintervall {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdTime:
      json["createdTime"] == null ? undefined : new Date(json["createdTime"]),
    version: json["version"] == null ? undefined : json["version"],
    zaehlungId: json["zaehlungId"] == null ? undefined : json["zaehlungId"],
    bewegungsbeziehungId:
      json["bewegungsbeziehungId"] == null
        ? undefined
        : json["bewegungsbeziehungId"],
    startUhrzeit: new Date(json["startUhrzeit"]),
    endeUhrzeit: new Date(json["endeUhrzeit"]),
    sortingIndex:
      json["sortingIndex"] == null ? undefined : json["sortingIndex"],
    pkw: json["pkw"] == null ? undefined : json["pkw"],
    lkw: json["lkw"] == null ? undefined : json["lkw"],
    lastzuege: json["lastzuege"] == null ? undefined : json["lastzuege"],
    busse: json["busse"] == null ? undefined : json["busse"],
    kraftraeder: json["kraftraeder"] == null ? undefined : json["kraftraeder"],
    fahrradfahrer:
      json["fahrradfahrer"] == null ? undefined : json["fahrradfahrer"],
    fussgaenger: json["fussgaenger"] == null ? undefined : json["fussgaenger"],
    type: json["type"],
    hochrechnung:
      json["hochrechnung"] == null
        ? undefined
        : HochrechnungFromJSON(json["hochrechnung"]),
    querungsverkehr:
      json["querungsverkehr"] == null
        ? undefined
        : QuerungsverkehrFromJSON(json["querungsverkehr"]),
    laengsverkehr:
      json["laengsverkehr"] == null
        ? undefined
        : LaengsverkehrFromJSON(json["laengsverkehr"]),
    verkehrsbeziehung:
      json["verkehrsbeziehung"] == null
        ? undefined
        : VerkehrsbeziehungFromJSON(json["verkehrsbeziehung"]),
    entityVersion:
      json["entityVersion"] == null ? undefined : json["entityVersion"],
    links:
      json["_links"] == null
        ? undefined
        : mapValues(json["_links"], LinkFromJSON),
  };
}

export function EntityModelZeitintervallToJSON(
  json: any
): EntityModelZeitintervall {
  return EntityModelZeitintervallToJSONTyped(json, false);
}

export function EntityModelZeitintervallToJSONTyped(
  value?: EntityModelZeitintervall | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    createdTime:
      value["createdTime"] == null
        ? undefined
        : value["createdTime"].toISOString(),
    version: value["version"],
    zaehlungId: value["zaehlungId"],
    bewegungsbeziehungId: value["bewegungsbeziehungId"],
    startUhrzeit: value["startUhrzeit"].toISOString(),
    endeUhrzeit: value["endeUhrzeit"].toISOString(),
    sortingIndex: value["sortingIndex"],
    pkw: value["pkw"],
    lkw: value["lkw"],
    lastzuege: value["lastzuege"],
    busse: value["busse"],
    kraftraeder: value["kraftraeder"],
    fahrradfahrer: value["fahrradfahrer"],
    fussgaenger: value["fussgaenger"],
    type: value["type"],
    hochrechnung: HochrechnungToJSON(value["hochrechnung"]),
    querungsverkehr: QuerungsverkehrToJSON(value["querungsverkehr"]),
    laengsverkehr: LaengsverkehrToJSON(value["laengsverkehr"]),
    verkehrsbeziehung: VerkehrsbeziehungToJSON(value["verkehrsbeziehung"]),
    entityVersion: value["entityVersion"],
    _links:
      value["links"] == null
        ? undefined
        : mapValues(value["links"], LinkToJSON),
  };
}
