/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Link } from "./Link";

import { mapValues } from "../runtime";
import {
  LinkFromJSON,
  LinkFromJSONTyped,
  LinkToJSON,
  LinkToJSONTyped,
} from "./Link";

/**
 *
 * @export
 * @interface EntityModelPkwEinheit
 */
export interface EntityModelPkwEinheit {
  /**
   *
   * @type {string}
   * @memberof EntityModelPkwEinheit
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof EntityModelPkwEinheit
   */
  createdTime?: Date;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  version?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  pkw?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  lkw?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  lastzuege?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  busse?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  kraftraeder?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  fahrradfahrer?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  fussgaenger?: number;
  /**
   *
   * @type {number}
   * @memberof EntityModelPkwEinheit
   */
  entityVersion?: number;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof EntityModelPkwEinheit
   */
  links?: { [key: string]: Link };
}

/**
 * Check if a given object implements the EntityModelPkwEinheit interface.
 */
export function instanceOfEntityModelPkwEinheit(
  value: object
): value is EntityModelPkwEinheit {
  return true;
}

export function EntityModelPkwEinheitFromJSON(
  json: any
): EntityModelPkwEinheit {
  return EntityModelPkwEinheitFromJSONTyped(json, false);
}

export function EntityModelPkwEinheitFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityModelPkwEinheit {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdTime:
      json["createdTime"] == null ? undefined : new Date(json["createdTime"]),
    version: json["version"] == null ? undefined : json["version"],
    pkw: json["pkw"] == null ? undefined : json["pkw"],
    lkw: json["lkw"] == null ? undefined : json["lkw"],
    lastzuege: json["lastzuege"] == null ? undefined : json["lastzuege"],
    busse: json["busse"] == null ? undefined : json["busse"],
    kraftraeder: json["kraftraeder"] == null ? undefined : json["kraftraeder"],
    fahrradfahrer:
      json["fahrradfahrer"] == null ? undefined : json["fahrradfahrer"],
    fussgaenger: json["fussgaenger"] == null ? undefined : json["fussgaenger"],
    entityVersion:
      json["entityVersion"] == null ? undefined : json["entityVersion"],
    links:
      json["_links"] == null
        ? undefined
        : mapValues(json["_links"], LinkFromJSON),
  };
}

export function EntityModelPkwEinheitToJSON(json: any): EntityModelPkwEinheit {
  return EntityModelPkwEinheitToJSONTyped(json, false);
}

export function EntityModelPkwEinheitToJSONTyped(
  value?: EntityModelPkwEinheit | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    createdTime:
      value["createdTime"] == null
        ? undefined
        : value["createdTime"].toISOString(),
    version: value["version"],
    pkw: value["pkw"],
    lkw: value["lkw"],
    lastzuege: value["lastzuege"],
    busse: value["busse"],
    kraftraeder: value["kraftraeder"],
    fahrradfahrer: value["fahrradfahrer"],
    fussgaenger: value["fussgaenger"],
    entityVersion: value["entityVersion"],
    _links:
      value["links"] == null
        ? undefined
        : mapValues(value["links"], LinkToJSON),
  };
}
