/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Link } from "./Link";

import { mapValues } from "../runtime";
import {
  LinkFromJSON,
  LinkFromJSONTyped,
  LinkToJSON,
  LinkToJSONTyped,
} from "./Link";

/**
 *
 * @export
 * @interface EntityModelOptionsmenueSettings
 */
export interface EntityModelOptionsmenueSettings {
  /**
   *
   * @type {string}
   * @memberof EntityModelOptionsmenueSettings
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof EntityModelOptionsmenueSettings
   */
  createdTime?: Date;
  /**
   *
   * @type {number}
   * @memberof EntityModelOptionsmenueSettings
   */
  version?: number;
  /**
   *
   * @type {string}
   * @memberof EntityModelOptionsmenueSettings
   */
  fahrzeugklasse?: EntityModelOptionsmenueSettingsFahrzeugklasseEnum;
  /**
   *
   * @type {string}
   * @memberof EntityModelOptionsmenueSettings
   */
  intervall?: EntityModelOptionsmenueSettingsIntervallEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  kraftfahrzeugverkehrChoosableIntervals?: Array<EntityModelOptionsmenueSettingsKraftfahrzeugverkehrChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  schwerverkehrChoosableIntervals?: Array<EntityModelOptionsmenueSettingsSchwerverkehrChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  gueterverkehrChoosableIntervals?: Array<EntityModelOptionsmenueSettingsGueterverkehrChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  schwerverkehrsanteilProzentChoosableIntervals?: Array<EntityModelOptionsmenueSettingsSchwerverkehrsanteilProzentChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  gueterverkehrsanteilProzentChoosableIntervals?: Array<EntityModelOptionsmenueSettingsGueterverkehrsanteilProzentChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  radverkehrChoosableIntervals?: Array<EntityModelOptionsmenueSettingsRadverkehrChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  fussverkehrChoosableIntervals?: Array<EntityModelOptionsmenueSettingsFussverkehrChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  lastkraftwagenChoosableIntervals?: Array<EntityModelOptionsmenueSettingsLastkraftwagenChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  lastzuegeChoosableIntervals?: Array<EntityModelOptionsmenueSettingsLastzuegeChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  busseChoosableIntervals?: Array<EntityModelOptionsmenueSettingsBusseChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  kraftraederChoosableIntervals?: Array<EntityModelOptionsmenueSettingsKraftraederChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  personenkraftwagenChoosableIntervals?: Array<EntityModelOptionsmenueSettingsPersonenkraftwagenChoosableIntervalsEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof EntityModelOptionsmenueSettings
   */
  lieferwagenChoosableIntervals?: Array<EntityModelOptionsmenueSettingsLieferwagenChoosableIntervalsEnum>;
  /**
   *
   * @type {number}
   * @memberof EntityModelOptionsmenueSettings
   */
  entityVersion?: number;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof EntityModelOptionsmenueSettings
   */
  links?: { [key: string]: Link };
}

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsFahrzeugklasseEnum = {
  Rad: "RAD",
  SummeKfz: "SUMME_KFZ",
  ZweiPlusEins: "ZWEI_PLUS_EINS",
  AchtPlusEins: "ACHT_PLUS_EINS",
} as const;
export type EntityModelOptionsmenueSettingsFahrzeugklasseEnum =
  (typeof EntityModelOptionsmenueSettingsFahrzeugklasseEnum)[keyof typeof EntityModelOptionsmenueSettingsFahrzeugklasseEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsIntervallEnum = {
  StundeViertel: "STUNDE_VIERTEL",
  StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
  StundeHalb: "STUNDE_HALB",
  StundeKomplett: "STUNDE_KOMPLETT",
} as const;
export type EntityModelOptionsmenueSettingsIntervallEnum =
  (typeof EntityModelOptionsmenueSettingsIntervallEnum)[keyof typeof EntityModelOptionsmenueSettingsIntervallEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsKraftfahrzeugverkehrChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsKraftfahrzeugverkehrChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsKraftfahrzeugverkehrChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsKraftfahrzeugverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsSchwerverkehrChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsSchwerverkehrChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsSchwerverkehrChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsSchwerverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsGueterverkehrChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsGueterverkehrChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsGueterverkehrChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsGueterverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsSchwerverkehrsanteilProzentChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsSchwerverkehrsanteilProzentChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsSchwerverkehrsanteilProzentChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsSchwerverkehrsanteilProzentChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsGueterverkehrsanteilProzentChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsGueterverkehrsanteilProzentChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsGueterverkehrsanteilProzentChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsGueterverkehrsanteilProzentChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsRadverkehrChoosableIntervalsEnum = {
  StundeViertel: "STUNDE_VIERTEL",
  StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
  StundeHalb: "STUNDE_HALB",
  StundeKomplett: "STUNDE_KOMPLETT",
} as const;
export type EntityModelOptionsmenueSettingsRadverkehrChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsRadverkehrChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsRadverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsFussverkehrChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsFussverkehrChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsFussverkehrChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsFussverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsLastkraftwagenChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsLastkraftwagenChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsLastkraftwagenChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsLastkraftwagenChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsLastzuegeChoosableIntervalsEnum = {
  StundeViertel: "STUNDE_VIERTEL",
  StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
  StundeHalb: "STUNDE_HALB",
  StundeKomplett: "STUNDE_KOMPLETT",
} as const;
export type EntityModelOptionsmenueSettingsLastzuegeChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsLastzuegeChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsLastzuegeChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsBusseChoosableIntervalsEnum = {
  StundeViertel: "STUNDE_VIERTEL",
  StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
  StundeHalb: "STUNDE_HALB",
  StundeKomplett: "STUNDE_KOMPLETT",
} as const;
export type EntityModelOptionsmenueSettingsBusseChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsBusseChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsBusseChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsKraftraederChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsKraftraederChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsKraftraederChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsKraftraederChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsPersonenkraftwagenChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsPersonenkraftwagenChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsPersonenkraftwagenChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsPersonenkraftwagenChoosableIntervalsEnum];

/**
 * @export
 */
export const EntityModelOptionsmenueSettingsLieferwagenChoosableIntervalsEnum =
  {
    StundeViertel: "STUNDE_VIERTEL",
    StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
    StundeHalb: "STUNDE_HALB",
    StundeKomplett: "STUNDE_KOMPLETT",
  } as const;
export type EntityModelOptionsmenueSettingsLieferwagenChoosableIntervalsEnum =
  (typeof EntityModelOptionsmenueSettingsLieferwagenChoosableIntervalsEnum)[keyof typeof EntityModelOptionsmenueSettingsLieferwagenChoosableIntervalsEnum];

/**
 * Check if a given object implements the EntityModelOptionsmenueSettings interface.
 */
export function instanceOfEntityModelOptionsmenueSettings(
  value: object
): value is EntityModelOptionsmenueSettings {
  return true;
}

export function EntityModelOptionsmenueSettingsFromJSON(
  json: any
): EntityModelOptionsmenueSettings {
  return EntityModelOptionsmenueSettingsFromJSONTyped(json, false);
}

export function EntityModelOptionsmenueSettingsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityModelOptionsmenueSettings {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    createdTime:
      json["createdTime"] == null ? undefined : new Date(json["createdTime"]),
    version: json["version"] == null ? undefined : json["version"],
    fahrzeugklasse:
      json["fahrzeugklasse"] == null ? undefined : json["fahrzeugklasse"],
    intervall: json["intervall"] == null ? undefined : json["intervall"],
    kraftfahrzeugverkehrChoosableIntervals:
      json["kraftfahrzeugverkehrChoosableIntervals"] == null
        ? undefined
        : json["kraftfahrzeugverkehrChoosableIntervals"],
    schwerverkehrChoosableIntervals:
      json["schwerverkehrChoosableIntervals"] == null
        ? undefined
        : json["schwerverkehrChoosableIntervals"],
    gueterverkehrChoosableIntervals:
      json["gueterverkehrChoosableIntervals"] == null
        ? undefined
        : json["gueterverkehrChoosableIntervals"],
    schwerverkehrsanteilProzentChoosableIntervals:
      json["schwerverkehrsanteilProzentChoosableIntervals"] == null
        ? undefined
        : json["schwerverkehrsanteilProzentChoosableIntervals"],
    gueterverkehrsanteilProzentChoosableIntervals:
      json["gueterverkehrsanteilProzentChoosableIntervals"] == null
        ? undefined
        : json["gueterverkehrsanteilProzentChoosableIntervals"],
    radverkehrChoosableIntervals:
      json["radverkehrChoosableIntervals"] == null
        ? undefined
        : json["radverkehrChoosableIntervals"],
    fussverkehrChoosableIntervals:
      json["fussverkehrChoosableIntervals"] == null
        ? undefined
        : json["fussverkehrChoosableIntervals"],
    lastkraftwagenChoosableIntervals:
      json["lastkraftwagenChoosableIntervals"] == null
        ? undefined
        : json["lastkraftwagenChoosableIntervals"],
    lastzuegeChoosableIntervals:
      json["lastzuegeChoosableIntervals"] == null
        ? undefined
        : json["lastzuegeChoosableIntervals"],
    busseChoosableIntervals:
      json["busseChoosableIntervals"] == null
        ? undefined
        : json["busseChoosableIntervals"],
    kraftraederChoosableIntervals:
      json["kraftraederChoosableIntervals"] == null
        ? undefined
        : json["kraftraederChoosableIntervals"],
    personenkraftwagenChoosableIntervals:
      json["personenkraftwagenChoosableIntervals"] == null
        ? undefined
        : json["personenkraftwagenChoosableIntervals"],
    lieferwagenChoosableIntervals:
      json["lieferwagenChoosableIntervals"] == null
        ? undefined
        : json["lieferwagenChoosableIntervals"],
    entityVersion:
      json["entityVersion"] == null ? undefined : json["entityVersion"],
    links:
      json["_links"] == null
        ? undefined
        : mapValues(json["_links"], LinkFromJSON),
  };
}

export function EntityModelOptionsmenueSettingsToJSON(
  json: any
): EntityModelOptionsmenueSettings {
  return EntityModelOptionsmenueSettingsToJSONTyped(json, false);
}

export function EntityModelOptionsmenueSettingsToJSONTyped(
  value?: EntityModelOptionsmenueSettings | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    createdTime:
      value["createdTime"] == null
        ? undefined
        : value["createdTime"].toISOString(),
    version: value["version"],
    fahrzeugklasse: value["fahrzeugklasse"],
    intervall: value["intervall"],
    kraftfahrzeugverkehrChoosableIntervals:
      value["kraftfahrzeugverkehrChoosableIntervals"],
    schwerverkehrChoosableIntervals: value["schwerverkehrChoosableIntervals"],
    gueterverkehrChoosableIntervals: value["gueterverkehrChoosableIntervals"],
    schwerverkehrsanteilProzentChoosableIntervals:
      value["schwerverkehrsanteilProzentChoosableIntervals"],
    gueterverkehrsanteilProzentChoosableIntervals:
      value["gueterverkehrsanteilProzentChoosableIntervals"],
    radverkehrChoosableIntervals: value["radverkehrChoosableIntervals"],
    fussverkehrChoosableIntervals: value["fussverkehrChoosableIntervals"],
    lastkraftwagenChoosableIntervals: value["lastkraftwagenChoosableIntervals"],
    lastzuegeChoosableIntervals: value["lastzuegeChoosableIntervals"],
    busseChoosableIntervals: value["busseChoosableIntervals"],
    kraftraederChoosableIntervals: value["kraftraederChoosableIntervals"],
    personenkraftwagenChoosableIntervals:
      value["personenkraftwagenChoosableIntervals"],
    lieferwagenChoosableIntervals: value["lieferwagenChoosableIntervals"],
    entityVersion: value["entityVersion"],
    _links:
      value["links"] == null
        ? undefined
        : mapValues(value["links"], LinkToJSON),
  };
}
