/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Bewegungsrichtung } from "./Bewegungsrichtung";
import type { Himmelsrichtung } from "./Himmelsrichtung";
import type { HochrechnungsfaktorDTO } from "./HochrechnungsfaktorDTO";
import type { ZeitintervallDTO } from "./ZeitintervallDTO";

import { mapValues } from "../runtime";
import {
  BewegungsrichtungFromJSON,
  BewegungsrichtungFromJSONTyped,
  BewegungsrichtungToJSON,
  BewegungsrichtungToJSONTyped,
} from "./Bewegungsrichtung";
import {
  HimmelsrichtungFromJSON,
  HimmelsrichtungFromJSONTyped,
  HimmelsrichtungToJSON,
  HimmelsrichtungToJSONTyped,
} from "./Himmelsrichtung";
import {
  HochrechnungsfaktorDTOFromJSON,
  HochrechnungsfaktorDTOFromJSONTyped,
  HochrechnungsfaktorDTOToJSON,
  HochrechnungsfaktorDTOToJSONTyped,
} from "./HochrechnungsfaktorDTO";
import {
  ZeitintervallDTOFromJSON,
  ZeitintervallDTOFromJSONTyped,
  ZeitintervallDTOToJSON,
  ZeitintervallDTOToJSONTyped,
} from "./ZeitintervallDTO";

/**
 *
 * @export
 * @interface ExternalLaengsverkehrDTO
 */
export interface ExternalLaengsverkehrDTO {
  /**
   *
   * @type {string}
   * @memberof ExternalLaengsverkehrDTO
   */
  id?: string;
  /**
   *
   * @type {Array<ZeitintervallDTO>}
   * @memberof ExternalLaengsverkehrDTO
   */
  zeitintervalle?: Array<ZeitintervallDTO>;
  /**
   *
   * @type {HochrechnungsfaktorDTO}
   * @memberof ExternalLaengsverkehrDTO
   */
  hochrechnungsfaktor?: HochrechnungsfaktorDTO;
  /**
   *
   * @type {number}
   * @memberof ExternalLaengsverkehrDTO
   */
  knotenarm?: number;
  /**
   *
   * @type {Bewegungsrichtung}
   * @memberof ExternalLaengsverkehrDTO
   */
  richtung?: Bewegungsrichtung;
  /**
   *
   * @type {Himmelsrichtung}
   * @memberof ExternalLaengsverkehrDTO
   */
  strassenseite?: Himmelsrichtung;
}

/**
 * Check if a given object implements the ExternalLaengsverkehrDTO interface.
 */
export function instanceOfExternalLaengsverkehrDTO(
  value: object
): value is ExternalLaengsverkehrDTO {
  return true;
}

export function ExternalLaengsverkehrDTOFromJSON(
  json: any
): ExternalLaengsverkehrDTO {
  return ExternalLaengsverkehrDTOFromJSONTyped(json, false);
}

export function ExternalLaengsverkehrDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ExternalLaengsverkehrDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    zeitintervalle:
      json["zeitintervalle"] == null
        ? undefined
        : (json["zeitintervalle"] as Array<any>).map(ZeitintervallDTOFromJSON),
    hochrechnungsfaktor:
      json["hochrechnungsfaktor"] == null
        ? undefined
        : HochrechnungsfaktorDTOFromJSON(json["hochrechnungsfaktor"]),
    knotenarm: json["knotenarm"] == null ? undefined : json["knotenarm"],
    richtung:
      json["richtung"] == null
        ? undefined
        : BewegungsrichtungFromJSON(json["richtung"]),
    strassenseite:
      json["strassenseite"] == null
        ? undefined
        : HimmelsrichtungFromJSON(json["strassenseite"]),
  };
}

export function ExternalLaengsverkehrDTOToJSON(
  json: any
): ExternalLaengsverkehrDTO {
  return ExternalLaengsverkehrDTOToJSONTyped(json, false);
}

export function ExternalLaengsverkehrDTOToJSONTyped(
  value?: ExternalLaengsverkehrDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    zeitintervalle:
      value["zeitintervalle"] == null
        ? undefined
        : (value["zeitintervalle"] as Array<any>).map(ZeitintervallDTOToJSON),
    hochrechnungsfaktor: HochrechnungsfaktorDTOToJSON(
      value["hochrechnungsfaktor"]
    ),
    knotenarm: value["knotenarm"],
    richtung: BewegungsrichtungToJSON(value["richtung"]),
    strassenseite: HimmelsrichtungToJSON(value["strassenseite"]),
  };
}
