/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HochrechnungsfaktorDTO } from './HochrechnungsfaktorDTO';
import {
    HochrechnungsfaktorDTOFromJSON,
    HochrechnungsfaktorDTOFromJSONTyped,
    HochrechnungsfaktorDTOToJSON,
    HochrechnungsfaktorDTOToJSONTyped,
} from './HochrechnungsfaktorDTO';
import type { ZeitintervallDTO } from './ZeitintervallDTO';
import {
    ZeitintervallDTOFromJSON,
    ZeitintervallDTOFromJSONTyped,
    ZeitintervallDTOToJSON,
    ZeitintervallDTOToJSONTyped,
} from './ZeitintervallDTO';

/**
 * 
 * @export
 * @interface ExternalVerkehrsbeziehungDTO
 */
export interface ExternalVerkehrsbeziehungDTO {
    /**
     * 
     * @type {string}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    id?: string;
    /**
     * 
     * @type {Array<ZeitintervallDTO>}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    zeitintervalle?: Array<ZeitintervallDTO>;
    /**
     * 
     * @type {HochrechnungsfaktorDTO}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    hochrechnungsfaktor?: HochrechnungsfaktorDTO;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    isKreuzung?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    von?: number;
    /**
     * 
     * @type {number}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    nach?: number;
    /**
     * 
     * @type {number}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    knotenarm?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    hinein?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    heraus?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    vorbei?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExternalVerkehrsbeziehungDTO
     */
    strassenseite?: ExternalVerkehrsbeziehungDTOStrassenseiteEnum;
}


/**
 * @export
 */
export const ExternalVerkehrsbeziehungDTOStrassenseiteEnum = {
    N: 'N',
    No: 'NO',
    O: 'O',
    So: 'SO',
    S: 'S',
    Sw: 'SW',
    W: 'W',
    Nw: 'NW'
} as const;
export type ExternalVerkehrsbeziehungDTOStrassenseiteEnum = typeof ExternalVerkehrsbeziehungDTOStrassenseiteEnum[keyof typeof ExternalVerkehrsbeziehungDTOStrassenseiteEnum];


/**
 * Check if a given object implements the ExternalVerkehrsbeziehungDTO interface.
 */
export function instanceOfExternalVerkehrsbeziehungDTO(value: object): value is ExternalVerkehrsbeziehungDTO {
    return true;
}

export function ExternalVerkehrsbeziehungDTOFromJSON(json: any): ExternalVerkehrsbeziehungDTO {
    return ExternalVerkehrsbeziehungDTOFromJSONTyped(json, false);
}

export function ExternalVerkehrsbeziehungDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalVerkehrsbeziehungDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'zeitintervalle': json['zeitintervalle'] == null ? undefined : ((json['zeitintervalle'] as Array<any>).map(ZeitintervallDTOFromJSON)),
        'hochrechnungsfaktor': json['hochrechnungsfaktor'] == null ? undefined : HochrechnungsfaktorDTOFromJSON(json['hochrechnungsfaktor']),
        'isKreuzung': json['isKreuzung'] == null ? undefined : json['isKreuzung'],
        'von': json['von'] == null ? undefined : json['von'],
        'nach': json['nach'] == null ? undefined : json['nach'],
        'knotenarm': json['knotenarm'] == null ? undefined : json['knotenarm'],
        'hinein': json['hinein'] == null ? undefined : json['hinein'],
        'heraus': json['heraus'] == null ? undefined : json['heraus'],
        'vorbei': json['vorbei'] == null ? undefined : json['vorbei'],
        'strassenseite': json['strassenseite'] == null ? undefined : json['strassenseite'],
    };
}

export function ExternalVerkehrsbeziehungDTOToJSON(json: any): ExternalVerkehrsbeziehungDTO {
    return ExternalVerkehrsbeziehungDTOToJSONTyped(json, false);
}

export function ExternalVerkehrsbeziehungDTOToJSONTyped(value?: ExternalVerkehrsbeziehungDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'zeitintervalle': value['zeitintervalle'] == null ? undefined : ((value['zeitintervalle'] as Array<any>).map(ZeitintervallDTOToJSON)),
        'hochrechnungsfaktor': HochrechnungsfaktorDTOToJSON(value['hochrechnungsfaktor']),
        'isKreuzung': value['isKreuzung'],
        'von': value['von'],
        'nach': value['nach'],
        'knotenarm': value['knotenarm'],
        'hinein': value['hinein'],
        'heraus': value['heraus'],
        'vorbei': value['vorbei'],
        'strassenseite': value['strassenseite'],
    };
}

