/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LadeZaehldatenSteplineDTO } from './LadeZaehldatenSteplineDTO';
import {
    LadeZaehldatenSteplineDTOFromJSON,
    LadeZaehldatenSteplineDTOFromJSONTyped,
    LadeZaehldatenSteplineDTOToJSON,
    LadeZaehldatenSteplineDTOToJSONTyped,
} from './LadeZaehldatenSteplineDTO';
import type { MessstelleAuswertungOptionsDTO } from './MessstelleAuswertungOptionsDTO';
import {
    MessstelleAuswertungOptionsDTOFromJSON,
    MessstelleAuswertungOptionsDTOFromJSONTyped,
    MessstelleAuswertungOptionsDTOToJSON,
    MessstelleAuswertungOptionsDTOToJSONTyped,
} from './MessstelleAuswertungOptionsDTO';

/**
 * 
 * @export
 * @interface GeneratePdfAuswertungRequest
 */
export interface GeneratePdfAuswertungRequest {
    /**
     * 
     * @type {string}
     * @memberof GeneratePdfAuswertungRequest
     */
    department: string;
    /**
     * 
     * @type {MessstelleAuswertungOptionsDTO}
     * @memberof GeneratePdfAuswertungRequest
     */
    options: MessstelleAuswertungOptionsDTO;
    /**
     * 
     * @type {LadeZaehldatenSteplineDTO}
     * @memberof GeneratePdfAuswertungRequest
     */
    auswertung: LadeZaehldatenSteplineDTO;
    /**
     * 
     * @type {string}
     * @memberof GeneratePdfAuswertungRequest
     */
    chartAsBase64Png?: string;
}

/**
 * Check if a given object implements the GeneratePdfAuswertungRequest interface.
 */
export function instanceOfGeneratePdfAuswertungRequest(value: object): value is GeneratePdfAuswertungRequest {
    if (!('department' in value) || value['department'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('auswertung' in value) || value['auswertung'] === undefined) return false;
    return true;
}

export function GeneratePdfAuswertungRequestFromJSON(json: any): GeneratePdfAuswertungRequest {
    return GeneratePdfAuswertungRequestFromJSONTyped(json, false);
}

export function GeneratePdfAuswertungRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePdfAuswertungRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'department': json['department'],
        'options': MessstelleAuswertungOptionsDTOFromJSON(json['options']),
        'auswertung': LadeZaehldatenSteplineDTOFromJSON(json['auswertung']),
        'chartAsBase64Png': json['chartAsBase64Png'] == null ? undefined : json['chartAsBase64Png'],
    };
}

export function GeneratePdfAuswertungRequestToJSON(json: any): GeneratePdfAuswertungRequest {
    return GeneratePdfAuswertungRequestToJSONTyped(json, false);
}

export function GeneratePdfAuswertungRequestToJSONTyped(value?: GeneratePdfAuswertungRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'department': value['department'],
        'options': MessstelleAuswertungOptionsDTOToJSON(value['options']),
        'auswertung': LadeZaehldatenSteplineDTOToJSON(value['auswertung']),
        'chartAsBase64Png': value['chartAsBase64Png'],
    };
}

