/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneratePdfReportRequestAssetsInner } from './GeneratePdfReportRequestAssetsInner';
import {
    GeneratePdfReportRequestAssetsInnerFromJSON,
    GeneratePdfReportRequestAssetsInnerFromJSONTyped,
    GeneratePdfReportRequestAssetsInnerToJSON,
    GeneratePdfReportRequestAssetsInnerToJSONTyped,
} from './GeneratePdfReportRequestAssetsInner';

/**
 * 
 * @export
 * @interface GeneratePdfReportRequest
 */
export interface GeneratePdfReportRequest {
    /**
     * 
     * @type {Array<GeneratePdfReportRequestAssetsInner>}
     * @memberof GeneratePdfReportRequest
     */
    assets: Array<GeneratePdfReportRequestAssetsInner>;
    /**
     * 
     * @type {string}
     * @memberof GeneratePdfReportRequest
     */
    department: string;
}

/**
 * Check if a given object implements the GeneratePdfReportRequest interface.
 */
export function instanceOfGeneratePdfReportRequest(value: object): value is GeneratePdfReportRequest {
    if (!('assets' in value) || value['assets'] === undefined) return false;
    if (!('department' in value) || value['department'] === undefined) return false;
    return true;
}

export function GeneratePdfReportRequestFromJSON(json: any): GeneratePdfReportRequest {
    return GeneratePdfReportRequestFromJSONTyped(json, false);
}

export function GeneratePdfReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePdfReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assets': ((json['assets'] as Array<any>).map(GeneratePdfReportRequestAssetsInnerFromJSON)),
        'department': json['department'],
    };
}

export function GeneratePdfReportRequestToJSON(json: any): GeneratePdfReportRequest {
    return GeneratePdfReportRequestToJSONTyped(json, false);
}

export function GeneratePdfReportRequestToJSONTyped(value?: GeneratePdfReportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assets': ((value['assets'] as Array<any>).map(GeneratePdfReportRequestAssetsInnerToJSON)),
        'department': value['department'],
    };
}

