/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OptionsDTO } from "./OptionsDTO";

import { mapValues } from "../runtime";
import {
  OptionsDTOFromJSON,
  OptionsDTOFromJSONTyped,
  OptionsDTOToJSON,
  OptionsDTOToJSONTyped,
} from "./OptionsDTO";

/**
 *
 * @export
 * @interface GeneratePdfRequest
 */
export interface GeneratePdfRequest {
  /**
   *
   * @type {string}
   * @memberof GeneratePdfRequest
   */
  department: string;
  /**
   *
   * @type {OptionsDTO}
   * @memberof GeneratePdfRequest
   */
  options: OptionsDTO;
  /**
   *
   * @type {string}
   * @memberof GeneratePdfRequest
   */
  chartAsBase64Png?: string;
  /**
   *
   * @type {string}
   * @memberof GeneratePdfRequest
   */
  schematischeUebersichtAsBase64Png?: string;
}

/**
 * Check if a given object implements the GeneratePdfRequest interface.
 */
export function instanceOfGeneratePdfRequest(
  value: object
): value is GeneratePdfRequest {
  if (!("department" in value) || value["department"] === undefined)
    return false;
  if (!("options" in value) || value["options"] === undefined) return false;
  return true;
}

export function GeneratePdfRequestFromJSON(json: any): GeneratePdfRequest {
  return GeneratePdfRequestFromJSONTyped(json, false);
}

export function GeneratePdfRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GeneratePdfRequest {
  if (json == null) {
    return json;
  }
  return {
    department: json["department"],
    options: OptionsDTOFromJSON(json["options"]),
    chartAsBase64Png:
      json["chartAsBase64Png"] == null ? undefined : json["chartAsBase64Png"],
    schematischeUebersichtAsBase64Png:
      json["schematischeUebersichtAsBase64Png"] == null
        ? undefined
        : json["schematischeUebersichtAsBase64Png"],
  };
}

export function GeneratePdfRequestToJSON(json: any): GeneratePdfRequest {
  return GeneratePdfRequestToJSONTyped(json, false);
}

export function GeneratePdfRequestToJSONTyped(
  value?: GeneratePdfRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    department: value["department"],
    options: OptionsDTOToJSON(value["options"]),
    chartAsBase64Png: value["chartAsBase64Png"],
    schematischeUebersichtAsBase64Png:
      value["schematischeUebersichtAsBase64Png"],
  };
}
