/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseAsset } from './BaseAsset';
import {
    BaseAssetFromJSON,
    BaseAssetFromJSONTyped,
    BaseAssetToJSON,
    BaseAssetToJSONTyped,
} from './BaseAsset';

/**
 * 
 * @export
 * @interface HeadingAsset
 */
export interface HeadingAsset extends BaseAsset {
    /**
     * 
     * @type {string}
     * @memberof HeadingAsset
     */
    text?: string;
}



/**
 * Check if a given object implements the HeadingAsset interface.
 */
export function instanceOfHeadingAsset(value: object): value is HeadingAsset {
    return true;
}

export function HeadingAssetFromJSON(json: any): HeadingAsset {
    return HeadingAssetFromJSONTyped(json, false);
}

export function HeadingAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadingAsset {
    if (json == null) {
        return json;
    }
    return {
        ...BaseAssetFromJSONTyped(json, true),
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function HeadingAssetToJSON(json: any): HeadingAsset {
    return HeadingAssetToJSONTyped(json, false);
}

export function HeadingAssetToJSONTyped(value?: HeadingAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseAssetToJSONTyped(value, true),
        'text': value['text'],
    };
}

