/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Hochrechnungsfaktor
 */
export interface Hochrechnungsfaktor {
  /**
   *
   * @type {string}
   * @memberof Hochrechnungsfaktor
   */
  matrix?: string;
  /**
   *
   * @type {number}
   * @memberof Hochrechnungsfaktor
   */
  kfz?: number;
  /**
   *
   * @type {number}
   * @memberof Hochrechnungsfaktor
   */
  sv?: number;
  /**
   *
   * @type {number}
   * @memberof Hochrechnungsfaktor
   */
  gv?: number;
  /**
   *
   * @type {boolean}
   * @memberof Hochrechnungsfaktor
   */
  active?: boolean;
}

/**
 * Check if a given object implements the Hochrechnungsfaktor interface.
 */
export function instanceOfHochrechnungsfaktor(
  value: object
): value is Hochrechnungsfaktor {
  return true;
}

export function HochrechnungsfaktorFromJSON(json: any): Hochrechnungsfaktor {
  return HochrechnungsfaktorFromJSONTyped(json, false);
}

export function HochrechnungsfaktorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Hochrechnungsfaktor {
  if (json == null) {
    return json;
  }
  return {
    matrix: json["matrix"] == null ? undefined : json["matrix"],
    kfz: json["kfz"] == null ? undefined : json["kfz"],
    sv: json["sv"] == null ? undefined : json["sv"],
    gv: json["gv"] == null ? undefined : json["gv"],
    active: json["active"] == null ? undefined : json["active"],
  };
}

export function HochrechnungsfaktorToJSON(json: any): Hochrechnungsfaktor {
  return HochrechnungsfaktorToJSONTyped(json, false);
}

export function HochrechnungsfaktorToJSONTyped(
  value?: Hochrechnungsfaktor | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    matrix: value["matrix"],
    kfz: value["kfz"],
    sv: value["sv"],
    gv: value["gv"],
    active: value["active"],
  };
}
