/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BaseAsset } from "./BaseAsset";

import { mapValues } from "../runtime";
import {
  BaseAssetFromJSON,
  BaseAssetFromJSONTyped,
  BaseAssetToJSON,
  BaseAssetToJSONTyped,
} from "./BaseAsset";

/**
 *
 * @export
 * @interface ImageAsset
 */
export interface ImageAsset extends BaseAsset {
  /**
   *
   * @type {string}
   * @memberof ImageAsset
   */
  caption?: string;
  /**
   *
   * @type {string}
   * @memberof ImageAsset
   */
  image?: string;
  /**
   *
   * @type {number}
   * @memberof ImageAsset
   */
  width?: number;
}

/**
 * Check if a given object implements the ImageAsset interface.
 */
export function instanceOfImageAsset(value: object): value is ImageAsset {
  return true;
}

export function ImageAssetFromJSON(json: any): ImageAsset {
  return ImageAssetFromJSONTyped(json, false);
}

export function ImageAssetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ImageAsset {
  if (json == null) {
    return json;
  }
  return {
    ...BaseAssetFromJSONTyped(json, true),
    caption: json["caption"] == null ? undefined : json["caption"],
    image: json["image"] == null ? undefined : json["image"],
    width: json["width"] == null ? undefined : json["width"],
  };
}

export function ImageAssetToJSON(json: any): ImageAsset {
  return ImageAssetToJSONTyped(json, false);
}

export function ImageAssetToJSONTyped(
  value?: ImageAsset | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ...BaseAssetToJSONTyped(value, true),
    caption: value["caption"],
    image: value["image"],
    width: value["width"],
  };
}
