/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuerungsverkehrValue } from './QuerungsverkehrValue';
import {
    QuerungsverkehrValueFromJSON,
    QuerungsverkehrValueFromJSONTyped,
    QuerungsverkehrValueToJSON,
    QuerungsverkehrValueToJSONTyped,
} from './QuerungsverkehrValue';

/**
 * 
 * @export
 * @interface KnotenarmValue
 */
export interface KnotenarmValue {
    /**
     * 
     * @type {number}
     * @memberof KnotenarmValue
     */
    knotenarm?: number;
    /**
     * 
     * @type {number}
     * @memberof KnotenarmValue
     */
    sumKnotenarm?: number;
    /**
     * 
     * @type {Array<QuerungsverkehrValue>}
     * @memberof KnotenarmValue
     */
    valuesQuerungsverkehre?: Array<QuerungsverkehrValue>;
}

/**
 * Check if a given object implements the KnotenarmValue interface.
 */
export function instanceOfKnotenarmValue(value: object): value is KnotenarmValue {
    return true;
}

export function KnotenarmValueFromJSON(json: any): KnotenarmValue {
    return KnotenarmValueFromJSONTyped(json, false);
}

export function KnotenarmValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): KnotenarmValue {
    if (json == null) {
        return json;
    }
    return {
        
        'knotenarm': json['knotenarm'] == null ? undefined : json['knotenarm'],
        'sumKnotenarm': json['sumKnotenarm'] == null ? undefined : json['sumKnotenarm'],
        'valuesQuerungsverkehre': json['valuesQuerungsverkehre'] == null ? undefined : ((json['valuesQuerungsverkehre'] as Array<any>).map(QuerungsverkehrValueFromJSON)),
    };
}

export function KnotenarmValueToJSON(json: any): KnotenarmValue {
    return KnotenarmValueToJSONTyped(json, false);
}

export function KnotenarmValueToJSONTyped(value?: KnotenarmValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'knotenarm': value['knotenarm'],
        'sumKnotenarm': value['sumKnotenarm'],
        'valuesQuerungsverkehre': value['valuesQuerungsverkehre'] == null ? undefined : ((value['valuesQuerungsverkehre'] as Array<any>).map(QuerungsverkehrValueToJSON)),
    };
}

