/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface Knotenarm
 */
export interface Knotenarm {
  /**
   *
   * @type {number}
   * @memberof Knotenarm
   */
  nummer?: number;
  /**
   *
   * @type {string}
   * @memberof Knotenarm
   */
  filename?: string;
  /**
   *
   * @type {string}
   * @memberof Knotenarm
   */
  strassenname?: string;
}

/**
 * Check if a given object implements the Knotenarm interface.
 */
export function instanceOfKnotenarm(value: object): value is Knotenarm {
  return true;
}

export function KnotenarmFromJSON(json: any): Knotenarm {
  return KnotenarmFromJSONTyped(json, false);
}

export function KnotenarmFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Knotenarm {
  if (json == null) {
    return json;
  }
  return {
    nummer: json["nummer"] == null ? undefined : json["nummer"],
    filename: json["filename"] == null ? undefined : json["filename"],
    strassenname:
      json["strassenname"] == null ? undefined : json["strassenname"],
  };
}

export function KnotenarmToJSON(json: any): Knotenarm {
  return KnotenarmToJSONTyped(json, false);
}

export function KnotenarmToJSONTyped(
  value?: Knotenarm | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    nummer: value["nummer"],
    filename: value["filename"],
    strassenname: value["strassenname"],
  };
}
