/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BelastungsplanMessquerschnitteDTO } from "./BelastungsplanMessquerschnitteDTO";
import type { LadeMesswerteListenausgabeDTO } from "./LadeMesswerteListenausgabeDTO";
import type { LadeZaehldatenHeatmapDTO } from "./LadeZaehldatenHeatmapDTO";
import type { LadeZaehldatenSteplineDTO } from "./LadeZaehldatenSteplineDTO";

import { mapValues } from "../runtime";
import {
  BelastungsplanMessquerschnitteDTOFromJSON,
  BelastungsplanMessquerschnitteDTOFromJSONTyped,
  BelastungsplanMessquerschnitteDTOToJSON,
  BelastungsplanMessquerschnitteDTOToJSONTyped,
} from "./BelastungsplanMessquerschnitteDTO";
import {
  LadeMesswerteListenausgabeDTOFromJSON,
  LadeMesswerteListenausgabeDTOFromJSONTyped,
  LadeMesswerteListenausgabeDTOToJSON,
  LadeMesswerteListenausgabeDTOToJSONTyped,
} from "./LadeMesswerteListenausgabeDTO";
import {
  LadeZaehldatenHeatmapDTOFromJSON,
  LadeZaehldatenHeatmapDTOFromJSONTyped,
  LadeZaehldatenHeatmapDTOToJSON,
  LadeZaehldatenHeatmapDTOToJSONTyped,
} from "./LadeZaehldatenHeatmapDTO";
import {
  LadeZaehldatenSteplineDTOFromJSON,
  LadeZaehldatenSteplineDTOFromJSONTyped,
  LadeZaehldatenSteplineDTOToJSON,
  LadeZaehldatenSteplineDTOToJSONTyped,
} from "./LadeZaehldatenSteplineDTO";

/**
 *
 * @export
 * @interface LadeProcessedMesswerteDTO
 */
export interface LadeProcessedMesswerteDTO {
  /**
   *
   * @type {string}
   * @memberof LadeProcessedMesswerteDTO
   */
  tagesTyp: LadeProcessedMesswerteDTOTagesTypEnum;
  /**
   *
   * @type {LadeMesswerteListenausgabeDTO}
   * @memberof LadeProcessedMesswerteDTO
   */
  zaehldatenTable: LadeMesswerteListenausgabeDTO;
  /**
   *
   * @type {LadeZaehldatenSteplineDTO}
   * @memberof LadeProcessedMesswerteDTO
   */
  zaehldatenStepline: LadeZaehldatenSteplineDTO;
  /**
   *
   * @type {LadeZaehldatenHeatmapDTO}
   * @memberof LadeProcessedMesswerteDTO
   */
  zaehldatenHeatmap: LadeZaehldatenHeatmapDTO;
  /**
   *
   * @type {BelastungsplanMessquerschnitteDTO}
   * @memberof LadeProcessedMesswerteDTO
   */
  belastungsplanMessquerschnitte: BelastungsplanMessquerschnitteDTO;
  /**
   *
   * @type {number}
   * @memberof LadeProcessedMesswerteDTO
   */
  requestedMeasuringDays: number;
  /**
   *
   * @type {number}
   * @memberof LadeProcessedMesswerteDTO
   */
  includedMeasuringDays: number;
}

/**
 * @export
 */
export const LadeProcessedMesswerteDTOTagesTypEnum = {
  Unspecified: "UNSPECIFIED",
  WerktagDiMiDo: "WERKTAG_DI_MI_DO",
  WerktagMoFr: "WERKTAG_MO_FR",
  Samstag: "SAMSTAG",
  SonntagFeiertag: "SONNTAG_FEIERTAG",
  WerktagFerien: "WERKTAG_FERIEN",
  MoSo: "MO_SO",
} as const;
export type LadeProcessedMesswerteDTOTagesTypEnum =
  (typeof LadeProcessedMesswerteDTOTagesTypEnum)[keyof typeof LadeProcessedMesswerteDTOTagesTypEnum];

/**
 * Check if a given object implements the LadeProcessedMesswerteDTO interface.
 */
export function instanceOfLadeProcessedMesswerteDTO(
  value: object
): value is LadeProcessedMesswerteDTO {
  if (!("tagesTyp" in value) || value["tagesTyp"] === undefined) return false;
  if (!("zaehldatenTable" in value) || value["zaehldatenTable"] === undefined)
    return false;
  if (
    !("zaehldatenStepline" in value) ||
    value["zaehldatenStepline"] === undefined
  )
    return false;
  if (
    !("zaehldatenHeatmap" in value) ||
    value["zaehldatenHeatmap"] === undefined
  )
    return false;
  if (
    !("belastungsplanMessquerschnitte" in value) ||
    value["belastungsplanMessquerschnitte"] === undefined
  )
    return false;
  if (
    !("requestedMeasuringDays" in value) ||
    value["requestedMeasuringDays"] === undefined
  )
    return false;
  if (
    !("includedMeasuringDays" in value) ||
    value["includedMeasuringDays"] === undefined
  )
    return false;
  return true;
}

export function LadeProcessedMesswerteDTOFromJSON(
  json: any
): LadeProcessedMesswerteDTO {
  return LadeProcessedMesswerteDTOFromJSONTyped(json, false);
}

export function LadeProcessedMesswerteDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LadeProcessedMesswerteDTO {
  if (json == null) {
    return json;
  }
  return {
    tagesTyp: json["tagesTyp"],
    zaehldatenTable: LadeMesswerteListenausgabeDTOFromJSON(
      json["zaehldatenTable"]
    ),
    zaehldatenStepline: LadeZaehldatenSteplineDTOFromJSON(
      json["zaehldatenStepline"]
    ),
    zaehldatenHeatmap: LadeZaehldatenHeatmapDTOFromJSON(
      json["zaehldatenHeatmap"]
    ),
    belastungsplanMessquerschnitte: BelastungsplanMessquerschnitteDTOFromJSON(
      json["belastungsplanMessquerschnitte"]
    ),
    requestedMeasuringDays: json["requestedMeasuringDays"],
    includedMeasuringDays: json["includedMeasuringDays"],
  };
}

export function LadeProcessedMesswerteDTOToJSON(
  json: any
): LadeProcessedMesswerteDTO {
  return LadeProcessedMesswerteDTOToJSONTyped(json, false);
}

export function LadeProcessedMesswerteDTOToJSONTyped(
  value?: LadeProcessedMesswerteDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    tagesTyp: value["tagesTyp"],
    zaehldatenTable: LadeMesswerteListenausgabeDTOToJSON(
      value["zaehldatenTable"]
    ),
    zaehldatenStepline: LadeZaehldatenSteplineDTOToJSON(
      value["zaehldatenStepline"]
    ),
    zaehldatenHeatmap: LadeZaehldatenHeatmapDTOToJSON(
      value["zaehldatenHeatmap"]
    ),
    belastungsplanMessquerschnitte: BelastungsplanMessquerschnitteDTOToJSON(
      value["belastungsplanMessquerschnitte"]
    ),
    requestedMeasuringDays: value["requestedMeasuringDays"],
    includedMeasuringDays: value["includedMeasuringDays"],
  };
}
