/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner } from "./LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner";

import { mapValues } from "../runtime";
import {
  LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerFromJSON,
  LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerFromJSONTyped,
  LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerToJSON,
  LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerToJSONTyped,
} from "./LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner";

/**
 *
 * @export
 * @interface LadeZaehldatenSteplineDTO
 */
export interface LadeZaehldatenSteplineDTO {
  /**
   *
   * @type {Array<string>}
   * @memberof LadeZaehldatenSteplineDTO
   */
  legend: Array<string>;
  /**
   *
   * @type {number}
   * @memberof LadeZaehldatenSteplineDTO
   */
  rangeMax: number;
  /**
   *
   * @type {number}
   * @memberof LadeZaehldatenSteplineDTO
   */
  rangeMaxPercent: number;
  /**
   *
   * @type {Array<LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner>}
   * @memberof LadeZaehldatenSteplineDTO
   */
  seriesEntriesFirstChart: Array<LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner>;
  /**
   *
   * @type {Array<LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner>}
   * @memberof LadeZaehldatenSteplineDTO
   */
  seriesEntriesSecondChart?: Array<LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInner>;
  /**
   *
   * @type {Array<string>}
   * @memberof LadeZaehldatenSteplineDTO
   */
  xaxisDataFirstChart?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof LadeZaehldatenSteplineDTO
   */
  xaxisDataSecondChart?: Array<string>;
}

/**
 * Check if a given object implements the LadeZaehldatenSteplineDTO interface.
 */
export function instanceOfLadeZaehldatenSteplineDTO(
  value: object
): value is LadeZaehldatenSteplineDTO {
  if (!("legend" in value) || value["legend"] === undefined) return false;
  if (!("rangeMax" in value) || value["rangeMax"] === undefined) return false;
  if (!("rangeMaxPercent" in value) || value["rangeMaxPercent"] === undefined)
    return false;
  if (
    !("seriesEntriesFirstChart" in value) ||
    value["seriesEntriesFirstChart"] === undefined
  )
    return false;
  return true;
}

export function LadeZaehldatenSteplineDTOFromJSON(
  json: any
): LadeZaehldatenSteplineDTO {
  return LadeZaehldatenSteplineDTOFromJSONTyped(json, false);
}

export function LadeZaehldatenSteplineDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LadeZaehldatenSteplineDTO {
  if (json == null) {
    return json;
  }
  return {
    legend: json["legend"],
    rangeMax: json["rangeMax"],
    rangeMaxPercent: json["rangeMaxPercent"],
    seriesEntriesFirstChart: (
      json["seriesEntriesFirstChart"] as Array<any>
    ).map(LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerFromJSON),
    seriesEntriesSecondChart:
      json["seriesEntriesSecondChart"] == null
        ? undefined
        : (json["seriesEntriesSecondChart"] as Array<any>).map(
            LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerFromJSON
          ),
    xaxisDataFirstChart:
      json["xaxisDataFirstChart"] == null
        ? undefined
        : json["xaxisDataFirstChart"],
    xaxisDataSecondChart:
      json["xaxisDataSecondChart"] == null
        ? undefined
        : json["xaxisDataSecondChart"],
  };
}

export function LadeZaehldatenSteplineDTOToJSON(
  json: any
): LadeZaehldatenSteplineDTO {
  return LadeZaehldatenSteplineDTOToJSONTyped(json, false);
}

export function LadeZaehldatenSteplineDTOToJSONTyped(
  value?: LadeZaehldatenSteplineDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    legend: value["legend"],
    rangeMax: value["rangeMax"],
    rangeMaxPercent: value["rangeMaxPercent"],
    seriesEntriesFirstChart: (
      value["seriesEntriesFirstChart"] as Array<any>
    ).map(LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerToJSON),
    seriesEntriesSecondChart:
      value["seriesEntriesSecondChart"] == null
        ? undefined
        : (value["seriesEntriesSecondChart"] as Array<any>).map(
            LadeZaehldatenSteplineDTOSeriesEntriesFirstChartInnerToJSON
          ),
    xaxisDataFirstChart: value["xaxisDataFirstChart"],
    xaxisDataSecondChart: value["xaxisDataSecondChart"],
  };
}
