/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LadeMesswerteDTO
 */
export interface LadeMesswerteDTO {
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    sortingIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof LadeMesswerteDTO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof LadeMesswerteDTO
     */
    startUhrzeit?: string;
    /**
     * 
     * @type {string}
     * @memberof LadeMesswerteDTO
     */
    endeUhrzeit?: string;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    pkw?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    lkw?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    lfw?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    lastzuege?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    busse?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    kraftraeder?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    fahrradfahrer?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    fussgaenger?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    kfz?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    schwerverkehr?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    gueterverkehr?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    anteilSchwerverkehrAnKfzProzent?: number;
    /**
     * 
     * @type {number}
     * @memberof LadeMesswerteDTO
     */
    anteilGueterverkehrAnKfzProzent?: number;
}

/**
 * Check if a given object implements the LadeMesswerteDTO interface.
 */
export function instanceOfLadeMesswerteDTO(value: object): value is LadeMesswerteDTO {
    return true;
}

export function LadeMesswerteDTOFromJSON(json: any): LadeMesswerteDTO {
    return LadeMesswerteDTOFromJSONTyped(json, false);
}

export function LadeMesswerteDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LadeMesswerteDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'sortingIndex': json['sortingIndex'] == null ? undefined : json['sortingIndex'],
        'type': json['type'] == null ? undefined : json['type'],
        'startUhrzeit': json['startUhrzeit'] == null ? undefined : json['startUhrzeit'],
        'endeUhrzeit': json['endeUhrzeit'] == null ? undefined : json['endeUhrzeit'],
        'pkw': json['pkw'] == null ? undefined : json['pkw'],
        'lkw': json['lkw'] == null ? undefined : json['lkw'],
        'lfw': json['lfw'] == null ? undefined : json['lfw'],
        'lastzuege': json['lastzuege'] == null ? undefined : json['lastzuege'],
        'busse': json['busse'] == null ? undefined : json['busse'],
        'kraftraeder': json['kraftraeder'] == null ? undefined : json['kraftraeder'],
        'fahrradfahrer': json['fahrradfahrer'] == null ? undefined : json['fahrradfahrer'],
        'fussgaenger': json['fussgaenger'] == null ? undefined : json['fussgaenger'],
        'kfz': json['kfz'] == null ? undefined : json['kfz'],
        'schwerverkehr': json['schwerverkehr'] == null ? undefined : json['schwerverkehr'],
        'gueterverkehr': json['gueterverkehr'] == null ? undefined : json['gueterverkehr'],
        'anteilSchwerverkehrAnKfzProzent': json['anteilSchwerverkehrAnKfzProzent'] == null ? undefined : json['anteilSchwerverkehrAnKfzProzent'],
        'anteilGueterverkehrAnKfzProzent': json['anteilGueterverkehrAnKfzProzent'] == null ? undefined : json['anteilGueterverkehrAnKfzProzent'],
    };
}

export function LadeMesswerteDTOToJSON(json: any): LadeMesswerteDTO {
    return LadeMesswerteDTOToJSONTyped(json, false);
}

export function LadeMesswerteDTOToJSONTyped(value?: LadeMesswerteDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortingIndex': value['sortingIndex'],
        'type': value['type'],
        'startUhrzeit': value['startUhrzeit'],
        'endeUhrzeit': value['endeUhrzeit'],
        'pkw': value['pkw'],
        'lkw': value['lkw'],
        'lfw': value['lfw'],
        'lastzuege': value['lastzuege'],
        'busse': value['busse'],
        'kraftraeder': value['kraftraeder'],
        'fahrradfahrer': value['fahrradfahrer'],
        'fussgaenger': value['fussgaenger'],
        'kfz': value['kfz'],
        'schwerverkehr': value['schwerverkehr'],
        'gueterverkehr': value['gueterverkehr'],
        'anteilSchwerverkehrAnKfzProzent': value['anteilSchwerverkehrAnKfzProzent'],
        'anteilGueterverkehrAnKfzProzent': value['anteilGueterverkehrAnKfzProzent'],
    };
}

