/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LadeZaehlungWithUnreadMessageDTO } from "./LadeZaehlungWithUnreadMessageDTO";

import { mapValues } from "../runtime";
import {
  LadeZaehlungWithUnreadMessageDTOFromJSON,
  LadeZaehlungWithUnreadMessageDTOFromJSONTyped,
  LadeZaehlungWithUnreadMessageDTOToJSON,
  LadeZaehlungWithUnreadMessageDTOToJSONTyped,
} from "./LadeZaehlungWithUnreadMessageDTO";

/**
 *
 * @export
 * @interface LadeZaehlstelleWithUnreadMessageDTO
 */
export interface LadeZaehlstelleWithUnreadMessageDTO {
  /**
   *
   * @type {string}
   * @memberof LadeZaehlstelleWithUnreadMessageDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof LadeZaehlstelleWithUnreadMessageDTO
   */
  nummer?: string;
  /**
   *
   * @type {number}
   * @memberof LadeZaehlstelleWithUnreadMessageDTO
   */
  lat?: number;
  /**
   *
   * @type {number}
   * @memberof LadeZaehlstelleWithUnreadMessageDTO
   */
  lng?: number;
  /**
   *
   * @type {Array<LadeZaehlungWithUnreadMessageDTO>}
   * @memberof LadeZaehlstelleWithUnreadMessageDTO
   */
  zaehlungen?: Array<LadeZaehlungWithUnreadMessageDTO>;
}

/**
 * Check if a given object implements the LadeZaehlstelleWithUnreadMessageDTO interface.
 */
export function instanceOfLadeZaehlstelleWithUnreadMessageDTO(
  value: object
): value is LadeZaehlstelleWithUnreadMessageDTO {
  return true;
}

export function LadeZaehlstelleWithUnreadMessageDTOFromJSON(
  json: any
): LadeZaehlstelleWithUnreadMessageDTO {
  return LadeZaehlstelleWithUnreadMessageDTOFromJSONTyped(json, false);
}

export function LadeZaehlstelleWithUnreadMessageDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LadeZaehlstelleWithUnreadMessageDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    nummer: json["nummer"] == null ? undefined : json["nummer"],
    lat: json["lat"] == null ? undefined : json["lat"],
    lng: json["lng"] == null ? undefined : json["lng"],
    zaehlungen:
      json["zaehlungen"] == null
        ? undefined
        : (json["zaehlungen"] as Array<any>).map(
            LadeZaehlungWithUnreadMessageDTOFromJSON
          ),
  };
}

export function LadeZaehlstelleWithUnreadMessageDTOToJSON(
  json: any
): LadeZaehlstelleWithUnreadMessageDTO {
  return LadeZaehlstelleWithUnreadMessageDTOToJSONTyped(json, false);
}

export function LadeZaehlstelleWithUnreadMessageDTOToJSONTyped(
  value?: LadeZaehlstelleWithUnreadMessageDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    nummer: value["nummer"],
    lat: value["lat"],
    lng: value["lng"],
    zaehlungen:
      value["zaehlungen"] == null
        ? undefined
        : (value["zaehlungen"] as Array<any>).map(
            LadeZaehlungWithUnreadMessageDTOToJSON
          ),
  };
}
