/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LadeZaehlungVisumDTO } from './LadeZaehlungVisumDTO';
import {
    LadeZaehlungVisumDTOFromJSON,
    LadeZaehlungVisumDTOFromJSONTyped,
    LadeZaehlungVisumDTOToJSON,
    LadeZaehlungVisumDTOToJSONTyped,
} from './LadeZaehlungVisumDTO';
import type { PositionUTM } from './PositionUTM';
import {
    PositionUTMFromJSON,
    PositionUTMFromJSONTyped,
    PositionUTMToJSON,
    PositionUTMToJSONTyped,
} from './PositionUTM';

/**
 * 
 * @export
 * @interface LadeZaehlstelleVisumDTO
 */
export interface LadeZaehlstelleVisumDTO {
    /**
     * 
     * @type {string}
     * @memberof LadeZaehlstelleVisumDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LadeZaehlstelleVisumDTO
     */
    nummer?: string;
    /**
     * 
     * @type {number}
     * @memberof LadeZaehlstelleVisumDTO
     */
    stadtbezirkNummer?: number;
    /**
     * 
     * @type {string}
     * @memberof LadeZaehlstelleVisumDTO
     */
    kommentar?: string;
    /**
     * 
     * @type {PositionUTM}
     * @memberof LadeZaehlstelleVisumDTO
     */
    punktUtm?: PositionUTM;
    /**
     * 
     * @type {Array<LadeZaehlungVisumDTO>}
     * @memberof LadeZaehlstelleVisumDTO
     */
    zaehlungen?: Array<LadeZaehlungVisumDTO>;
}

/**
 * Check if a given object implements the LadeZaehlstelleVisumDTO interface.
 */
export function instanceOfLadeZaehlstelleVisumDTO(value: object): value is LadeZaehlstelleVisumDTO {
    return true;
}

export function LadeZaehlstelleVisumDTOFromJSON(json: any): LadeZaehlstelleVisumDTO {
    return LadeZaehlstelleVisumDTOFromJSONTyped(json, false);
}

export function LadeZaehlstelleVisumDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LadeZaehlstelleVisumDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nummer': json['nummer'] == null ? undefined : json['nummer'],
        'stadtbezirkNummer': json['stadtbezirkNummer'] == null ? undefined : json['stadtbezirkNummer'],
        'kommentar': json['kommentar'] == null ? undefined : json['kommentar'],
        'punktUtm': json['punktUtm'] == null ? undefined : PositionUTMFromJSON(json['punktUtm']),
        'zaehlungen': json['zaehlungen'] == null ? undefined : ((json['zaehlungen'] as Array<any>).map(LadeZaehlungVisumDTOFromJSON)),
    };
}

export function LadeZaehlstelleVisumDTOToJSON(json: any): LadeZaehlstelleVisumDTO {
    return LadeZaehlstelleVisumDTOToJSONTyped(json, false);
}

export function LadeZaehlstelleVisumDTOToJSONTyped(value?: LadeZaehlstelleVisumDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nummer': value['nummer'],
        'stadtbezirkNummer': value['stadtbezirkNummer'],
        'kommentar': value['kommentar'],
        'punktUtm': PositionUTMToJSON(value['punktUtm']),
        'zaehlungen': value['zaehlungen'] == null ? undefined : ((value['zaehlungen'] as Array<any>).map(LadeZaehlungVisumDTOToJSON)),
    };
}

