/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BelastungsplanFjsDataDTO } from './BelastungsplanFjsDataDTO';
import {
    BelastungsplanFjsDataDTOFromJSON,
    BelastungsplanFjsDataDTOFromJSONTyped,
    BelastungsplanFjsDataDTOToJSON,
    BelastungsplanFjsDataDTOToJSONTyped,
} from './BelastungsplanFjsDataDTO';
import type { AbstractLadeBelastungsplanDTOObject } from './AbstractLadeBelastungsplanDTOObject';
import {
    AbstractLadeBelastungsplanDTOObjectFromJSON,
    AbstractLadeBelastungsplanDTOObjectFromJSONTyped,
    AbstractLadeBelastungsplanDTOObjectToJSON,
    AbstractLadeBelastungsplanDTOObjectToJSONTyped,
} from './AbstractLadeBelastungsplanDTOObject';

/**
 * 
 * @export
 * @interface LadeBelastungsplanFjsDTO
 */
export interface LadeBelastungsplanFjsDTO extends AbstractLadeBelastungsplanDTOObject {
    /**
     * 
     * @type {BelastungsplanFjsDataDTO}
     * @memberof LadeBelastungsplanFjsDTO
     */
    value1?: BelastungsplanFjsDataDTO;
    /**
     * 
     * @type {BelastungsplanFjsDataDTO}
     * @memberof LadeBelastungsplanFjsDTO
     */
    value2?: BelastungsplanFjsDataDTO;
    /**
     * 
     * @type {BelastungsplanFjsDataDTO}
     * @memberof LadeBelastungsplanFjsDTO
     */
    value3?: BelastungsplanFjsDataDTO;
}

/**
 * Check if a given object implements the LadeBelastungsplanFjsDTO interface.
 */
export function instanceOfLadeBelastungsplanFjsDTO(value: object): value is LadeBelastungsplanFjsDTO {
    return true;
}

export function LadeBelastungsplanFjsDTOFromJSON(json: any): LadeBelastungsplanFjsDTO {
    return LadeBelastungsplanFjsDTOFromJSONTyped(json, false);
}

export function LadeBelastungsplanFjsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LadeBelastungsplanFjsDTO {
    if (json == null) {
        return json;
    }
    return {
        ...AbstractLadeBelastungsplanDTOObjectFromJSONTyped(json, true),
        'value1': json['value1'] == null ? undefined : BelastungsplanFjsDataDTOFromJSON(json['value1']),
        'value2': json['value2'] == null ? undefined : BelastungsplanFjsDataDTOFromJSON(json['value2']),
        'value3': json['value3'] == null ? undefined : BelastungsplanFjsDataDTOFromJSON(json['value3']),
    };
}

export function LadeBelastungsplanFjsDTOToJSON(json: any): LadeBelastungsplanFjsDTO {
    return LadeBelastungsplanFjsDTOToJSONTyped(json, false);
}

export function LadeBelastungsplanFjsDTOToJSONTyped(value?: LadeBelastungsplanFjsDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...AbstractLadeBelastungsplanDTOObjectToJSONTyped(value, true),
        'value1': BelastungsplanFjsDataDTOToJSON(value['value1']),
        'value2': BelastungsplanFjsDataDTOToJSON(value['value2']),
        'value3': BelastungsplanFjsDataDTOToJSON(value['value3']),
    };
}

