/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Bewegungsrichtung } from "./Bewegungsrichtung";

import { mapValues } from "../runtime";
import {
  BewegungsrichtungFromJSON,
  BewegungsrichtungFromJSONTyped,
  BewegungsrichtungToJSON,
  BewegungsrichtungToJSONTyped,
} from "./Bewegungsrichtung";

/**
 *
 * @export
 * @interface LaengsverkehrValue
 */
export interface LaengsverkehrValue {
  /**
   *
   * @type {Bewegungsrichtung}
   * @memberof LaengsverkehrValue
   */
  richtung: Bewegungsrichtung;
  /**
   *
   * @type {number}
   * @memberof LaengsverkehrValue
   */
  value: number;
}

/**
 * Check if a given object implements the LaengsverkehrValue interface.
 */
export function instanceOfLaengsverkehrValue(
  value: object
): value is LaengsverkehrValue {
  if (!("richtung" in value) || value["richtung"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function LaengsverkehrValueFromJSON(json: any): LaengsverkehrValue {
  return LaengsverkehrValueFromJSONTyped(json, false);
}

export function LaengsverkehrValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LaengsverkehrValue {
  if (json == null) {
    return json;
  }
  return {
    richtung: BewegungsrichtungFromJSON(json["richtung"]),
    value: json["value"],
  };
}

export function LaengsverkehrValueToJSON(json: any): LaengsverkehrValue {
  return LaengsverkehrValueToJSONTyped(json, false);
}

export function LaengsverkehrValueToJSONTyped(
  value?: LaengsverkehrValue | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    richtung: BewegungsrichtungToJSON(value["richtung"]),
    value: value["value"],
  };
}
