/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Bewegungsrichtung } from "./Bewegungsrichtung";
import type { Himmelsrichtung } from "./Himmelsrichtung";

import { mapValues } from "../runtime";
import {
  BewegungsrichtungFromJSON,
  BewegungsrichtungFromJSONTyped,
  BewegungsrichtungToJSON,
  BewegungsrichtungToJSONTyped,
} from "./Bewegungsrichtung";
import {
  HimmelsrichtungFromJSON,
  HimmelsrichtungFromJSONTyped,
  HimmelsrichtungToJSON,
  HimmelsrichtungToJSONTyped,
} from "./Himmelsrichtung";

/**
 *
 * @export
 * @interface Laengsverkehr
 */
export interface Laengsverkehr {
  /**
   *
   * @type {number}
   * @memberof Laengsverkehr
   */
  knotenarm?: number;
  /**
   *
   * @type {Bewegungsrichtung}
   * @memberof Laengsverkehr
   */
  richtung?: Bewegungsrichtung;
  /**
   *
   * @type {Himmelsrichtung}
   * @memberof Laengsverkehr
   */
  strassenseite?: Himmelsrichtung;
}

/**
 * Check if a given object implements the Laengsverkehr interface.
 */
export function instanceOfLaengsverkehr(value: object): value is Laengsverkehr {
  return true;
}

export function LaengsverkehrFromJSON(json: any): Laengsverkehr {
  return LaengsverkehrFromJSONTyped(json, false);
}

export function LaengsverkehrFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Laengsverkehr {
  if (json == null) {
    return json;
  }
  return {
    knotenarm: json["knotenarm"] == null ? undefined : json["knotenarm"],
    richtung:
      json["richtung"] == null
        ? undefined
        : BewegungsrichtungFromJSON(json["richtung"]),
    strassenseite:
      json["strassenseite"] == null
        ? undefined
        : HimmelsrichtungFromJSON(json["strassenseite"]),
  };
}

export function LaengsverkehrToJSON(json: any): Laengsverkehr {
  return LaengsverkehrToJSONTyped(json, false);
}

export function LaengsverkehrToJSONTyped(
  value?: Laengsverkehr | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    knotenarm: value["knotenarm"],
    richtung: BewegungsrichtungToJSON(value["richtung"]),
    strassenseite: HimmelsrichtungToJSON(value["strassenseite"]),
  };
}
