/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface LayerDTO
 */
export interface LayerDTO {
  /**
   *
   * @type {string}
   * @memberof LayerDTO
   */
  baseUrl: string;
  /**
   *
   * @type {string}
   * @memberof LayerDTO
   */
  layerName: string;
  /**
   *
   * @type {string}
   * @memberof LayerDTO
   */
  layerNameToDisplay: string;
  /**
   *
   * @type {string}
   * @memberof LayerDTO
   */
  attribution: string;
}

/**
 * Check if a given object implements the LayerDTO interface.
 */
export function instanceOfLayerDTO(value: object): value is LayerDTO {
  if (!("baseUrl" in value) || value["baseUrl"] === undefined) return false;
  if (!("layerName" in value) || value["layerName"] === undefined) return false;
  if (
    !("layerNameToDisplay" in value) ||
    value["layerNameToDisplay"] === undefined
  )
    return false;
  if (!("attribution" in value) || value["attribution"] === undefined)
    return false;
  return true;
}

export function LayerDTOFromJSON(json: any): LayerDTO {
  return LayerDTOFromJSONTyped(json, false);
}

export function LayerDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LayerDTO {
  if (json == null) {
    return json;
  }
  return {
    baseUrl: json["baseUrl"],
    layerName: json["layerName"],
    layerNameToDisplay: json["layerNameToDisplay"],
    attribution: json["attribution"],
  };
}

export function LayerDTOToJSON(json: any): LayerDTO {
  return LayerDTOToJSONTyped(json, false);
}

export function LayerDTOToJSONTyped(
  value?: LayerDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    baseUrl: value["baseUrl"],
    layerName: value["layerName"],
    layerNameToDisplay: value["layerNameToDisplay"],
    attribution: value["attribution"],
  };
}
