/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Knotenarm } from "./Knotenarm";
import type { Laengsverkehr } from "./Laengsverkehr";
import type { PkwEinheit } from "./PkwEinheit";
import type { Querungsverkehr } from "./Querungsverkehr";
import type { Verkehrsbeziehung } from "./Verkehrsbeziehung";
import type { ZeitauswahlDTO } from "./ZeitauswahlDTO";

import { mapValues } from "../runtime";
import {
  KnotenarmFromJSON,
  KnotenarmFromJSONTyped,
  KnotenarmToJSON,
  KnotenarmToJSONTyped,
} from "./Knotenarm";
import {
  LaengsverkehrFromJSON,
  LaengsverkehrFromJSONTyped,
  LaengsverkehrToJSON,
  LaengsverkehrToJSONTyped,
} from "./Laengsverkehr";
import {
  PkwEinheitFromJSON,
  PkwEinheitFromJSONTyped,
  PkwEinheitToJSON,
  PkwEinheitToJSONTyped,
} from "./PkwEinheit";
import {
  QuerungsverkehrFromJSON,
  QuerungsverkehrFromJSONTyped,
  QuerungsverkehrToJSON,
  QuerungsverkehrToJSONTyped,
} from "./Querungsverkehr";
import {
  VerkehrsbeziehungFromJSON,
  VerkehrsbeziehungFromJSONTyped,
  VerkehrsbeziehungToJSON,
  VerkehrsbeziehungToJSONTyped,
} from "./Verkehrsbeziehung";
import {
  ZeitauswahlDTOFromJSON,
  ZeitauswahlDTOFromJSONTyped,
  ZeitauswahlDTOToJSON,
  ZeitauswahlDTOToJSONTyped,
} from "./ZeitauswahlDTO";

/**
 *
 * @export
 * @interface LeseZaehlungDTO
 */
export interface LeseZaehlungDTO {
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof LeseZaehlungDTO
   */
  datum?: Date;
  /**
   *
   * @type {number}
   * @memberof LeseZaehlungDTO
   */
  jahr?: number;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  monat?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  jahreszeit?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  zaehlart?: string;
  /**
   *
   * @type {number}
   * @memberof LeseZaehlungDTO
   */
  lat?: number;
  /**
   *
   * @type {number}
   * @memberof LeseZaehlungDTO
   */
  lng?: number;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  tagesTyp?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  projektNummer?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  projektName?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  kreuzungsname?: string;
  /**
   *
   * @type {boolean}
   * @memberof LeseZaehlungDTO
   */
  sonderzaehlung?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof LeseZaehlungDTO
   */
  kreisverkehr?: boolean;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  zaehlsituation?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  zaehlsituationErweitert?: string;
  /**
   *
   * @type {number}
   * @memberof LeseZaehlungDTO
   */
  zaehlIntervall?: number;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  wetter?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  zaehldauer?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  quelle?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  kommentar?: string;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  schulZeiten?: string;
  /**
   *
   * @type {PkwEinheit}
   * @memberof LeseZaehlungDTO
   */
  pkwEinheit?: PkwEinheit;
  /**
   *
   * @type {Array<string>}
   * @memberof LeseZaehlungDTO
   */
  kategorien?: Array<LeseZaehlungDTOKategorienEnum>;
  /**
   *
   * @type {Array<Knotenarm>}
   * @memberof LeseZaehlungDTO
   */
  knotenarme?: Array<Knotenarm>;
  /**
   *
   * @type {Array<Laengsverkehr>}
   * @memberof LeseZaehlungDTO
   */
  laengsverkehr?: Array<Laengsverkehr>;
  /**
   *
   * @type {Array<Querungsverkehr>}
   * @memberof LeseZaehlungDTO
   */
  querungsverkehr?: Array<Querungsverkehr>;
  /**
   *
   * @type {Array<Verkehrsbeziehung>}
   * @memberof LeseZaehlungDTO
   */
  verkehrsbeziehungen?: Array<Verkehrsbeziehung>;
  /**
   *
   * @type {ZeitauswahlDTO}
   * @memberof LeseZaehlungDTO
   */
  zeitauswahl?: ZeitauswahlDTO;
  /**
   *
   * @type {boolean}
   * @memberof LeseZaehlungDTO
   */
  unreadMessagesMobilitaetsreferat?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof LeseZaehlungDTO
   */
  unreadMessagesDienstleister?: boolean;
  /**
   *
   * @type {string}
   * @memberof LeseZaehlungDTO
   */
  dienstleisterkennung?: string;
}

/**
 * @export
 */
export const LeseZaehlungDTOKategorienEnum = {
  Kfz: "KFZ",
  Sv: "SV",
  Gv: "GV",
  SvP: "SV_P",
  GvP: "GV_P",
  Pkw: "PKW",
  Lkw: "LKW",
  Lz: "LZ",
  Bus: "BUS",
  Krad: "KRAD",
  Rad: "RAD",
  Fuss: "FUSS",
  PkwEinheit: "PKW_EINHEIT",
} as const;
export type LeseZaehlungDTOKategorienEnum =
  (typeof LeseZaehlungDTOKategorienEnum)[keyof typeof LeseZaehlungDTOKategorienEnum];

/**
 * Check if a given object implements the LeseZaehlungDTO interface.
 */
export function instanceOfLeseZaehlungDTO(
  value: object
): value is LeseZaehlungDTO {
  return true;
}

export function LeseZaehlungDTOFromJSON(json: any): LeseZaehlungDTO {
  return LeseZaehlungDTOFromJSONTyped(json, false);
}

export function LeseZaehlungDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LeseZaehlungDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    datum: json["datum"] == null ? undefined : new Date(json["datum"]),
    jahr: json["jahr"] == null ? undefined : json["jahr"],
    monat: json["monat"] == null ? undefined : json["monat"],
    jahreszeit: json["jahreszeit"] == null ? undefined : json["jahreszeit"],
    zaehlart: json["zaehlart"] == null ? undefined : json["zaehlart"],
    lat: json["lat"] == null ? undefined : json["lat"],
    lng: json["lng"] == null ? undefined : json["lng"],
    tagesTyp: json["tagesTyp"] == null ? undefined : json["tagesTyp"],
    projektNummer:
      json["projektNummer"] == null ? undefined : json["projektNummer"],
    projektName: json["projektName"] == null ? undefined : json["projektName"],
    kreuzungsname:
      json["kreuzungsname"] == null ? undefined : json["kreuzungsname"],
    sonderzaehlung:
      json["sonderzaehlung"] == null ? undefined : json["sonderzaehlung"],
    kreisverkehr:
      json["kreisverkehr"] == null ? undefined : json["kreisverkehr"],
    status: json["status"] == null ? undefined : json["status"],
    zaehlsituation:
      json["zaehlsituation"] == null ? undefined : json["zaehlsituation"],
    zaehlsituationErweitert:
      json["zaehlsituationErweitert"] == null
        ? undefined
        : json["zaehlsituationErweitert"],
    zaehlIntervall:
      json["zaehlIntervall"] == null ? undefined : json["zaehlIntervall"],
    wetter: json["wetter"] == null ? undefined : json["wetter"],
    zaehldauer: json["zaehldauer"] == null ? undefined : json["zaehldauer"],
    quelle: json["quelle"] == null ? undefined : json["quelle"],
    kommentar: json["kommentar"] == null ? undefined : json["kommentar"],
    schulZeiten: json["schulZeiten"] == null ? undefined : json["schulZeiten"],
    pkwEinheit:
      json["pkwEinheit"] == null
        ? undefined
        : PkwEinheitFromJSON(json["pkwEinheit"]),
    kategorien: json["kategorien"] == null ? undefined : json["kategorien"],
    knotenarme:
      json["knotenarme"] == null
        ? undefined
        : (json["knotenarme"] as Array<any>).map(KnotenarmFromJSON),
    laengsverkehr:
      json["laengsverkehr"] == null
        ? undefined
        : (json["laengsverkehr"] as Array<any>).map(LaengsverkehrFromJSON),
    querungsverkehr:
      json["querungsverkehr"] == null
        ? undefined
        : (json["querungsverkehr"] as Array<any>).map(QuerungsverkehrFromJSON),
    verkehrsbeziehungen:
      json["verkehrsbeziehungen"] == null
        ? undefined
        : (json["verkehrsbeziehungen"] as Array<any>).map(
            VerkehrsbeziehungFromJSON
          ),
    zeitauswahl:
      json["zeitauswahl"] == null
        ? undefined
        : ZeitauswahlDTOFromJSON(json["zeitauswahl"]),
    unreadMessagesMobilitaetsreferat:
      json["unreadMessagesMobilitaetsreferat"] == null
        ? undefined
        : json["unreadMessagesMobilitaetsreferat"],
    unreadMessagesDienstleister:
      json["unreadMessagesDienstleister"] == null
        ? undefined
        : json["unreadMessagesDienstleister"],
    dienstleisterkennung:
      json["dienstleisterkennung"] == null
        ? undefined
        : json["dienstleisterkennung"],
  };
}

export function LeseZaehlungDTOToJSON(json: any): LeseZaehlungDTO {
  return LeseZaehlungDTOToJSONTyped(json, false);
}

export function LeseZaehlungDTOToJSONTyped(
  value?: LeseZaehlungDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    datum: value["datum"] == null ? undefined : value["datum"].toISOString(),
    jahr: value["jahr"],
    monat: value["monat"],
    jahreszeit: value["jahreszeit"],
    zaehlart: value["zaehlart"],
    lat: value["lat"],
    lng: value["lng"],
    tagesTyp: value["tagesTyp"],
    projektNummer: value["projektNummer"],
    projektName: value["projektName"],
    kreuzungsname: value["kreuzungsname"],
    sonderzaehlung: value["sonderzaehlung"],
    kreisverkehr: value["kreisverkehr"],
    status: value["status"],
    zaehlsituation: value["zaehlsituation"],
    zaehlsituationErweitert: value["zaehlsituationErweitert"],
    zaehlIntervall: value["zaehlIntervall"],
    wetter: value["wetter"],
    zaehldauer: value["zaehldauer"],
    quelle: value["quelle"],
    kommentar: value["kommentar"],
    schulZeiten: value["schulZeiten"],
    pkwEinheit: PkwEinheitToJSON(value["pkwEinheit"]),
    kategorien: value["kategorien"],
    knotenarme:
      value["knotenarme"] == null
        ? undefined
        : (value["knotenarme"] as Array<any>).map(KnotenarmToJSON),
    laengsverkehr:
      value["laengsverkehr"] == null
        ? undefined
        : (value["laengsverkehr"] as Array<any>).map(LaengsverkehrToJSON),
    querungsverkehr:
      value["querungsverkehr"] == null
        ? undefined
        : (value["querungsverkehr"] as Array<any>).map(QuerungsverkehrToJSON),
    verkehrsbeziehungen:
      value["verkehrsbeziehungen"] == null
        ? undefined
        : (value["verkehrsbeziehungen"] as Array<any>).map(
            VerkehrsbeziehungToJSON
          ),
    zeitauswahl: ZeitauswahlDTOToJSON(value["zeitauswahl"]),
    unreadMessagesMobilitaetsreferat: value["unreadMessagesMobilitaetsreferat"],
    unreadMessagesDienstleister: value["unreadMessagesDienstleister"],
    dienstleisterkennung: value["dienstleisterkennung"],
  };
}
