/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LayerDTO } from './LayerDTO';
import {
    LayerDTOFromJSON,
    LayerDTOFromJSONTyped,
    LayerDTOToJSON,
    LayerDTOToJSONTyped,
} from './LayerDTO';

/**
 * 
 * @export
 * @interface MapConfigurationDTO
 */
export interface MapConfigurationDTO {
    /**
     * 
     * @type {string}
     * @memberof MapConfigurationDTO
     */
    lat?: string;
    /**
     * 
     * @type {string}
     * @memberof MapConfigurationDTO
     */
    lng?: string;
    /**
     * 
     * @type {number}
     * @memberof MapConfigurationDTO
     */
    zoom?: number;
    /**
     * 
     * @type {Array<LayerDTO>}
     * @memberof MapConfigurationDTO
     */
    baseLayers?: Array<LayerDTO>;
    /**
     * 
     * @type {Array<LayerDTO>}
     * @memberof MapConfigurationDTO
     */
    overlayLayers?: Array<LayerDTO>;
}

/**
 * Check if a given object implements the MapConfigurationDTO interface.
 */
export function instanceOfMapConfigurationDTO(value: object): value is MapConfigurationDTO {
    return true;
}

export function MapConfigurationDTOFromJSON(json: any): MapConfigurationDTO {
    return MapConfigurationDTOFromJSONTyped(json, false);
}

export function MapConfigurationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapConfigurationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lng': json['lng'] == null ? undefined : json['lng'],
        'zoom': json['zoom'] == null ? undefined : json['zoom'],
        'baseLayers': json['baseLayers'] == null ? undefined : ((json['baseLayers'] as Array<any>).map(LayerDTOFromJSON)),
        'overlayLayers': json['overlayLayers'] == null ? undefined : ((json['overlayLayers'] as Array<any>).map(LayerDTOFromJSON)),
    };
}

export function MapConfigurationDTOToJSON(json: any): MapConfigurationDTO {
    return MapConfigurationDTOToJSONTyped(json, false);
}

export function MapConfigurationDTOToJSONTyped(value?: MapConfigurationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lng': value['lng'],
        'zoom': value['zoom'],
        'baseLayers': value['baseLayers'] == null ? undefined : ((value['baseLayers'] as Array<any>).map(LayerDTOToJSON)),
        'overlayLayers': value['overlayLayers'] == null ? undefined : ((value['overlayLayers'] as Array<any>).map(LayerDTOToJSON)),
    };
}

