/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessstelleOverviewDTO
 */
export interface MessstelleOverviewDTO {
    /**
     * 
     * @type {string}
     * @memberof MessstelleOverviewDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MessstelleOverviewDTO
     */
    mstId?: string;
    /**
     * 
     * @type {string}
     * @memberof MessstelleOverviewDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MessstelleOverviewDTO
     */
    status?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessstelleOverviewDTO
     */
    sichtbarDatenportal?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MessstelleOverviewDTO
     */
    geprueft?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MessstelleOverviewDTO
     */
    stadtbezirk?: string;
    /**
     * 
     * @type {string}
     * @memberof MessstelleOverviewDTO
     */
    stadtbezirkNummer?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessstelleOverviewDTO
     */
    lageplanVorhanden?: boolean;
}

/**
 * Check if a given object implements the MessstelleOverviewDTO interface.
 */
export function instanceOfMessstelleOverviewDTO(value: object): value is MessstelleOverviewDTO {
    return true;
}

export function MessstelleOverviewDTOFromJSON(json: any): MessstelleOverviewDTO {
    return MessstelleOverviewDTOFromJSONTyped(json, false);
}

export function MessstelleOverviewDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessstelleOverviewDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'mstId': json['mstId'] == null ? undefined : json['mstId'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'sichtbarDatenportal': json['sichtbarDatenportal'] == null ? undefined : json['sichtbarDatenportal'],
        'geprueft': json['geprueft'] == null ? undefined : json['geprueft'],
        'stadtbezirk': json['stadtbezirk'] == null ? undefined : json['stadtbezirk'],
        'stadtbezirkNummer': json['stadtbezirkNummer'] == null ? undefined : json['stadtbezirkNummer'],
        'lageplanVorhanden': json['lageplanVorhanden'] == null ? undefined : json['lageplanVorhanden'],
    };
}

export function MessstelleOverviewDTOToJSON(json: any): MessstelleOverviewDTO {
    return MessstelleOverviewDTOToJSONTyped(json, false);
}

export function MessstelleOverviewDTOToJSONTyped(value?: MessstelleOverviewDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'mstId': value['mstId'],
        'name': value['name'],
        'status': value['status'],
        'sichtbarDatenportal': value['sichtbarDatenportal'],
        'geprueft': value['geprueft'],
        'stadtbezirk': value['stadtbezirk'],
        'stadtbezirkNummer': value['stadtbezirkNummer'],
        'lageplanVorhanden': value['lageplanVorhanden'],
    };
}

