/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface MessquerschnittAuswertungDTO
 */
export interface MessquerschnittAuswertungDTO {
  /**
   *
   * @type {string}
   * @memberof MessquerschnittAuswertungDTO
   */
  mqId: string;
  /**
   *
   * @type {string}
   * @memberof MessquerschnittAuswertungDTO
   */
  fahrtrichtung?: string;
  /**
   *
   * @type {string}
   * @memberof MessquerschnittAuswertungDTO
   */
  standort?: string;
}

/**
 * Check if a given object implements the MessquerschnittAuswertungDTO interface.
 */
export function instanceOfMessquerschnittAuswertungDTO(
  value: object
): value is MessquerschnittAuswertungDTO {
  if (!("mqId" in value) || value["mqId"] === undefined) return false;
  return true;
}

export function MessquerschnittAuswertungDTOFromJSON(
  json: any
): MessquerschnittAuswertungDTO {
  return MessquerschnittAuswertungDTOFromJSONTyped(json, false);
}

export function MessquerschnittAuswertungDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessquerschnittAuswertungDTO {
  if (json == null) {
    return json;
  }
  return {
    mqId: json["mqId"],
    fahrtrichtung:
      json["fahrtrichtung"] == null ? undefined : json["fahrtrichtung"],
    standort: json["standort"] == null ? undefined : json["standort"],
  };
}

export function MessquerschnittAuswertungDTOToJSON(
  json: any
): MessquerschnittAuswertungDTO {
  return MessquerschnittAuswertungDTOToJSONTyped(json, false);
}

export function MessquerschnittAuswertungDTOToJSONTyped(
  value?: MessquerschnittAuswertungDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    mqId: value["mqId"],
    fahrtrichtung: value["fahrtrichtung"],
    standort: value["standort"],
  };
}
