/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuswertungsZeitraum } from "./AuswertungsZeitraum";
import type { FahrzeugOptionsDTO } from "./FahrzeugOptionsDTO";
import type { MessstelleAuswertungIdDTO } from "./MessstelleAuswertungIdDTO";
import type { TagesTyp } from "./TagesTyp";

import { mapValues } from "../runtime";
import {
  AuswertungsZeitraumFromJSON,
  AuswertungsZeitraumFromJSONTyped,
  AuswertungsZeitraumToJSON,
  AuswertungsZeitraumToJSONTyped,
} from "./AuswertungsZeitraum";
import {
  FahrzeugOptionsDTOFromJSON,
  FahrzeugOptionsDTOFromJSONTyped,
  FahrzeugOptionsDTOToJSON,
  FahrzeugOptionsDTOToJSONTyped,
} from "./FahrzeugOptionsDTO";
import {
  MessstelleAuswertungIdDTOFromJSON,
  MessstelleAuswertungIdDTOFromJSONTyped,
  MessstelleAuswertungIdDTOToJSON,
  MessstelleAuswertungIdDTOToJSONTyped,
} from "./MessstelleAuswertungIdDTO";
import {
  TagesTypFromJSON,
  TagesTypFromJSONTyped,
  TagesTypToJSON,
  TagesTypToJSONTyped,
} from "./TagesTyp";

/**
 *
 * @export
 * @interface MessstelleAuswertungOptionsDTO
 */
export interface MessstelleAuswertungOptionsDTO {
  /**
   *
   * @type {Array<number>}
   * @memberof MessstelleAuswertungOptionsDTO
   */
  jahre: Array<number>;
  /**
   *
   * @type {TagesTyp}
   * @memberof MessstelleAuswertungOptionsDTO
   */
  tagesTyp: TagesTyp;
  /**
   *
   * @type {Array<AuswertungsZeitraum>}
   * @memberof MessstelleAuswertungOptionsDTO
   */
  zeitraum: Array<AuswertungsZeitraum>;
  /**
   *
   * @type {Set<MessstelleAuswertungIdDTO>}
   * @memberof MessstelleAuswertungOptionsDTO
   */
  messstelleAuswertungIds: Set<MessstelleAuswertungIdDTO>;
  /**
   *
   * @type {FahrzeugOptionsDTO}
   * @memberof MessstelleAuswertungOptionsDTO
   */
  fahrzeuge: FahrzeugOptionsDTO;
}

/**
 * Check if a given object implements the MessstelleAuswertungOptionsDTO interface.
 */
export function instanceOfMessstelleAuswertungOptionsDTO(
  value: object
): value is MessstelleAuswertungOptionsDTO {
  if (!("jahre" in value) || value["jahre"] === undefined) return false;
  if (!("tagesTyp" in value) || value["tagesTyp"] === undefined) return false;
  if (!("zeitraum" in value) || value["zeitraum"] === undefined) return false;
  if (
    !("messstelleAuswertungIds" in value) ||
    value["messstelleAuswertungIds"] === undefined
  )
    return false;
  if (!("fahrzeuge" in value) || value["fahrzeuge"] === undefined) return false;
  return true;
}

export function MessstelleAuswertungOptionsDTOFromJSON(
  json: any
): MessstelleAuswertungOptionsDTO {
  return MessstelleAuswertungOptionsDTOFromJSONTyped(json, false);
}

export function MessstelleAuswertungOptionsDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessstelleAuswertungOptionsDTO {
  if (json == null) {
    return json;
  }
  return {
    jahre: json["jahre"],
    tagesTyp: TagesTypFromJSON(json["tagesTyp"]),
    zeitraum: (json["zeitraum"] as Array<any>).map(AuswertungsZeitraumFromJSON),
    messstelleAuswertungIds: new Set(
      (json["messstelleAuswertungIds"] as Array<any>).map(
        MessstelleAuswertungIdDTOFromJSON
      )
    ),
    fahrzeuge: FahrzeugOptionsDTOFromJSON(json["fahrzeuge"]),
  };
}

export function MessstelleAuswertungOptionsDTOToJSON(
  json: any
): MessstelleAuswertungOptionsDTO {
  return MessstelleAuswertungOptionsDTOToJSONTyped(json, false);
}

export function MessstelleAuswertungOptionsDTOToJSONTyped(
  value?: MessstelleAuswertungOptionsDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    jahre: value["jahre"],
    tagesTyp: TagesTypToJSON(value["tagesTyp"]),
    zeitraum: (value["zeitraum"] as Array<any>).map(AuswertungsZeitraumToJSON),
    messstelleAuswertungIds: Array.from(
      value["messstelleAuswertungIds"] as Set<any>
    ).map(MessstelleAuswertungIdDTOToJSON),
    fahrzeuge: FahrzeugOptionsDTOToJSON(value["fahrzeuge"]),
  };
}
