/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FahrzeugOptionsDTO } from "./FahrzeugOptionsDTO";
import type { Rounding } from "./Rounding";
import type { TagesTyp } from "./TagesTyp";
import type { ZaehldatenIntervall } from "./ZaehldatenIntervall";
import type { Zeitblock } from "./Zeitblock";

import { mapValues } from "../runtime";
import {
  FahrzeugOptionsDTOFromJSON,
  FahrzeugOptionsDTOFromJSONTyped,
  FahrzeugOptionsDTOToJSON,
  FahrzeugOptionsDTOToJSONTyped,
} from "./FahrzeugOptionsDTO";
import {
  RoundingFromJSON,
  RoundingFromJSONTyped,
  RoundingToJSON,
  RoundingToJSONTyped,
} from "./Rounding";
import {
  TagesTypFromJSON,
  TagesTypFromJSONTyped,
  TagesTypToJSON,
  TagesTypToJSONTyped,
} from "./TagesTyp";
import {
  ZaehldatenIntervallFromJSON,
  ZaehldatenIntervallFromJSONTyped,
  ZaehldatenIntervallToJSON,
  ZaehldatenIntervallToJSONTyped,
} from "./ZaehldatenIntervall";
import {
  ZeitblockFromJSON,
  ZeitblockFromJSONTyped,
  ZeitblockToJSON,
  ZeitblockToJSONTyped,
} from "./Zeitblock";

/**
 *
 * @export
 * @interface MessstelleOptionsDTO
 */
export interface MessstelleOptionsDTO {
  /**
   *
   * @type {Array<Date>}
   * @memberof MessstelleOptionsDTO
   */
  zeitraum: Array<Date>;
  /**
   *
   * @type {FahrzeugOptionsDTO}
   * @memberof MessstelleOptionsDTO
   */
  fahrzeuge: FahrzeugOptionsDTO;
  /**
   *
   * @type {string}
   * @memberof MessstelleOptionsDTO
   */
  zeitauswahl: string;
  /**
   *
   * @type {Zeitblock}
   * @memberof MessstelleOptionsDTO
   */
  zeitblock: Zeitblock;
  /**
   *
   * @type {TagesTyp}
   * @memberof MessstelleOptionsDTO
   */
  tagesTyp: TagesTyp;
  /**
   *
   * @type {ZaehldatenIntervall}
   * @memberof MessstelleOptionsDTO
   */
  intervall: ZaehldatenIntervall;
  /**
   *
   * @type {Set<string>}
   * @memberof MessstelleOptionsDTO
   */
  messquerschnittIds: Set<string>;
  /**
   *
   * @type {Rounding}
   * @memberof MessstelleOptionsDTO
   */
  rounding: Rounding;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleOptionsDTO
   */
  stundensumme: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleOptionsDTO
   */
  blocksumme: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleOptionsDTO
   */
  tagessumme: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleOptionsDTO
   */
  spitzenstunde: boolean;
}

/**
 * Check if a given object implements the MessstelleOptionsDTO interface.
 */
export function instanceOfMessstelleOptionsDTO(
  value: object
): value is MessstelleOptionsDTO {
  if (!("zeitraum" in value) || value["zeitraum"] === undefined) return false;
  if (!("fahrzeuge" in value) || value["fahrzeuge"] === undefined) return false;
  if (!("zeitauswahl" in value) || value["zeitauswahl"] === undefined)
    return false;
  if (!("zeitblock" in value) || value["zeitblock"] === undefined) return false;
  if (!("tagesTyp" in value) || value["tagesTyp"] === undefined) return false;
  if (!("intervall" in value) || value["intervall"] === undefined) return false;
  if (
    !("messquerschnittIds" in value) ||
    value["messquerschnittIds"] === undefined
  )
    return false;
  if (!("rounding" in value) || value["rounding"] === undefined) return false;
  if (!("stundensumme" in value) || value["stundensumme"] === undefined)
    return false;
  if (!("blocksumme" in value) || value["blocksumme"] === undefined)
    return false;
  if (!("tagessumme" in value) || value["tagessumme"] === undefined)
    return false;
  if (!("spitzenstunde" in value) || value["spitzenstunde"] === undefined)
    return false;
  return true;
}

export function MessstelleOptionsDTOFromJSON(json: any): MessstelleOptionsDTO {
  return MessstelleOptionsDTOFromJSONTyped(json, false);
}

export function MessstelleOptionsDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessstelleOptionsDTO {
  if (json == null) {
    return json;
  }
  return {
    zeitraum: json["zeitraum"],
    fahrzeuge: FahrzeugOptionsDTOFromJSON(json["fahrzeuge"]),
    zeitauswahl: json["zeitauswahl"],
    zeitblock: ZeitblockFromJSON(json["zeitblock"]),
    tagesTyp: TagesTypFromJSON(json["tagesTyp"]),
    intervall: ZaehldatenIntervallFromJSON(json["intervall"]),
    messquerschnittIds: new Set(json["messquerschnittIds"]),
    rounding: RoundingFromJSON(json["rounding"]),
    stundensumme: json["stundensumme"],
    blocksumme: json["blocksumme"],
    tagessumme: json["tagessumme"],
    spitzenstunde: json["spitzenstunde"],
  };
}

export function MessstelleOptionsDTOToJSON(json: any): MessstelleOptionsDTO {
  return MessstelleOptionsDTOToJSONTyped(json, false);
}

export function MessstelleOptionsDTOToJSONTyped(
  value?: MessstelleOptionsDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    zeitraum: value["zeitraum"],
    fahrzeuge: FahrzeugOptionsDTOToJSON(value["fahrzeuge"]),
    zeitauswahl: value["zeitauswahl"],
    zeitblock: ZeitblockToJSON(value["zeitblock"]),
    tagesTyp: TagesTypToJSON(value["tagesTyp"]),
    intervall: ZaehldatenIntervallToJSON(value["intervall"]),
    messquerschnittIds: Array.from(value["messquerschnittIds"] as Set<any>),
    rounding: RoundingToJSON(value["rounding"]),
    stundensumme: value["stundensumme"],
    blocksumme: value["blocksumme"],
    tagessumme: value["tagessumme"],
    spitzenstunde: value["spitzenstunde"],
  };
}
