/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GeoPoint } from "./GeoPoint";
import type { Messfaehigkeit } from "./Messfaehigkeit";
import type { Messquerschnitt } from "./Messquerschnitt";

import { mapValues } from "../runtime";
import {
  GeoPointFromJSON,
  GeoPointFromJSONTyped,
  GeoPointToJSON,
  GeoPointToJSONTyped,
} from "./GeoPoint";
import {
  MessfaehigkeitFromJSON,
  MessfaehigkeitFromJSONTyped,
  MessfaehigkeitToJSON,
  MessfaehigkeitToJSONTyped,
} from "./Messfaehigkeit";
import {
  MessquerschnittFromJSON,
  MessquerschnittFromJSONTyped,
  MessquerschnittToJSON,
  MessquerschnittToJSONTyped,
} from "./Messquerschnitt";

/**
 *
 * @export
 * @interface MessstelleRequestBody
 */
export interface MessstelleRequestBody {
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  mstId?: string;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  status?: MessstelleRequestBodyStatusEnum;
  /**
   *
   * @type {Date}
   * @memberof MessstelleRequestBody
   */
  realisierungsdatum?: Date;
  /**
   *
   * @type {Date}
   * @memberof MessstelleRequestBody
   */
  abbaudatum?: Date;
  /**
   *
   * @type {number}
   * @memberof MessstelleRequestBody
   */
  stadtbezirkNummer?: number;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  bemerkung?: string;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  fahrzeugklasse?: MessstelleRequestBodyFahrzeugklasseEnum;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  detektierteVerkehrsart?: MessstelleRequestBodyDetektierteVerkehrsartEnum;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  hersteller?: string;
  /**
   *
   * @type {Date}
   * @memberof MessstelleRequestBody
   */
  datumLetztePlausibleMessung?: Date;
  /**
   *
   * @type {GeoPoint}
   * @memberof MessstelleRequestBody
   */
  punkt?: GeoPoint;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleRequestBody
   */
  sichtbarDatenportal?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleRequestBody
   */
  geprueft?: boolean;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  kommentar?: string;
  /**
   *
   * @type {string}
   * @memberof MessstelleRequestBody
   */
  standort?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof MessstelleRequestBody
   */
  suchwoerter?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof MessstelleRequestBody
   */
  customSuchwoerter?: Array<string>;
  /**
   *
   * @type {Array<Messquerschnitt>}
   * @memberof MessstelleRequestBody
   */
  messquerschnitte?: Array<Messquerschnitt>;
  /**
   *
   * @type {Array<Messfaehigkeit>}
   * @memberof MessstelleRequestBody
   */
  messfaehigkeiten?: Array<Messfaehigkeit>;
  /**
   *
   * @type {boolean}
   * @memberof MessstelleRequestBody
   */
  lageplanVorhanden?: boolean;
}

/**
 * @export
 */
export const MessstelleRequestBodyStatusEnum = {
  InPlanung: "IN_PLANUNG",
  InBestand: "IN_BESTAND",
  AusserBetrieb: "AUSSER_BETRIEB",
  Abgebaut: "ABGEBAUT",
  Unbekannt: "UNBEKANNT",
} as const;
export type MessstelleRequestBodyStatusEnum =
  (typeof MessstelleRequestBodyStatusEnum)[keyof typeof MessstelleRequestBodyStatusEnum];

/**
 * @export
 */
export const MessstelleRequestBodyFahrzeugklasseEnum = {
  Rad: "RAD",
  SummeKfz: "SUMME_KFZ",
  ZweiPlusEins: "ZWEI_PLUS_EINS",
  AchtPlusEins: "ACHT_PLUS_EINS",
} as const;
export type MessstelleRequestBodyFahrzeugklasseEnum =
  (typeof MessstelleRequestBodyFahrzeugklasseEnum)[keyof typeof MessstelleRequestBodyFahrzeugklasseEnum];

/**
 * @export
 */
export const MessstelleRequestBodyDetektierteVerkehrsartEnum = {
  Kfz: "KFZ",
  Rad: "RAD",
  Unbekannt: "UNBEKANNT",
} as const;
export type MessstelleRequestBodyDetektierteVerkehrsartEnum =
  (typeof MessstelleRequestBodyDetektierteVerkehrsartEnum)[keyof typeof MessstelleRequestBodyDetektierteVerkehrsartEnum];

/**
 * Check if a given object implements the MessstelleRequestBody interface.
 */
export function instanceOfMessstelleRequestBody(
  value: object
): value is MessstelleRequestBody {
  return true;
}

export function MessstelleRequestBodyFromJSON(
  json: any
): MessstelleRequestBody {
  return MessstelleRequestBodyFromJSONTyped(json, false);
}

export function MessstelleRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MessstelleRequestBody {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    mstId: json["mstId"] == null ? undefined : json["mstId"],
    name: json["name"] == null ? undefined : json["name"],
    status: json["status"] == null ? undefined : json["status"],
    realisierungsdatum:
      json["realisierungsdatum"] == null
        ? undefined
        : new Date(json["realisierungsdatum"]),
    abbaudatum:
      json["abbaudatum"] == null ? undefined : new Date(json["abbaudatum"]),
    stadtbezirkNummer:
      json["stadtbezirkNummer"] == null ? undefined : json["stadtbezirkNummer"],
    bemerkung: json["bemerkung"] == null ? undefined : json["bemerkung"],
    fahrzeugklasse:
      json["fahrzeugklasse"] == null ? undefined : json["fahrzeugklasse"],
    detektierteVerkehrsart:
      json["detektierteVerkehrsart"] == null
        ? undefined
        : json["detektierteVerkehrsart"],
    hersteller: json["hersteller"] == null ? undefined : json["hersteller"],
    datumLetztePlausibleMessung:
      json["datumLetztePlausibleMessung"] == null
        ? undefined
        : new Date(json["datumLetztePlausibleMessung"]),
    punkt: json["punkt"] == null ? undefined : GeoPointFromJSON(json["punkt"]),
    sichtbarDatenportal:
      json["sichtbarDatenportal"] == null
        ? undefined
        : json["sichtbarDatenportal"],
    geprueft: json["geprueft"] == null ? undefined : json["geprueft"],
    kommentar: json["kommentar"] == null ? undefined : json["kommentar"],
    standort: json["standort"] == null ? undefined : json["standort"],
    suchwoerter: json["suchwoerter"] == null ? undefined : json["suchwoerter"],
    customSuchwoerter:
      json["customSuchwoerter"] == null ? undefined : json["customSuchwoerter"],
    messquerschnitte:
      json["messquerschnitte"] == null
        ? undefined
        : (json["messquerschnitte"] as Array<any>).map(MessquerschnittFromJSON),
    messfaehigkeiten:
      json["messfaehigkeiten"] == null
        ? undefined
        : (json["messfaehigkeiten"] as Array<any>).map(MessfaehigkeitFromJSON),
    lageplanVorhanden:
      json["lageplanVorhanden"] == null ? undefined : json["lageplanVorhanden"],
  };
}

export function MessstelleRequestBodyToJSON(json: any): MessstelleRequestBody {
  return MessstelleRequestBodyToJSONTyped(json, false);
}

export function MessstelleRequestBodyToJSONTyped(
  value?: MessstelleRequestBody | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    mstId: value["mstId"],
    name: value["name"],
    status: value["status"],
    realisierungsdatum:
      value["realisierungsdatum"] == null
        ? undefined
        : value["realisierungsdatum"].toISOString().substring(0, 10),
    abbaudatum:
      value["abbaudatum"] == null
        ? undefined
        : value["abbaudatum"].toISOString().substring(0, 10),
    stadtbezirkNummer: value["stadtbezirkNummer"],
    bemerkung: value["bemerkung"],
    fahrzeugklasse: value["fahrzeugklasse"],
    detektierteVerkehrsart: value["detektierteVerkehrsart"],
    hersteller: value["hersteller"],
    datumLetztePlausibleMessung:
      value["datumLetztePlausibleMessung"] == null
        ? undefined
        : value["datumLetztePlausibleMessung"].toISOString().substring(0, 10),
    punkt: GeoPointToJSON(value["punkt"]),
    sichtbarDatenportal: value["sichtbarDatenportal"],
    geprueft: value["geprueft"],
    kommentar: value["kommentar"],
    standort: value["standort"],
    suchwoerter: value["suchwoerter"],
    customSuchwoerter: value["customSuchwoerter"],
    messquerschnitte:
      value["messquerschnitte"] == null
        ? undefined
        : (value["messquerschnitte"] as Array<any>).map(MessquerschnittToJSON),
    messfaehigkeiten:
      value["messfaehigkeiten"] == null
        ? undefined
        : (value["messfaehigkeiten"] as Array<any>).map(MessfaehigkeitToJSON),
    lageplanVorhanden: value["lageplanVorhanden"],
  };
}
