/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NextZaehlstellennummerDTO
 */
export interface NextZaehlstellennummerDTO {
    /**
     * 
     * @type {string}
     * @memberof NextZaehlstellennummerDTO
     */
    nummer?: string;
}

/**
 * Check if a given object implements the NextZaehlstellennummerDTO interface.
 */
export function instanceOfNextZaehlstellennummerDTO(value: object): value is NextZaehlstellennummerDTO {
    return true;
}

export function NextZaehlstellennummerDTOFromJSON(json: any): NextZaehlstellennummerDTO {
    return NextZaehlstellennummerDTOFromJSONTyped(json, false);
}

export function NextZaehlstellennummerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextZaehlstellennummerDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'nummer': json['nummer'] == null ? undefined : json['nummer'],
    };
}

export function NextZaehlstellennummerDTOToJSON(json: any): NextZaehlstellennummerDTO {
    return NextZaehlstellennummerDTOToJSONTyped(json, false);
}

export function NextZaehlstellennummerDTOToJSONTyped(value?: NextZaehlstellennummerDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nummer': value['nummer'],
    };
}

