/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OptionsQuerungsverkehrDTO } from './OptionsQuerungsverkehrDTO';
import {
    OptionsQuerungsverkehrDTOFromJSON,
    OptionsQuerungsverkehrDTOFromJSONTyped,
    OptionsQuerungsverkehrDTOToJSON,
    OptionsQuerungsverkehrDTOToJSONTyped,
} from './OptionsQuerungsverkehrDTO';
import type { OptionsLaengsverkehrDTO } from './OptionsLaengsverkehrDTO';
import {
    OptionsLaengsverkehrDTOFromJSON,
    OptionsLaengsverkehrDTOFromJSONTyped,
    OptionsLaengsverkehrDTOToJSON,
    OptionsLaengsverkehrDTOToJSONTyped,
} from './OptionsLaengsverkehrDTO';
import type { OptionsVerkehrsbeziehungDTO } from './OptionsVerkehrsbeziehungDTO';
import {
    OptionsVerkehrsbeziehungDTOFromJSON,
    OptionsVerkehrsbeziehungDTOFromJSONTyped,
    OptionsVerkehrsbeziehungDTOToJSON,
    OptionsVerkehrsbeziehungDTOToJSONTyped,
} from './OptionsVerkehrsbeziehungDTO';

/**
 * 
 * @export
 * @interface OptionsDTO
 */
export interface OptionsDTO {
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    zaehldauer: OptionsDTOZaehldauerEnum;
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    intervall: OptionsDTOIntervallEnum;
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    zeitblock: OptionsDTOZeitblockEnum;
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    zeitauswahl: string;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    kraftfahrzeugverkehr: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    schwerverkehr: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    gueterverkehr: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    radverkehr: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    fussverkehr: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    schwerverkehrsanteilProzent: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    gueterverkehrsanteilProzent: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    pkwEinheiten: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    personenkraftwagen: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    lastkraftwagen: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    lastzuege: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    busse: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    kraftraeder: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    stundensumme: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    blocksumme: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    tagessumme: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    spitzenstunde: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    spitzenstundeKfz: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    spitzenstundeRad: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    spitzenstundeFuss: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    mittelwert: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    fahrzeugklassenStapeln: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    beschriftung: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    datentabelle: boolean;
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    rounding: OptionsDTORoundingEnum;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    differenzdatenDarstellen: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    zeitreiheGesamt: boolean;
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    vergleichszaehlungsId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OptionsDTO
     */
    beideRichtungen?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OptionsDTO
     */
    vonKnotenarm?: number;
    /**
     * 
     * @type {number}
     * @memberof OptionsDTO
     */
    nachKnotenarm?: number;
    /**
     * 
     * @type {Array<OptionsVerkehrsbeziehungDTO>}
     * @memberof OptionsDTO
     */
    chosenVerkehrsbeziehungen?: Array<OptionsVerkehrsbeziehungDTO>;
    /**
     * 
     * @type {Array<OptionsLaengsverkehrDTO>}
     * @memberof OptionsDTO
     */
    chosenLaengsverkehre?: Array<OptionsLaengsverkehrDTO>;
    /**
     * 
     * @type {Array<OptionsQuerungsverkehrDTO>}
     * @memberof OptionsDTO
     */
    chosenQuerungsverkehre?: Array<OptionsQuerungsverkehrDTO>;
    /**
     * 
     * @type {string}
     * @memberof OptionsDTO
     */
    idVergleichszaehlungZeitreihe?: string;
}


/**
 * @export
 */
export const OptionsDTOZaehldauerEnum = {
    Dauer2X4Stunden: 'DAUER_2_X_4_STUNDEN',
    Dauer24Stunden: 'DAUER_24_STUNDEN',
    Dauer16Stunden: 'DAUER_16_STUNDEN',
    Dauer13Stunden: 'DAUER_13_STUNDEN',
    Sonstige: 'SONSTIGE'
} as const;
export type OptionsDTOZaehldauerEnum = typeof OptionsDTOZaehldauerEnum[keyof typeof OptionsDTOZaehldauerEnum];

/**
 * @export
 */
export const OptionsDTOIntervallEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsDTOIntervallEnum = typeof OptionsDTOIntervallEnum[keyof typeof OptionsDTOIntervallEnum];

/**
 * @export
 */
export const OptionsDTOZeitblockEnum = {
    Zb0006: 'ZB_00_06',
    Zb0610: 'ZB_06_10',
    Zb1015: 'ZB_10_15',
    Zb1519: 'ZB_15_19',
    Zb1922: 'ZB_19_22',
    Zb1924: 'ZB_19_24',
    Zb0024: 'ZB_00_24',
    Zb0619: 'ZB_06_19',
    Zb0622: 'ZB_06_22',
    Zb0001: 'ZB_00_01',
    Zb0102: 'ZB_01_02',
    Zb0203: 'ZB_02_03',
    Zb0304: 'ZB_03_04',
    Zb0405: 'ZB_04_05',
    Zb0506: 'ZB_05_06',
    Zb0607: 'ZB_06_07',
    Zb0708: 'ZB_07_08',
    Zb0809: 'ZB_08_09',
    Zb0910: 'ZB_09_10',
    Zb1011: 'ZB_10_11',
    Zb1112: 'ZB_11_12',
    Zb1213: 'ZB_12_13',
    Zb1314: 'ZB_13_14',
    Zb1415: 'ZB_14_15',
    Zb1516: 'ZB_15_16',
    Zb1617: 'ZB_16_17',
    Zb1718: 'ZB_17_18',
    Zb1819: 'ZB_18_19',
    Zb1920: 'ZB_19_20',
    Zb2021: 'ZB_20_21',
    Zb2122: 'ZB_21_22',
    Zb2223: 'ZB_22_23',
    Zb2324: 'ZB_23_24',
    Zb00000030: 'ZB_0000_0030',
    Zb00300100: 'ZB_0030_0100',
    Zb01000130: 'ZB_0100_0130',
    Zb01300200: 'ZB_0130_0200',
    Zb02000230: 'ZB_0200_0230',
    Zb02300300: 'ZB_0230_0300',
    Zb03000330: 'ZB_0300_0330',
    Zb03300400: 'ZB_0330_0400',
    Zb04000430: 'ZB_0400_0430',
    Zb04300500: 'ZB_0430_0500',
    Zb05000530: 'ZB_0500_0530',
    Zb05300600: 'ZB_0530_0600',
    Zb06000630: 'ZB_0600_0630',
    Zb06300700: 'ZB_0630_0700',
    Zb07000730: 'ZB_0700_0730',
    Zb07300800: 'ZB_0730_0800',
    Zb08000830: 'ZB_0800_0830',
    Zb08300900: 'ZB_0830_0900',
    Zb09000930: 'ZB_0900_0930',
    Zb09301000: 'ZB_0930_1000',
    Zb10001030: 'ZB_1000_1030',
    Zb10301100: 'ZB_1030_1100',
    Zb11001130: 'ZB_1100_1130',
    Zb11301200: 'ZB_1130_1200',
    Zb12001230: 'ZB_1200_1230',
    Zb12301300: 'ZB_1230_1300',
    Zb13001330: 'ZB_1300_1330',
    Zb13301400: 'ZB_1330_1400',
    Zb14001430: 'ZB_1400_1430',
    Zb14301500: 'ZB_1430_1500',
    Zb15001530: 'ZB_1500_1530',
    Zb15301600: 'ZB_1530_1600',
    Zb16001630: 'ZB_1600_1630',
    Zb16301700: 'ZB_1630_1700',
    Zb17001730: 'ZB_1700_1730',
    Zb17301800: 'ZB_1730_1800',
    Zb18001830: 'ZB_1800_1830',
    Zb18301900: 'ZB_1830_1900',
    Zb19001930: 'ZB_1900_1930',
    Zb19302000: 'ZB_1930_2000',
    Zb20002030: 'ZB_2000_2030',
    Zb20302100: 'ZB_2030_2100',
    Zb21002130: 'ZB_2100_2130',
    Zb21302200: 'ZB_2130_2200',
    Zb22002230: 'ZB_2200_2230',
    Zb22302300: 'ZB_2230_2300',
    Zb23002330: 'ZB_2300_2330',
    Zb23302400: 'ZB_2330_2400'
} as const;
export type OptionsDTOZeitblockEnum = typeof OptionsDTOZeitblockEnum[keyof typeof OptionsDTOZeitblockEnum];

/**
 * @export
 */
export const OptionsDTORoundingEnum = {
    None: 'NONE',
    R10: 'R10',
    R100: 'R100'
} as const;
export type OptionsDTORoundingEnum = typeof OptionsDTORoundingEnum[keyof typeof OptionsDTORoundingEnum];


/**
 * Check if a given object implements the OptionsDTO interface.
 */
export function instanceOfOptionsDTO(value: object): value is OptionsDTO {
    if (!('zaehldauer' in value) || value['zaehldauer'] === undefined) return false;
    if (!('intervall' in value) || value['intervall'] === undefined) return false;
    if (!('zeitblock' in value) || value['zeitblock'] === undefined) return false;
    if (!('zeitauswahl' in value) || value['zeitauswahl'] === undefined) return false;
    if (!('kraftfahrzeugverkehr' in value) || value['kraftfahrzeugverkehr'] === undefined) return false;
    if (!('schwerverkehr' in value) || value['schwerverkehr'] === undefined) return false;
    if (!('gueterverkehr' in value) || value['gueterverkehr'] === undefined) return false;
    if (!('radverkehr' in value) || value['radverkehr'] === undefined) return false;
    if (!('fussverkehr' in value) || value['fussverkehr'] === undefined) return false;
    if (!('schwerverkehrsanteilProzent' in value) || value['schwerverkehrsanteilProzent'] === undefined) return false;
    if (!('gueterverkehrsanteilProzent' in value) || value['gueterverkehrsanteilProzent'] === undefined) return false;
    if (!('pkwEinheiten' in value) || value['pkwEinheiten'] === undefined) return false;
    if (!('personenkraftwagen' in value) || value['personenkraftwagen'] === undefined) return false;
    if (!('lastkraftwagen' in value) || value['lastkraftwagen'] === undefined) return false;
    if (!('lastzuege' in value) || value['lastzuege'] === undefined) return false;
    if (!('busse' in value) || value['busse'] === undefined) return false;
    if (!('kraftraeder' in value) || value['kraftraeder'] === undefined) return false;
    if (!('stundensumme' in value) || value['stundensumme'] === undefined) return false;
    if (!('blocksumme' in value) || value['blocksumme'] === undefined) return false;
    if (!('tagessumme' in value) || value['tagessumme'] === undefined) return false;
    if (!('spitzenstunde' in value) || value['spitzenstunde'] === undefined) return false;
    if (!('spitzenstundeKfz' in value) || value['spitzenstundeKfz'] === undefined) return false;
    if (!('spitzenstundeRad' in value) || value['spitzenstundeRad'] === undefined) return false;
    if (!('spitzenstundeFuss' in value) || value['spitzenstundeFuss'] === undefined) return false;
    if (!('mittelwert' in value) || value['mittelwert'] === undefined) return false;
    if (!('fahrzeugklassenStapeln' in value) || value['fahrzeugklassenStapeln'] === undefined) return false;
    if (!('beschriftung' in value) || value['beschriftung'] === undefined) return false;
    if (!('datentabelle' in value) || value['datentabelle'] === undefined) return false;
    if (!('rounding' in value) || value['rounding'] === undefined) return false;
    if (!('differenzdatenDarstellen' in value) || value['differenzdatenDarstellen'] === undefined) return false;
    if (!('zeitreiheGesamt' in value) || value['zeitreiheGesamt'] === undefined) return false;
    return true;
}

export function OptionsDTOFromJSON(json: any): OptionsDTO {
    return OptionsDTOFromJSONTyped(json, false);
}

export function OptionsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionsDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'zaehldauer': json['zaehldauer'],
        'intervall': json['intervall'],
        'zeitblock': json['zeitblock'],
        'zeitauswahl': json['zeitauswahl'],
        'kraftfahrzeugverkehr': json['kraftfahrzeugverkehr'],
        'schwerverkehr': json['schwerverkehr'],
        'gueterverkehr': json['gueterverkehr'],
        'radverkehr': json['radverkehr'],
        'fussverkehr': json['fussverkehr'],
        'schwerverkehrsanteilProzent': json['schwerverkehrsanteilProzent'],
        'gueterverkehrsanteilProzent': json['gueterverkehrsanteilProzent'],
        'pkwEinheiten': json['pkwEinheiten'],
        'personenkraftwagen': json['personenkraftwagen'],
        'lastkraftwagen': json['lastkraftwagen'],
        'lastzuege': json['lastzuege'],
        'busse': json['busse'],
        'kraftraeder': json['kraftraeder'],
        'stundensumme': json['stundensumme'],
        'blocksumme': json['blocksumme'],
        'tagessumme': json['tagessumme'],
        'spitzenstunde': json['spitzenstunde'],
        'spitzenstundeKfz': json['spitzenstundeKfz'],
        'spitzenstundeRad': json['spitzenstundeRad'],
        'spitzenstundeFuss': json['spitzenstundeFuss'],
        'mittelwert': json['mittelwert'],
        'fahrzeugklassenStapeln': json['fahrzeugklassenStapeln'],
        'beschriftung': json['beschriftung'],
        'datentabelle': json['datentabelle'],
        'rounding': json['rounding'],
        'differenzdatenDarstellen': json['differenzdatenDarstellen'],
        'zeitreiheGesamt': json['zeitreiheGesamt'],
        'vergleichszaehlungsId': json['vergleichszaehlungsId'] == null ? undefined : json['vergleichszaehlungsId'],
        'beideRichtungen': json['beideRichtungen'] == null ? undefined : json['beideRichtungen'],
        'vonKnotenarm': json['vonKnotenarm'] == null ? undefined : json['vonKnotenarm'],
        'nachKnotenarm': json['nachKnotenarm'] == null ? undefined : json['nachKnotenarm'],
        'chosenVerkehrsbeziehungen': json['chosenVerkehrsbeziehungen'] == null ? undefined : ((json['chosenVerkehrsbeziehungen'] as Array<any>).map(OptionsVerkehrsbeziehungDTOFromJSON)),
        'chosenLaengsverkehre': json['chosenLaengsverkehre'] == null ? undefined : ((json['chosenLaengsverkehre'] as Array<any>).map(OptionsLaengsverkehrDTOFromJSON)),
        'chosenQuerungsverkehre': json['chosenQuerungsverkehre'] == null ? undefined : ((json['chosenQuerungsverkehre'] as Array<any>).map(OptionsQuerungsverkehrDTOFromJSON)),
        'idVergleichszaehlungZeitreihe': json['idVergleichszaehlungZeitreihe'] == null ? undefined : json['idVergleichszaehlungZeitreihe'],
    };
}

export function OptionsDTOToJSON(json: any): OptionsDTO {
    return OptionsDTOToJSONTyped(json, false);
}

export function OptionsDTOToJSONTyped(value?: OptionsDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'zaehldauer': value['zaehldauer'],
        'intervall': value['intervall'],
        'zeitblock': value['zeitblock'],
        'zeitauswahl': value['zeitauswahl'],
        'kraftfahrzeugverkehr': value['kraftfahrzeugverkehr'],
        'schwerverkehr': value['schwerverkehr'],
        'gueterverkehr': value['gueterverkehr'],
        'radverkehr': value['radverkehr'],
        'fussverkehr': value['fussverkehr'],
        'schwerverkehrsanteilProzent': value['schwerverkehrsanteilProzent'],
        'gueterverkehrsanteilProzent': value['gueterverkehrsanteilProzent'],
        'pkwEinheiten': value['pkwEinheiten'],
        'personenkraftwagen': value['personenkraftwagen'],
        'lastkraftwagen': value['lastkraftwagen'],
        'lastzuege': value['lastzuege'],
        'busse': value['busse'],
        'kraftraeder': value['kraftraeder'],
        'stundensumme': value['stundensumme'],
        'blocksumme': value['blocksumme'],
        'tagessumme': value['tagessumme'],
        'spitzenstunde': value['spitzenstunde'],
        'spitzenstundeKfz': value['spitzenstundeKfz'],
        'spitzenstundeRad': value['spitzenstundeRad'],
        'spitzenstundeFuss': value['spitzenstundeFuss'],
        'mittelwert': value['mittelwert'],
        'fahrzeugklassenStapeln': value['fahrzeugklassenStapeln'],
        'beschriftung': value['beschriftung'],
        'datentabelle': value['datentabelle'],
        'rounding': value['rounding'],
        'differenzdatenDarstellen': value['differenzdatenDarstellen'],
        'zeitreiheGesamt': value['zeitreiheGesamt'],
        'vergleichszaehlungsId': value['vergleichszaehlungsId'],
        'beideRichtungen': value['beideRichtungen'],
        'vonKnotenarm': value['vonKnotenarm'],
        'nachKnotenarm': value['nachKnotenarm'],
        'chosenVerkehrsbeziehungen': value['chosenVerkehrsbeziehungen'] == null ? undefined : ((value['chosenVerkehrsbeziehungen'] as Array<any>).map(OptionsVerkehrsbeziehungDTOToJSON)),
        'chosenLaengsverkehre': value['chosenLaengsverkehre'] == null ? undefined : ((value['chosenLaengsverkehre'] as Array<any>).map(OptionsLaengsverkehrDTOToJSON)),
        'chosenQuerungsverkehre': value['chosenQuerungsverkehre'] == null ? undefined : ((value['chosenQuerungsverkehre'] as Array<any>).map(OptionsQuerungsverkehrDTOToJSON)),
        'idVergleichszaehlungZeitreihe': value['idVergleichszaehlungZeitreihe'],
    };
}

