/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptionsmenueSettingsDTO
 */
export interface OptionsmenueSettingsDTO {
    /**
     * 
     * @type {string}
     * @memberof OptionsmenueSettingsDTO
     */
    fahrzeugklasse?: OptionsmenueSettingsDTOFahrzeugklasseEnum;
    /**
     * 
     * @type {string}
     * @memberof OptionsmenueSettingsDTO
     */
    intervall?: OptionsmenueSettingsDTOIntervallEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    kraftfahrzeugverkehrChoosableIntervals?: Array<OptionsmenueSettingsDTOKraftfahrzeugverkehrChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    schwerverkehrChoosableIntervals?: Array<OptionsmenueSettingsDTOSchwerverkehrChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    gueterverkehrChoosableIntervals?: Array<OptionsmenueSettingsDTOGueterverkehrChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    schwerverkehrsanteilProzentChoosableIntervals?: Array<OptionsmenueSettingsDTOSchwerverkehrsanteilProzentChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    gueterverkehrsanteilProzentChoosableIntervals?: Array<OptionsmenueSettingsDTOGueterverkehrsanteilProzentChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    radverkehrChoosableIntervals?: Array<OptionsmenueSettingsDTORadverkehrChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    fussverkehrChoosableIntervals?: Array<OptionsmenueSettingsDTOFussverkehrChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    lastkraftwagenChoosableIntervals?: Array<OptionsmenueSettingsDTOLastkraftwagenChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    lastzuegeChoosableIntervals?: Array<OptionsmenueSettingsDTOLastzuegeChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    busseChoosableIntervals?: Array<OptionsmenueSettingsDTOBusseChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    kraftraederChoosableIntervals?: Array<OptionsmenueSettingsDTOKraftraederChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    personenkraftwagenChoosableIntervals?: Array<OptionsmenueSettingsDTOPersonenkraftwagenChoosableIntervalsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptionsmenueSettingsDTO
     */
    lieferwagenChoosableIntervals?: Array<OptionsmenueSettingsDTOLieferwagenChoosableIntervalsEnum>;
}


/**
 * @export
 */
export const OptionsmenueSettingsDTOFahrzeugklasseEnum = {
    Rad: 'RAD',
    SummeKfz: 'SUMME_KFZ',
    ZweiPlusEins: 'ZWEI_PLUS_EINS',
    AchtPlusEins: 'ACHT_PLUS_EINS'
} as const;
export type OptionsmenueSettingsDTOFahrzeugklasseEnum = typeof OptionsmenueSettingsDTOFahrzeugklasseEnum[keyof typeof OptionsmenueSettingsDTOFahrzeugklasseEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOIntervallEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOIntervallEnum = typeof OptionsmenueSettingsDTOIntervallEnum[keyof typeof OptionsmenueSettingsDTOIntervallEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOKraftfahrzeugverkehrChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOKraftfahrzeugverkehrChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOKraftfahrzeugverkehrChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOKraftfahrzeugverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOSchwerverkehrChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOSchwerverkehrChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOSchwerverkehrChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOSchwerverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOGueterverkehrChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOGueterverkehrChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOGueterverkehrChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOGueterverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOSchwerverkehrsanteilProzentChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOSchwerverkehrsanteilProzentChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOSchwerverkehrsanteilProzentChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOSchwerverkehrsanteilProzentChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOGueterverkehrsanteilProzentChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOGueterverkehrsanteilProzentChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOGueterverkehrsanteilProzentChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOGueterverkehrsanteilProzentChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTORadverkehrChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTORadverkehrChoosableIntervalsEnum = typeof OptionsmenueSettingsDTORadverkehrChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTORadverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOFussverkehrChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOFussverkehrChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOFussverkehrChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOFussverkehrChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOLastkraftwagenChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOLastkraftwagenChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOLastkraftwagenChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOLastkraftwagenChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOLastzuegeChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOLastzuegeChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOLastzuegeChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOLastzuegeChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOBusseChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOBusseChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOBusseChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOBusseChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOKraftraederChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOKraftraederChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOKraftraederChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOKraftraederChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOPersonenkraftwagenChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOPersonenkraftwagenChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOPersonenkraftwagenChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOPersonenkraftwagenChoosableIntervalsEnum];

/**
 * @export
 */
export const OptionsmenueSettingsDTOLieferwagenChoosableIntervalsEnum = {
    StundeViertel: 'STUNDE_VIERTEL',
    StundeViertelEingeschraenkt: 'STUNDE_VIERTEL_EINGESCHRAENKT',
    StundeHalb: 'STUNDE_HALB',
    StundeKomplett: 'STUNDE_KOMPLETT'
} as const;
export type OptionsmenueSettingsDTOLieferwagenChoosableIntervalsEnum = typeof OptionsmenueSettingsDTOLieferwagenChoosableIntervalsEnum[keyof typeof OptionsmenueSettingsDTOLieferwagenChoosableIntervalsEnum];


/**
 * Check if a given object implements the OptionsmenueSettingsDTO interface.
 */
export function instanceOfOptionsmenueSettingsDTO(value: object): value is OptionsmenueSettingsDTO {
    return true;
}

export function OptionsmenueSettingsDTOFromJSON(json: any): OptionsmenueSettingsDTO {
    return OptionsmenueSettingsDTOFromJSONTyped(json, false);
}

export function OptionsmenueSettingsDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionsmenueSettingsDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'fahrzeugklasse': json['fahrzeugklasse'] == null ? undefined : json['fahrzeugklasse'],
        'intervall': json['intervall'] == null ? undefined : json['intervall'],
        'kraftfahrzeugverkehrChoosableIntervals': json['kraftfahrzeugverkehrChoosableIntervals'] == null ? undefined : json['kraftfahrzeugverkehrChoosableIntervals'],
        'schwerverkehrChoosableIntervals': json['schwerverkehrChoosableIntervals'] == null ? undefined : json['schwerverkehrChoosableIntervals'],
        'gueterverkehrChoosableIntervals': json['gueterverkehrChoosableIntervals'] == null ? undefined : json['gueterverkehrChoosableIntervals'],
        'schwerverkehrsanteilProzentChoosableIntervals': json['schwerverkehrsanteilProzentChoosableIntervals'] == null ? undefined : json['schwerverkehrsanteilProzentChoosableIntervals'],
        'gueterverkehrsanteilProzentChoosableIntervals': json['gueterverkehrsanteilProzentChoosableIntervals'] == null ? undefined : json['gueterverkehrsanteilProzentChoosableIntervals'],
        'radverkehrChoosableIntervals': json['radverkehrChoosableIntervals'] == null ? undefined : json['radverkehrChoosableIntervals'],
        'fussverkehrChoosableIntervals': json['fussverkehrChoosableIntervals'] == null ? undefined : json['fussverkehrChoosableIntervals'],
        'lastkraftwagenChoosableIntervals': json['lastkraftwagenChoosableIntervals'] == null ? undefined : json['lastkraftwagenChoosableIntervals'],
        'lastzuegeChoosableIntervals': json['lastzuegeChoosableIntervals'] == null ? undefined : json['lastzuegeChoosableIntervals'],
        'busseChoosableIntervals': json['busseChoosableIntervals'] == null ? undefined : json['busseChoosableIntervals'],
        'kraftraederChoosableIntervals': json['kraftraederChoosableIntervals'] == null ? undefined : json['kraftraederChoosableIntervals'],
        'personenkraftwagenChoosableIntervals': json['personenkraftwagenChoosableIntervals'] == null ? undefined : json['personenkraftwagenChoosableIntervals'],
        'lieferwagenChoosableIntervals': json['lieferwagenChoosableIntervals'] == null ? undefined : json['lieferwagenChoosableIntervals'],
    };
}

export function OptionsmenueSettingsDTOToJSON(json: any): OptionsmenueSettingsDTO {
    return OptionsmenueSettingsDTOToJSONTyped(json, false);
}

export function OptionsmenueSettingsDTOToJSONTyped(value?: OptionsmenueSettingsDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fahrzeugklasse': value['fahrzeugklasse'],
        'intervall': value['intervall'],
        'kraftfahrzeugverkehrChoosableIntervals': value['kraftfahrzeugverkehrChoosableIntervals'],
        'schwerverkehrChoosableIntervals': value['schwerverkehrChoosableIntervals'],
        'gueterverkehrChoosableIntervals': value['gueterverkehrChoosableIntervals'],
        'schwerverkehrsanteilProzentChoosableIntervals': value['schwerverkehrsanteilProzentChoosableIntervals'],
        'gueterverkehrsanteilProzentChoosableIntervals': value['gueterverkehrsanteilProzentChoosableIntervals'],
        'radverkehrChoosableIntervals': value['radverkehrChoosableIntervals'],
        'fussverkehrChoosableIntervals': value['fussverkehrChoosableIntervals'],
        'lastkraftwagenChoosableIntervals': value['lastkraftwagenChoosableIntervals'],
        'lastzuegeChoosableIntervals': value['lastzuegeChoosableIntervals'],
        'busseChoosableIntervals': value['busseChoosableIntervals'],
        'kraftraederChoosableIntervals': value['kraftraederChoosableIntervals'],
        'personenkraftwagenChoosableIntervals': value['personenkraftwagenChoosableIntervals'],
        'lieferwagenChoosableIntervals': value['lieferwagenChoosableIntervals'],
    };
}

