/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Fahrzeugklasse } from "./Fahrzeugklasse";
import type { ZaehldatenIntervall } from "./ZaehldatenIntervall";

import { mapValues } from "../runtime";
import {
  FahrzeugklasseFromJSON,
  FahrzeugklasseFromJSONTyped,
  FahrzeugklasseToJSON,
  FahrzeugklasseToJSONTyped,
} from "./Fahrzeugklasse";
import {
  ZaehldatenIntervallFromJSON,
  ZaehldatenIntervallFromJSONTyped,
  ZaehldatenIntervallToJSON,
  ZaehldatenIntervallToJSONTyped,
} from "./ZaehldatenIntervall";

/**
 *
 * @export
 * @interface OptionsmenueSettingsDTO
 */
export interface OptionsmenueSettingsDTO {
  /**
   *
   * @type {Fahrzeugklasse}
   * @memberof OptionsmenueSettingsDTO
   */
  fahrzeugklasse?: Fahrzeugklasse;
  /**
   *
   * @type {ZaehldatenIntervall}
   * @memberof OptionsmenueSettingsDTO
   */
  intervall?: ZaehldatenIntervall;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  kraftfahrzeugverkehrChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  schwerverkehrChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  gueterverkehrChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  schwerverkehrsanteilProzentChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  gueterverkehrsanteilProzentChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  radverkehrChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  fussverkehrChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  lastkraftwagenChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  lastzuegeChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  busseChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  kraftraederChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  personenkraftwagenChoosableIntervals?: Array<ZaehldatenIntervall>;
  /**
   *
   * @type {Array<ZaehldatenIntervall>}
   * @memberof OptionsmenueSettingsDTO
   */
  lieferwagenChoosableIntervals?: Array<ZaehldatenIntervall>;
}

/**
 * Check if a given object implements the OptionsmenueSettingsDTO interface.
 */
export function instanceOfOptionsmenueSettingsDTO(
  value: object
): value is OptionsmenueSettingsDTO {
  return true;
}

export function OptionsmenueSettingsDTOFromJSON(
  json: any
): OptionsmenueSettingsDTO {
  return OptionsmenueSettingsDTOFromJSONTyped(json, false);
}

export function OptionsmenueSettingsDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OptionsmenueSettingsDTO {
  if (json == null) {
    return json;
  }
  return {
    fahrzeugklasse:
      json["fahrzeugklasse"] == null
        ? undefined
        : FahrzeugklasseFromJSON(json["fahrzeugklasse"]),
    intervall:
      json["intervall"] == null
        ? undefined
        : ZaehldatenIntervallFromJSON(json["intervall"]),
    kraftfahrzeugverkehrChoosableIntervals:
      json["kraftfahrzeugverkehrChoosableIntervals"] == null
        ? undefined
        : (json["kraftfahrzeugverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    schwerverkehrChoosableIntervals:
      json["schwerverkehrChoosableIntervals"] == null
        ? undefined
        : (json["schwerverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    gueterverkehrChoosableIntervals:
      json["gueterverkehrChoosableIntervals"] == null
        ? undefined
        : (json["gueterverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    schwerverkehrsanteilProzentChoosableIntervals:
      json["schwerverkehrsanteilProzentChoosableIntervals"] == null
        ? undefined
        : (
            json["schwerverkehrsanteilProzentChoosableIntervals"] as Array<any>
          ).map(ZaehldatenIntervallFromJSON),
    gueterverkehrsanteilProzentChoosableIntervals:
      json["gueterverkehrsanteilProzentChoosableIntervals"] == null
        ? undefined
        : (
            json["gueterverkehrsanteilProzentChoosableIntervals"] as Array<any>
          ).map(ZaehldatenIntervallFromJSON),
    radverkehrChoosableIntervals:
      json["radverkehrChoosableIntervals"] == null
        ? undefined
        : (json["radverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    fussverkehrChoosableIntervals:
      json["fussverkehrChoosableIntervals"] == null
        ? undefined
        : (json["fussverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    lastkraftwagenChoosableIntervals:
      json["lastkraftwagenChoosableIntervals"] == null
        ? undefined
        : (json["lastkraftwagenChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    lastzuegeChoosableIntervals:
      json["lastzuegeChoosableIntervals"] == null
        ? undefined
        : (json["lastzuegeChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    busseChoosableIntervals:
      json["busseChoosableIntervals"] == null
        ? undefined
        : (json["busseChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    kraftraederChoosableIntervals:
      json["kraftraederChoosableIntervals"] == null
        ? undefined
        : (json["kraftraederChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    personenkraftwagenChoosableIntervals:
      json["personenkraftwagenChoosableIntervals"] == null
        ? undefined
        : (json["personenkraftwagenChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
    lieferwagenChoosableIntervals:
      json["lieferwagenChoosableIntervals"] == null
        ? undefined
        : (json["lieferwagenChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallFromJSON
          ),
  };
}

export function OptionsmenueSettingsDTOToJSON(
  json: any
): OptionsmenueSettingsDTO {
  return OptionsmenueSettingsDTOToJSONTyped(json, false);
}

export function OptionsmenueSettingsDTOToJSONTyped(
  value?: OptionsmenueSettingsDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    fahrzeugklasse: FahrzeugklasseToJSON(value["fahrzeugklasse"]),
    intervall: ZaehldatenIntervallToJSON(value["intervall"]),
    kraftfahrzeugverkehrChoosableIntervals:
      value["kraftfahrzeugverkehrChoosableIntervals"] == null
        ? undefined
        : (value["kraftfahrzeugverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    schwerverkehrChoosableIntervals:
      value["schwerverkehrChoosableIntervals"] == null
        ? undefined
        : (value["schwerverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    gueterverkehrChoosableIntervals:
      value["gueterverkehrChoosableIntervals"] == null
        ? undefined
        : (value["gueterverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    schwerverkehrsanteilProzentChoosableIntervals:
      value["schwerverkehrsanteilProzentChoosableIntervals"] == null
        ? undefined
        : (
            value["schwerverkehrsanteilProzentChoosableIntervals"] as Array<any>
          ).map(ZaehldatenIntervallToJSON),
    gueterverkehrsanteilProzentChoosableIntervals:
      value["gueterverkehrsanteilProzentChoosableIntervals"] == null
        ? undefined
        : (
            value["gueterverkehrsanteilProzentChoosableIntervals"] as Array<any>
          ).map(ZaehldatenIntervallToJSON),
    radverkehrChoosableIntervals:
      value["radverkehrChoosableIntervals"] == null
        ? undefined
        : (value["radverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    fussverkehrChoosableIntervals:
      value["fussverkehrChoosableIntervals"] == null
        ? undefined
        : (value["fussverkehrChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    lastkraftwagenChoosableIntervals:
      value["lastkraftwagenChoosableIntervals"] == null
        ? undefined
        : (value["lastkraftwagenChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    lastzuegeChoosableIntervals:
      value["lastzuegeChoosableIntervals"] == null
        ? undefined
        : (value["lastzuegeChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    busseChoosableIntervals:
      value["busseChoosableIntervals"] == null
        ? undefined
        : (value["busseChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    kraftraederChoosableIntervals:
      value["kraftraederChoosableIntervals"] == null
        ? undefined
        : (value["kraftraederChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    personenkraftwagenChoosableIntervals:
      value["personenkraftwagenChoosableIntervals"] == null
        ? undefined
        : (value["personenkraftwagenChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
    lieferwagenChoosableIntervals:
      value["lieferwagenChoosableIntervals"] == null
        ? undefined
        : (value["lieferwagenChoosableIntervals"] as Array<any>).map(
            ZaehldatenIntervallToJSON
          ),
  };
}
