/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface OptionsLaengsverkehrDTO
 */
export interface OptionsLaengsverkehrDTO {
  /**
   *
   * @type {number}
   * @memberof OptionsLaengsverkehrDTO
   */
  knotenarm?: number;
  /**
   *
   * @type {string}
   * @memberof OptionsLaengsverkehrDTO
   */
  richtung?: OptionsLaengsverkehrDTORichtungEnum;
  /**
   *
   * @type {string}
   * @memberof OptionsLaengsverkehrDTO
   */
  strassenseite?: OptionsLaengsverkehrDTOStrassenseiteEnum;
}

/**
 * @export
 */
export const OptionsLaengsverkehrDTORichtungEnum = {
  Ein: "EIN",
  Aus: "AUS",
} as const;
export type OptionsLaengsverkehrDTORichtungEnum =
  (typeof OptionsLaengsverkehrDTORichtungEnum)[keyof typeof OptionsLaengsverkehrDTORichtungEnum];

/**
 * @export
 */
export const OptionsLaengsverkehrDTOStrassenseiteEnum = {
  N: "N",
  No: "NO",
  O: "O",
  So: "SO",
  S: "S",
  Sw: "SW",
  W: "W",
  Nw: "NW",
} as const;
export type OptionsLaengsverkehrDTOStrassenseiteEnum =
  (typeof OptionsLaengsverkehrDTOStrassenseiteEnum)[keyof typeof OptionsLaengsverkehrDTOStrassenseiteEnum];

/**
 * Check if a given object implements the OptionsLaengsverkehrDTO interface.
 */
export function instanceOfOptionsLaengsverkehrDTO(
  value: object
): value is OptionsLaengsverkehrDTO {
  return true;
}

export function OptionsLaengsverkehrDTOFromJSON(
  json: any
): OptionsLaengsverkehrDTO {
  return OptionsLaengsverkehrDTOFromJSONTyped(json, false);
}

export function OptionsLaengsverkehrDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OptionsLaengsverkehrDTO {
  if (json == null) {
    return json;
  }
  return {
    knotenarm: json["knotenarm"] == null ? undefined : json["knotenarm"],
    richtung: json["richtung"] == null ? undefined : json["richtung"],
    strassenseite:
      json["strassenseite"] == null ? undefined : json["strassenseite"],
  };
}

export function OptionsLaengsverkehrDTOToJSON(
  json: any
): OptionsLaengsverkehrDTO {
  return OptionsLaengsverkehrDTOToJSONTyped(json, false);
}

export function OptionsLaengsverkehrDTOToJSONTyped(
  value?: OptionsLaengsverkehrDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    knotenarm: value["knotenarm"],
    richtung: value["richtung"],
    strassenseite: value["strassenseite"],
  };
}
