/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PagedModelEntityModelCustomSuggestEmbedded } from './PagedModelEntityModelCustomSuggestEmbedded';
import {
    PagedModelEntityModelCustomSuggestEmbeddedFromJSON,
    PagedModelEntityModelCustomSuggestEmbeddedFromJSONTyped,
    PagedModelEntityModelCustomSuggestEmbeddedToJSON,
    PagedModelEntityModelCustomSuggestEmbeddedToJSONTyped,
} from './PagedModelEntityModelCustomSuggestEmbedded';
import type { Null } from './Null';
import {
    NullFromJSON,
    NullFromJSONTyped,
    NullToJSON,
    NullToJSONTyped,
} from './Null';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelCustomSuggest
 */
export interface PagedModelEntityModelCustomSuggest {
    /**
     * 
     * @type {PagedModelEntityModelCustomSuggestEmbedded}
     * @memberof PagedModelEntityModelCustomSuggest
     */
    embedded?: PagedModelEntityModelCustomSuggestEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelCustomSuggest
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {Null}
     * @memberof PagedModelEntityModelCustomSuggest
     */
    page?: Null;
}

/**
 * Check if a given object implements the PagedModelEntityModelCustomSuggest interface.
 */
export function instanceOfPagedModelEntityModelCustomSuggest(value: object): value is PagedModelEntityModelCustomSuggest {
    return true;
}

export function PagedModelEntityModelCustomSuggestFromJSON(json: any): PagedModelEntityModelCustomSuggest {
    return PagedModelEntityModelCustomSuggestFromJSONTyped(json, false);
}

export function PagedModelEntityModelCustomSuggestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelCustomSuggest {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelCustomSuggestEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : NullFromJSON(json['page']),
    };
}

export function PagedModelEntityModelCustomSuggestToJSON(json: any): PagedModelEntityModelCustomSuggest {
    return PagedModelEntityModelCustomSuggestToJSONTyped(json, false);
}

export function PagedModelEntityModelCustomSuggestToJSONTyped(value?: PagedModelEntityModelCustomSuggest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelCustomSuggestEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': NullToJSON(value['page']),
    };
}

