/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EntityModelZaehlstelle } from "./EntityModelZaehlstelle";

import { mapValues } from "../runtime";
import {
  EntityModelZaehlstelleFromJSON,
  EntityModelZaehlstelleFromJSONTyped,
  EntityModelZaehlstelleToJSON,
  EntityModelZaehlstelleToJSONTyped,
} from "./EntityModelZaehlstelle";

/**
 *
 * @export
 * @interface PagedModelEntityModelZaehlstelleEmbedded
 */
export interface PagedModelEntityModelZaehlstelleEmbedded {
  /**
   *
   * @type {Array<EntityModelZaehlstelle>}
   * @memberof PagedModelEntityModelZaehlstelleEmbedded
   */
  zaehlstelles?: Array<EntityModelZaehlstelle>;
}

/**
 * Check if a given object implements the PagedModelEntityModelZaehlstelleEmbedded interface.
 */
export function instanceOfPagedModelEntityModelZaehlstelleEmbedded(
  value: object
): value is PagedModelEntityModelZaehlstelleEmbedded {
  return true;
}

export function PagedModelEntityModelZaehlstelleEmbeddedFromJSON(
  json: any
): PagedModelEntityModelZaehlstelleEmbedded {
  return PagedModelEntityModelZaehlstelleEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelZaehlstelleEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PagedModelEntityModelZaehlstelleEmbedded {
  if (json == null) {
    return json;
  }
  return {
    zaehlstelles:
      json["zaehlstelles"] == null
        ? undefined
        : (json["zaehlstelles"] as Array<any>).map(
            EntityModelZaehlstelleFromJSON
          ),
  };
}

export function PagedModelEntityModelZaehlstelleEmbeddedToJSON(
  json: any
): PagedModelEntityModelZaehlstelleEmbedded {
  return PagedModelEntityModelZaehlstelleEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelZaehlstelleEmbeddedToJSONTyped(
  value?: PagedModelEntityModelZaehlstelleEmbedded | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    zaehlstelles:
      value["zaehlstelles"] == null
        ? undefined
        : (value["zaehlstelles"] as Array<any>).map(
            EntityModelZaehlstelleToJSON
          ),
  };
}
