/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EntityModelPkwEinheit } from "./EntityModelPkwEinheit";

import { mapValues } from "../runtime";
import {
  EntityModelPkwEinheitFromJSON,
  EntityModelPkwEinheitFromJSONTyped,
  EntityModelPkwEinheitToJSON,
  EntityModelPkwEinheitToJSONTyped,
} from "./EntityModelPkwEinheit";

/**
 *
 * @export
 * @interface PagedModelEntityModelPkwEinheitEmbedded
 */
export interface PagedModelEntityModelPkwEinheitEmbedded {
  /**
   *
   * @type {Array<EntityModelPkwEinheit>}
   * @memberof PagedModelEntityModelPkwEinheitEmbedded
   */
  pkwEinheits?: Array<EntityModelPkwEinheit>;
}

/**
 * Check if a given object implements the PagedModelEntityModelPkwEinheitEmbedded interface.
 */
export function instanceOfPagedModelEntityModelPkwEinheitEmbedded(
  value: object
): value is PagedModelEntityModelPkwEinheitEmbedded {
  return true;
}

export function PagedModelEntityModelPkwEinheitEmbeddedFromJSON(
  json: any
): PagedModelEntityModelPkwEinheitEmbedded {
  return PagedModelEntityModelPkwEinheitEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelPkwEinheitEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PagedModelEntityModelPkwEinheitEmbedded {
  if (json == null) {
    return json;
  }
  return {
    pkwEinheits:
      json["pkwEinheits"] == null
        ? undefined
        : (json["pkwEinheits"] as Array<any>).map(
            EntityModelPkwEinheitFromJSON
          ),
  };
}

export function PagedModelEntityModelPkwEinheitEmbeddedToJSON(
  json: any
): PagedModelEntityModelPkwEinheitEmbedded {
  return PagedModelEntityModelPkwEinheitEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelPkwEinheitEmbeddedToJSONTyped(
  value?: PagedModelEntityModelPkwEinheitEmbedded | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    pkwEinheits:
      value["pkwEinheits"] == null
        ? undefined
        : (value["pkwEinheits"] as Array<any>).map(EntityModelPkwEinheitToJSON),
  };
}
