/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EntityModelEmailAddress } from "./EntityModelEmailAddress";

import { mapValues } from "../runtime";
import {
  EntityModelEmailAddressFromJSON,
  EntityModelEmailAddressFromJSONTyped,
  EntityModelEmailAddressToJSON,
  EntityModelEmailAddressToJSONTyped,
} from "./EntityModelEmailAddress";

/**
 *
 * @export
 * @interface PagedModelEntityModelEmailAddressEmbedded
 */
export interface PagedModelEntityModelEmailAddressEmbedded {
  /**
   *
   * @type {Array<EntityModelEmailAddress>}
   * @memberof PagedModelEntityModelEmailAddressEmbedded
   */
  emailAddresses?: Array<EntityModelEmailAddress>;
}

/**
 * Check if a given object implements the PagedModelEntityModelEmailAddressEmbedded interface.
 */
export function instanceOfPagedModelEntityModelEmailAddressEmbedded(
  value: object
): value is PagedModelEntityModelEmailAddressEmbedded {
  return true;
}

export function PagedModelEntityModelEmailAddressEmbeddedFromJSON(
  json: any
): PagedModelEntityModelEmailAddressEmbedded {
  return PagedModelEntityModelEmailAddressEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelEmailAddressEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PagedModelEntityModelEmailAddressEmbedded {
  if (json == null) {
    return json;
  }
  return {
    emailAddresses:
      json["emailAddresses"] == null
        ? undefined
        : (json["emailAddresses"] as Array<any>).map(
            EntityModelEmailAddressFromJSON
          ),
  };
}

export function PagedModelEntityModelEmailAddressEmbeddedToJSON(
  json: any
): PagedModelEntityModelEmailAddressEmbedded {
  return PagedModelEntityModelEmailAddressEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelEmailAddressEmbeddedToJSONTyped(
  value?: PagedModelEntityModelEmailAddressEmbedded | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    emailAddresses:
      value["emailAddresses"] == null
        ? undefined
        : (value["emailAddresses"] as Array<any>).map(
            EntityModelEmailAddressToJSON
          ),
  };
}
