/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EntityModelMessstelle } from "./EntityModelMessstelle";

import { mapValues } from "../runtime";
import {
  EntityModelMessstelleFromJSON,
  EntityModelMessstelleFromJSONTyped,
  EntityModelMessstelleToJSON,
  EntityModelMessstelleToJSONTyped,
} from "./EntityModelMessstelle";

/**
 *
 * @export
 * @interface PagedModelEntityModelMessstelleEmbedded
 */
export interface PagedModelEntityModelMessstelleEmbedded {
  /**
   *
   * @type {Array<EntityModelMessstelle>}
   * @memberof PagedModelEntityModelMessstelleEmbedded
   */
  messstelles?: Array<EntityModelMessstelle>;
}

/**
 * Check if a given object implements the PagedModelEntityModelMessstelleEmbedded interface.
 */
export function instanceOfPagedModelEntityModelMessstelleEmbedded(
  value: object
): value is PagedModelEntityModelMessstelleEmbedded {
  return true;
}

export function PagedModelEntityModelMessstelleEmbeddedFromJSON(
  json: any
): PagedModelEntityModelMessstelleEmbedded {
  return PagedModelEntityModelMessstelleEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelMessstelleEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PagedModelEntityModelMessstelleEmbedded {
  if (json == null) {
    return json;
  }
  return {
    messstelles:
      json["messstelles"] == null
        ? undefined
        : (json["messstelles"] as Array<any>).map(
            EntityModelMessstelleFromJSON
          ),
  };
}

export function PagedModelEntityModelMessstelleEmbeddedToJSON(
  json: any
): PagedModelEntityModelMessstelleEmbedded {
  return PagedModelEntityModelMessstelleEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelMessstelleEmbeddedToJSONTyped(
  value?: PagedModelEntityModelMessstelleEmbedded | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    messstelles:
      value["messstelles"] == null
        ? undefined
        : (value["messstelles"] as Array<any>).map(EntityModelMessstelleToJSON),
  };
}
