/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelOptionsmenueSettings } from './EntityModelOptionsmenueSettings';
import {
    EntityModelOptionsmenueSettingsFromJSON,
    EntityModelOptionsmenueSettingsFromJSONTyped,
    EntityModelOptionsmenueSettingsToJSON,
    EntityModelOptionsmenueSettingsToJSONTyped,
} from './EntityModelOptionsmenueSettings';

/**
 * 
 * @export
 * @interface PagedModelEntityModelOptionsmenueSettingsEmbedded
 */
export interface PagedModelEntityModelOptionsmenueSettingsEmbedded {
    /**
     * 
     * @type {Array<EntityModelOptionsmenueSettings>}
     * @memberof PagedModelEntityModelOptionsmenueSettingsEmbedded
     */
    optionsmenueSettingses?: Array<EntityModelOptionsmenueSettings>;
}

/**
 * Check if a given object implements the PagedModelEntityModelOptionsmenueSettingsEmbedded interface.
 */
export function instanceOfPagedModelEntityModelOptionsmenueSettingsEmbedded(value: object): value is PagedModelEntityModelOptionsmenueSettingsEmbedded {
    return true;
}

export function PagedModelEntityModelOptionsmenueSettingsEmbeddedFromJSON(json: any): PagedModelEntityModelOptionsmenueSettingsEmbedded {
    return PagedModelEntityModelOptionsmenueSettingsEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelOptionsmenueSettingsEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelOptionsmenueSettingsEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'optionsmenueSettingses': json['optionsmenueSettingses'] == null ? undefined : ((json['optionsmenueSettingses'] as Array<any>).map(EntityModelOptionsmenueSettingsFromJSON)),
    };
}

export function PagedModelEntityModelOptionsmenueSettingsEmbeddedToJSON(json: any): PagedModelEntityModelOptionsmenueSettingsEmbedded {
    return PagedModelEntityModelOptionsmenueSettingsEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelOptionsmenueSettingsEmbeddedToJSONTyped(value?: PagedModelEntityModelOptionsmenueSettingsEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'optionsmenueSettingses': value['optionsmenueSettingses'] == null ? undefined : ((value['optionsmenueSettingses'] as Array<any>).map(EntityModelOptionsmenueSettingsToJSON)),
    };
}

