/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface PkwEinheitDTO
 */
export interface PkwEinheitDTO {
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  pkw?: number;
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  lkw?: number;
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  lastzuege?: number;
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  busse?: number;
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  kraftraeder?: number;
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  fahrradfahrer?: number;
  /**
   *
   * @type {number}
   * @memberof PkwEinheitDTO
   */
  fussgaenger?: number;
}

/**
 * Check if a given object implements the PkwEinheitDTO interface.
 */
export function instanceOfPkwEinheitDTO(value: object): value is PkwEinheitDTO {
  return true;
}

export function PkwEinheitDTOFromJSON(json: any): PkwEinheitDTO {
  return PkwEinheitDTOFromJSONTyped(json, false);
}

export function PkwEinheitDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PkwEinheitDTO {
  if (json == null) {
    return json;
  }
  return {
    pkw: json["pkw"] == null ? undefined : json["pkw"],
    lkw: json["lkw"] == null ? undefined : json["lkw"],
    lastzuege: json["lastzuege"] == null ? undefined : json["lastzuege"],
    busse: json["busse"] == null ? undefined : json["busse"],
    kraftraeder: json["kraftraeder"] == null ? undefined : json["kraftraeder"],
    fahrradfahrer:
      json["fahrradfahrer"] == null ? undefined : json["fahrradfahrer"],
    fussgaenger: json["fussgaenger"] == null ? undefined : json["fussgaenger"],
  };
}

export function PkwEinheitDTOToJSON(json: any): PkwEinheitDTO {
  return PkwEinheitDTOToJSONTyped(json, false);
}

export function PkwEinheitDTOToJSONTyped(
  value?: PkwEinheitDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    pkw: value["pkw"],
    lkw: value["lkw"],
    lastzuege: value["lastzuege"],
    busse: value["busse"],
    kraftraeder: value["kraftraeder"],
    fahrradfahrer: value["fahrradfahrer"],
    fussgaenger: value["fussgaenger"],
  };
}
