/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PkwEinheit
 */
export interface PkwEinheit {
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    pkw?: number;
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    lkw?: number;
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    lastzuege?: number;
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    busse?: number;
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    kraftraeder?: number;
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    fahrradfahrer?: number;
    /**
     * 
     * @type {number}
     * @memberof PkwEinheit
     */
    fussgaenger?: number;
}

/**
 * Check if a given object implements the PkwEinheit interface.
 */
export function instanceOfPkwEinheit(value: object): value is PkwEinheit {
    return true;
}

export function PkwEinheitFromJSON(json: any): PkwEinheit {
    return PkwEinheitFromJSONTyped(json, false);
}

export function PkwEinheitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PkwEinheit {
    if (json == null) {
        return json;
    }
    return {
        
        'pkw': json['pkw'] == null ? undefined : json['pkw'],
        'lkw': json['lkw'] == null ? undefined : json['lkw'],
        'lastzuege': json['lastzuege'] == null ? undefined : json['lastzuege'],
        'busse': json['busse'] == null ? undefined : json['busse'],
        'kraftraeder': json['kraftraeder'] == null ? undefined : json['kraftraeder'],
        'fahrradfahrer': json['fahrradfahrer'] == null ? undefined : json['fahrradfahrer'],
        'fussgaenger': json['fussgaenger'] == null ? undefined : json['fussgaenger'],
    };
}

export function PkwEinheitToJSON(json: any): PkwEinheit {
    return PkwEinheitToJSONTyped(json, false);
}

export function PkwEinheitToJSONTyped(value?: PkwEinheit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pkw': value['pkw'],
        'lkw': value['lkw'],
        'lastzuege': value['lastzuege'],
        'busse': value['busse'],
        'kraftraeder': value['kraftraeder'],
        'fahrradfahrer': value['fahrradfahrer'],
        'fussgaenger': value['fussgaenger'],
    };
}

