/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface PositionUTM
 */
export interface PositionUTM {
  /**
   *
   * @type {number}
   * @memberof PositionUTM
   */
  zone?: number;
  /**
   *
   * @type {string}
   * @memberof PositionUTM
   */
  letter?: string;
  /**
   *
   * @type {number}
   * @memberof PositionUTM
   */
  easting?: number;
  /**
   *
   * @type {number}
   * @memberof PositionUTM
   */
  northing?: number;
}

/**
 * Check if a given object implements the PositionUTM interface.
 */
export function instanceOfPositionUTM(value: object): value is PositionUTM {
  return true;
}

export function PositionUTMFromJSON(json: any): PositionUTM {
  return PositionUTMFromJSONTyped(json, false);
}

export function PositionUTMFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PositionUTM {
  if (json == null) {
    return json;
  }
  return {
    zone: json["zone"] == null ? undefined : json["zone"],
    letter: json["letter"] == null ? undefined : json["letter"],
    easting: json["easting"] == null ? undefined : json["easting"],
    northing: json["northing"] == null ? undefined : json["northing"],
  };
}

export function PositionUTMToJSON(json: any): PositionUTM {
  return PositionUTMToJSONTyped(json, false);
}

export function PositionUTMToJSONTyped(
  value?: PositionUTM | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    zone: value["zone"],
    letter: value["letter"],
    easting: value["easting"],
    northing: value["northing"],
  };
}
