/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ReadMessquerschnittDTO
 */
export interface ReadMessquerschnittDTO {
  /**
   *
   * @type {string}
   * @memberof ReadMessquerschnittDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof ReadMessquerschnittDTO
   */
  mqId?: string;
  /**
   *
   * @type {number}
   * @memberof ReadMessquerschnittDTO
   */
  longitude?: number;
  /**
   *
   * @type {number}
   * @memberof ReadMessquerschnittDTO
   */
  latitude?: number;
  /**
   *
   * @type {string}
   * @memberof ReadMessquerschnittDTO
   */
  strassenname?: string;
  /**
   *
   * @type {string}
   * @memberof ReadMessquerschnittDTO
   */
  lageMessquerschnitt?: string;
  /**
   *
   * @type {string}
   * @memberof ReadMessquerschnittDTO
   */
  fahrtrichtung?: string;
  /**
   *
   * @type {number}
   * @memberof ReadMessquerschnittDTO
   */
  anzahlFahrspuren?: number;
  /**
   *
   * @type {number}
   * @memberof ReadMessquerschnittDTO
   */
  anzahlDetektoren?: number;
  /**
   *
   * @type {string}
   * @memberof ReadMessquerschnittDTO
   */
  standort?: string;
}

/**
 * Check if a given object implements the ReadMessquerschnittDTO interface.
 */
export function instanceOfReadMessquerschnittDTO(
  value: object
): value is ReadMessquerschnittDTO {
  return true;
}

export function ReadMessquerschnittDTOFromJSON(
  json: any
): ReadMessquerschnittDTO {
  return ReadMessquerschnittDTOFromJSONTyped(json, false);
}

export function ReadMessquerschnittDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReadMessquerschnittDTO {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    mqId: json["mqId"] == null ? undefined : json["mqId"],
    longitude: json["longitude"] == null ? undefined : json["longitude"],
    latitude: json["latitude"] == null ? undefined : json["latitude"],
    strassenname:
      json["strassenname"] == null ? undefined : json["strassenname"],
    lageMessquerschnitt:
      json["lageMessquerschnitt"] == null
        ? undefined
        : json["lageMessquerschnitt"],
    fahrtrichtung:
      json["fahrtrichtung"] == null ? undefined : json["fahrtrichtung"],
    anzahlFahrspuren:
      json["anzahlFahrspuren"] == null ? undefined : json["anzahlFahrspuren"],
    anzahlDetektoren:
      json["anzahlDetektoren"] == null ? undefined : json["anzahlDetektoren"],
    standort: json["standort"] == null ? undefined : json["standort"],
  };
}

export function ReadMessquerschnittDTOToJSON(
  json: any
): ReadMessquerschnittDTO {
  return ReadMessquerschnittDTOToJSONTyped(json, false);
}

export function ReadMessquerschnittDTOToJSONTyped(
  value?: ReadMessquerschnittDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    mqId: value["mqId"],
    longitude: value["longitude"],
    latitude: value["latitude"],
    strassenname: value["strassenname"],
    lageMessquerschnitt: value["lageMessquerschnitt"],
    fahrtrichtung: value["fahrtrichtung"],
    anzahlFahrspuren: value["anzahlFahrspuren"],
    anzahlDetektoren: value["anzahlDetektoren"],
    standort: value["standort"],
  };
}
