/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ReadMessfaehigkeitDTO
 */
export interface ReadMessfaehigkeitDTO {
  /**
   *
   * @type {string}
   * @memberof ReadMessfaehigkeitDTO
   */
  gueltigBis?: string;
  /**
   *
   * @type {string}
   * @memberof ReadMessfaehigkeitDTO
   */
  gueltigAb?: string;
  /**
   *
   * @type {string}
   * @memberof ReadMessfaehigkeitDTO
   */
  fahrzeugklasse?: ReadMessfaehigkeitDTOFahrzeugklasseEnum;
  /**
   *
   * @type {string}
   * @memberof ReadMessfaehigkeitDTO
   */
  intervall?: ReadMessfaehigkeitDTOIntervallEnum;
}

/**
 * @export
 */
export const ReadMessfaehigkeitDTOFahrzeugklasseEnum = {
  Rad: "RAD",
  SummeKfz: "SUMME_KFZ",
  ZweiPlusEins: "ZWEI_PLUS_EINS",
  AchtPlusEins: "ACHT_PLUS_EINS",
} as const;
export type ReadMessfaehigkeitDTOFahrzeugklasseEnum =
  (typeof ReadMessfaehigkeitDTOFahrzeugklasseEnum)[keyof typeof ReadMessfaehigkeitDTOFahrzeugklasseEnum];

/**
 * @export
 */
export const ReadMessfaehigkeitDTOIntervallEnum = {
  StundeViertel: "STUNDE_VIERTEL",
  StundeViertelEingeschraenkt: "STUNDE_VIERTEL_EINGESCHRAENKT",
  StundeHalb: "STUNDE_HALB",
  StundeKomplett: "STUNDE_KOMPLETT",
} as const;
export type ReadMessfaehigkeitDTOIntervallEnum =
  (typeof ReadMessfaehigkeitDTOIntervallEnum)[keyof typeof ReadMessfaehigkeitDTOIntervallEnum];

/**
 * Check if a given object implements the ReadMessfaehigkeitDTO interface.
 */
export function instanceOfReadMessfaehigkeitDTO(
  value: object
): value is ReadMessfaehigkeitDTO {
  return true;
}

export function ReadMessfaehigkeitDTOFromJSON(
  json: any
): ReadMessfaehigkeitDTO {
  return ReadMessfaehigkeitDTOFromJSONTyped(json, false);
}

export function ReadMessfaehigkeitDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReadMessfaehigkeitDTO {
  if (json == null) {
    return json;
  }
  return {
    gueltigBis: json["gueltigBis"] == null ? undefined : json["gueltigBis"],
    gueltigAb: json["gueltigAb"] == null ? undefined : json["gueltigAb"],
    fahrzeugklasse:
      json["fahrzeugklasse"] == null ? undefined : json["fahrzeugklasse"],
    intervall: json["intervall"] == null ? undefined : json["intervall"],
  };
}

export function ReadMessfaehigkeitDTOToJSON(json: any): ReadMessfaehigkeitDTO {
  return ReadMessfaehigkeitDTOToJSONTyped(json, false);
}

export function ReadMessfaehigkeitDTOToJSONTyped(
  value?: ReadMessfaehigkeitDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    gueltigBis: value["gueltigBis"],
    gueltigAb: value["gueltigAb"],
    fahrzeugklasse: value["fahrzeugklasse"],
    intervall: value["intervall"],
  };
}
