/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Rounding = {
  None: "NONE",
  R10: "R10",
  R100: "R100",
} as const;
export type Rounding = (typeof Rounding)[keyof typeof Rounding];

export function instanceOfRounding(value: any): boolean {
  for (const key in Rounding) {
    if (Object.prototype.hasOwnProperty.call(Rounding, key)) {
      if (Rounding[key as keyof typeof Rounding] === value) {
        return true;
      }
    }
  }
  return false;
}

export function RoundingFromJSON(json: any): Rounding {
  return RoundingFromJSONTyped(json, false);
}

export function RoundingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Rounding {
  return json as Rounding;
}

export function RoundingToJSON(value?: Rounding | null): any {
  return value as any;
}

export function RoundingToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): Rounding {
  return value as Rounding;
}
