/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Verkehrsart } from "./Verkehrsart";

import { mapValues } from "../runtime";
import {
  VerkehrsartFromJSON,
  VerkehrsartFromJSONTyped,
  VerkehrsartToJSON,
  VerkehrsartToJSONTyped,
} from "./Verkehrsart";

/**
 *
 * @export
 * @interface SearchAndFilterOptionsDTO
 */
export interface SearchAndFilterOptionsDTO {
  /**
   *
   * @type {boolean}
   * @memberof SearchAndFilterOptionsDTO
   */
  searchInMessstellen?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof SearchAndFilterOptionsDTO
   */
  searchInZaehlstellen?: boolean;
  /**
   *
   * @type {Array<Verkehrsart>}
   * @memberof SearchAndFilterOptionsDTO
   */
  messstelleVerkehrsart: Array<Verkehrsart>;
}

/**
 * Check if a given object implements the SearchAndFilterOptionsDTO interface.
 */
export function instanceOfSearchAndFilterOptionsDTO(
  value: object
): value is SearchAndFilterOptionsDTO {
  if (
    !("messstelleVerkehrsart" in value) ||
    value["messstelleVerkehrsart"] === undefined
  )
    return false;
  return true;
}

export function SearchAndFilterOptionsDTOFromJSON(
  json: any
): SearchAndFilterOptionsDTO {
  return SearchAndFilterOptionsDTOFromJSONTyped(json, false);
}

export function SearchAndFilterOptionsDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SearchAndFilterOptionsDTO {
  if (json == null) {
    return json;
  }
  return {
    searchInMessstellen:
      json["searchInMessstellen"] == null
        ? undefined
        : json["searchInMessstellen"],
    searchInZaehlstellen:
      json["searchInZaehlstellen"] == null
        ? undefined
        : json["searchInZaehlstellen"],
    messstelleVerkehrsart: (json["messstelleVerkehrsart"] as Array<any>).map(
      VerkehrsartFromJSON
    ),
  };
}

export function SearchAndFilterOptionsDTOToJSON(
  json: any
): SearchAndFilterOptionsDTO {
  return SearchAndFilterOptionsDTOToJSONTyped(json, false);
}

export function SearchAndFilterOptionsDTOToJSONTyped(
  value?: SearchAndFilterOptionsDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    searchInMessstellen: value["searchInMessstellen"],
    searchInZaehlstellen: value["searchInZaehlstellen"],
    messstelleVerkehrsart: (value["messstelleVerkehrsart"] as Array<any>).map(
      VerkehrsartToJSON
    ),
  };
}
