/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StepLineSeriesEntryBaseDTO } from "./StepLineSeriesEntryBaseDTO";

import { mapValues } from "../runtime";
import {
  StepLineSeriesEntryBaseDTOFromJSON,
  StepLineSeriesEntryBaseDTOFromJSONTyped,
  StepLineSeriesEntryBaseDTOToJSON,
  StepLineSeriesEntryBaseDTOToJSONTyped,
} from "./StepLineSeriesEntryBaseDTO";

/**
 *
 * @export
 * @interface StepLineSeriesEntryBigDecimalDTO
 */
export interface StepLineSeriesEntryBigDecimalDTO
  extends StepLineSeriesEntryBaseDTO {
  /**
   *
   * @type {Array<number>}
   * @memberof StepLineSeriesEntryBigDecimalDTO
   */
  yaxisData?: Array<number>;
}

/**
 * Check if a given object implements the StepLineSeriesEntryBigDecimalDTO interface.
 */
export function instanceOfStepLineSeriesEntryBigDecimalDTO(
  value: object
): value is StepLineSeriesEntryBigDecimalDTO {
  return true;
}

export function StepLineSeriesEntryBigDecimalDTOFromJSON(
  json: any
): StepLineSeriesEntryBigDecimalDTO {
  return StepLineSeriesEntryBigDecimalDTOFromJSONTyped(json, false);
}

export function StepLineSeriesEntryBigDecimalDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StepLineSeriesEntryBigDecimalDTO {
  if (json == null) {
    return json;
  }
  return {
    ...StepLineSeriesEntryBaseDTOFromJSONTyped(json, true),
    yaxisData: json["yaxisData"] == null ? undefined : json["yaxisData"],
  };
}

export function StepLineSeriesEntryBigDecimalDTOToJSON(
  json: any
): StepLineSeriesEntryBigDecimalDTO {
  return StepLineSeriesEntryBigDecimalDTOToJSONTyped(json, false);
}

export function StepLineSeriesEntryBigDecimalDTOToJSONTyped(
  value?: StepLineSeriesEntryBigDecimalDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ...StepLineSeriesEntryBaseDTOToJSONTyped(value, true),
    yaxisData: value["yaxisData"],
  };
}
