/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LaengsverkehrValue } from "./LaengsverkehrValue";

import { mapValues } from "../runtime";
import {
  LaengsverkehrValueFromJSON,
  LaengsverkehrValueFromJSONTyped,
  LaengsverkehrValueToJSON,
  LaengsverkehrValueToJSONTyped,
} from "./LaengsverkehrValue";

/**
 *
 * @export
 * @interface StrassenseiteValue
 */
export interface StrassenseiteValue {
  /**
   *
   * @type {string}
   * @memberof StrassenseiteValue
   */
  strassenseite: StrassenseiteValueStrassenseiteEnum;
  /**
   *
   * @type {number}
   * @memberof StrassenseiteValue
   */
  sumStrassenseite: number;
  /**
   *
   * @type {Array<LaengsverkehrValue>}
   * @memberof StrassenseiteValue
   */
  valuesLaengsverkehre: Array<LaengsverkehrValue>;
}

/**
 * @export
 */
export const StrassenseiteValueStrassenseiteEnum = {
  N: "N",
  No: "NO",
  O: "O",
  So: "SO",
  S: "S",
  Sw: "SW",
  W: "W",
  Nw: "NW",
} as const;
export type StrassenseiteValueStrassenseiteEnum =
  (typeof StrassenseiteValueStrassenseiteEnum)[keyof typeof StrassenseiteValueStrassenseiteEnum];

/**
 * Check if a given object implements the StrassenseiteValue interface.
 */
export function instanceOfStrassenseiteValue(
  value: object
): value is StrassenseiteValue {
  if (!("strassenseite" in value) || value["strassenseite"] === undefined)
    return false;
  if (!("sumStrassenseite" in value) || value["sumStrassenseite"] === undefined)
    return false;
  if (
    !("valuesLaengsverkehre" in value) ||
    value["valuesLaengsverkehre"] === undefined
  )
    return false;
  return true;
}

export function StrassenseiteValueFromJSON(json: any): StrassenseiteValue {
  return StrassenseiteValueFromJSONTyped(json, false);
}

export function StrassenseiteValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StrassenseiteValue {
  if (json == null) {
    return json;
  }
  return {
    strassenseite: json["strassenseite"],
    sumStrassenseite: json["sumStrassenseite"],
    valuesLaengsverkehre: (json["valuesLaengsverkehre"] as Array<any>).map(
      LaengsverkehrValueFromJSON
    ),
  };
}

export function StrassenseiteValueToJSON(json: any): StrassenseiteValue {
  return StrassenseiteValueToJSONTyped(json, false);
}

export function StrassenseiteValueToJSONTyped(
  value?: StrassenseiteValue | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    strassenseite: value["strassenseite"],
    sumStrassenseite: value["sumStrassenseite"],
    valuesLaengsverkehre: (value["valuesLaengsverkehre"] as Array<any>).map(
      LaengsverkehrValueToJSON
    ),
  };
}
