/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SucheMessstelleSuggestDTO } from "./SucheMessstelleSuggestDTO";
import type { SucheWordSuggestDTO } from "./SucheWordSuggestDTO";
import type { SucheZaehlstelleSuggestDTO } from "./SucheZaehlstelleSuggestDTO";
import type { SucheZaehlungSuggestDTO } from "./SucheZaehlungSuggestDTO";

import { mapValues } from "../runtime";
import {
  SucheMessstelleSuggestDTOFromJSON,
  SucheMessstelleSuggestDTOFromJSONTyped,
  SucheMessstelleSuggestDTOToJSON,
  SucheMessstelleSuggestDTOToJSONTyped,
} from "./SucheMessstelleSuggestDTO";
import {
  SucheWordSuggestDTOFromJSON,
  SucheWordSuggestDTOFromJSONTyped,
  SucheWordSuggestDTOToJSON,
  SucheWordSuggestDTOToJSONTyped,
} from "./SucheWordSuggestDTO";
import {
  SucheZaehlstelleSuggestDTOFromJSON,
  SucheZaehlstelleSuggestDTOFromJSONTyped,
  SucheZaehlstelleSuggestDTOToJSON,
  SucheZaehlstelleSuggestDTOToJSONTyped,
} from "./SucheZaehlstelleSuggestDTO";
import {
  SucheZaehlungSuggestDTOFromJSON,
  SucheZaehlungSuggestDTOFromJSONTyped,
  SucheZaehlungSuggestDTOToJSON,
  SucheZaehlungSuggestDTOToJSONTyped,
} from "./SucheZaehlungSuggestDTO";

/**
 *
 * @export
 * @interface SucheComplexSuggestsDTO
 */
export interface SucheComplexSuggestsDTO {
  /**
   *
   * @type {Array<SucheWordSuggestDTO>}
   * @memberof SucheComplexSuggestsDTO
   */
  wordSuggests?: Array<SucheWordSuggestDTO>;
  /**
   *
   * @type {Array<SucheZaehlstelleSuggestDTO>}
   * @memberof SucheComplexSuggestsDTO
   */
  zaehlstellenSuggests?: Array<SucheZaehlstelleSuggestDTO>;
  /**
   *
   * @type {Array<SucheZaehlungSuggestDTO>}
   * @memberof SucheComplexSuggestsDTO
   */
  zaehlungenSuggests?: Array<SucheZaehlungSuggestDTO>;
  /**
   *
   * @type {Array<SucheMessstelleSuggestDTO>}
   * @memberof SucheComplexSuggestsDTO
   */
  messstellenSuggests?: Array<SucheMessstelleSuggestDTO>;
}

/**
 * Check if a given object implements the SucheComplexSuggestsDTO interface.
 */
export function instanceOfSucheComplexSuggestsDTO(
  value: object
): value is SucheComplexSuggestsDTO {
  return true;
}

export function SucheComplexSuggestsDTOFromJSON(
  json: any
): SucheComplexSuggestsDTO {
  return SucheComplexSuggestsDTOFromJSONTyped(json, false);
}

export function SucheComplexSuggestsDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SucheComplexSuggestsDTO {
  if (json == null) {
    return json;
  }
  return {
    wordSuggests:
      json["wordSuggests"] == null
        ? undefined
        : (json["wordSuggests"] as Array<any>).map(SucheWordSuggestDTOFromJSON),
    zaehlstellenSuggests:
      json["zaehlstellenSuggests"] == null
        ? undefined
        : (json["zaehlstellenSuggests"] as Array<any>).map(
            SucheZaehlstelleSuggestDTOFromJSON
          ),
    zaehlungenSuggests:
      json["zaehlungenSuggests"] == null
        ? undefined
        : (json["zaehlungenSuggests"] as Array<any>).map(
            SucheZaehlungSuggestDTOFromJSON
          ),
    messstellenSuggests:
      json["messstellenSuggests"] == null
        ? undefined
        : (json["messstellenSuggests"] as Array<any>).map(
            SucheMessstelleSuggestDTOFromJSON
          ),
  };
}

export function SucheComplexSuggestsDTOToJSON(
  json: any
): SucheComplexSuggestsDTO {
  return SucheComplexSuggestsDTOToJSONTyped(json, false);
}

export function SucheComplexSuggestsDTOToJSONTyped(
  value?: SucheComplexSuggestsDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    wordSuggests:
      value["wordSuggests"] == null
        ? undefined
        : (value["wordSuggests"] as Array<any>).map(SucheWordSuggestDTOToJSON),
    zaehlstellenSuggests:
      value["zaehlstellenSuggests"] == null
        ? undefined
        : (value["zaehlstellenSuggests"] as Array<any>).map(
            SucheZaehlstelleSuggestDTOToJSON
          ),
    zaehlungenSuggests:
      value["zaehlungenSuggests"] == null
        ? undefined
        : (value["zaehlungenSuggests"] as Array<any>).map(
            SucheZaehlungSuggestDTOToJSON
          ),
    messstellenSuggests:
      value["messstellenSuggests"] == null
        ? undefined
        : (value["messstellenSuggests"] as Array<any>).map(
            SucheMessstelleSuggestDTOToJSON
          ),
  };
}
