/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SucheMessstelleSuggestDTO
 */
export interface SucheMessstelleSuggestDTO {
  /**
   *
   * @type {string}
   * @memberof SucheMessstelleSuggestDTO
   */
  text?: string;
  /**
   *
   * @type {string}
   * @memberof SucheMessstelleSuggestDTO
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof SucheMessstelleSuggestDTO
   */
  sichtbarDatenportal?: boolean;
}

/**
 * Check if a given object implements the SucheMessstelleSuggestDTO interface.
 */
export function instanceOfSucheMessstelleSuggestDTO(
  value: object
): value is SucheMessstelleSuggestDTO {
  return true;
}

export function SucheMessstelleSuggestDTOFromJSON(
  json: any
): SucheMessstelleSuggestDTO {
  return SucheMessstelleSuggestDTOFromJSONTyped(json, false);
}

export function SucheMessstelleSuggestDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SucheMessstelleSuggestDTO {
  if (json == null) {
    return json;
  }
  return {
    text: json["text"] == null ? undefined : json["text"],
    id: json["id"] == null ? undefined : json["id"],
    sichtbarDatenportal:
      json["sichtbarDatenportal"] == null
        ? undefined
        : json["sichtbarDatenportal"],
  };
}

export function SucheMessstelleSuggestDTOToJSON(
  json: any
): SucheMessstelleSuggestDTO {
  return SucheMessstelleSuggestDTOToJSONTyped(json, false);
}

export function SucheMessstelleSuggestDTOToJSONTyped(
  value?: SucheMessstelleSuggestDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    text: value["text"],
    id: value["id"],
    sichtbarDatenportal: value["sichtbarDatenportal"],
  };
}
