/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SucheZaehlungSuggestDTO
 */
export interface SucheZaehlungSuggestDTO {
  /**
   *
   * @type {string}
   * @memberof SucheZaehlungSuggestDTO
   */
  text: string;
  /**
   *
   * @type {string}
   * @memberof SucheZaehlungSuggestDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof SucheZaehlungSuggestDTO
   */
  zaehlstelleId: string;
  /**
   *
   * @type {boolean}
   * @memberof SucheZaehlungSuggestDTO
   */
  sichtbarDatenportal: boolean;
}

/**
 * Check if a given object implements the SucheZaehlungSuggestDTO interface.
 */
export function instanceOfSucheZaehlungSuggestDTO(
  value: object
): value is SucheZaehlungSuggestDTO {
  if (!("text" in value) || value["text"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("zaehlstelleId" in value) || value["zaehlstelleId"] === undefined)
    return false;
  if (
    !("sichtbarDatenportal" in value) ||
    value["sichtbarDatenportal"] === undefined
  )
    return false;
  return true;
}

export function SucheZaehlungSuggestDTOFromJSON(
  json: any
): SucheZaehlungSuggestDTO {
  return SucheZaehlungSuggestDTOFromJSONTyped(json, false);
}

export function SucheZaehlungSuggestDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SucheZaehlungSuggestDTO {
  if (json == null) {
    return json;
  }
  return {
    text: json["text"],
    id: json["id"],
    zaehlstelleId: json["zaehlstelleId"],
    sichtbarDatenportal: json["sichtbarDatenportal"],
  };
}

export function SucheZaehlungSuggestDTOToJSON(
  json: any
): SucheZaehlungSuggestDTO {
  return SucheZaehlungSuggestDTOToJSONTyped(json, false);
}

export function SucheZaehlungSuggestDTOToJSONTyped(
  value?: SucheZaehlungSuggestDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    text: value["text"],
    id: value["id"],
    zaehlstelleId: value["zaehlstelleId"],
    sichtbarDatenportal: value["sichtbarDatenportal"],
  };
}
