/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface SucheZaehlstelleSuggestDTO
 */
export interface SucheZaehlstelleSuggestDTO {
  /**
   *
   * @type {string}
   * @memberof SucheZaehlstelleSuggestDTO
   */
  text?: string;
  /**
   *
   * @type {string}
   * @memberof SucheZaehlstelleSuggestDTO
   */
  id?: string;
  /**
   *
   * @type {boolean}
   * @memberof SucheZaehlstelleSuggestDTO
   */
  sichtbarDatenportal?: boolean;
}

/**
 * Check if a given object implements the SucheZaehlstelleSuggestDTO interface.
 */
export function instanceOfSucheZaehlstelleSuggestDTO(
  value: object
): value is SucheZaehlstelleSuggestDTO {
  return true;
}

export function SucheZaehlstelleSuggestDTOFromJSON(
  json: any
): SucheZaehlstelleSuggestDTO {
  return SucheZaehlstelleSuggestDTOFromJSONTyped(json, false);
}

export function SucheZaehlstelleSuggestDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SucheZaehlstelleSuggestDTO {
  if (json == null) {
    return json;
  }
  return {
    text: json["text"] == null ? undefined : json["text"],
    id: json["id"] == null ? undefined : json["id"],
    sichtbarDatenportal:
      json["sichtbarDatenportal"] == null
        ? undefined
        : json["sichtbarDatenportal"],
  };
}

export function SucheZaehlstelleSuggestDTOToJSON(
  json: any
): SucheZaehlstelleSuggestDTO {
  return SucheZaehlstelleSuggestDTOToJSONTyped(json, false);
}

export function SucheZaehlstelleSuggestDTOToJSONTyped(
  value?: SucheZaehlstelleSuggestDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    text: value["text"],
    id: value["id"],
    sichtbarDatenportal: value["sichtbarDatenportal"],
  };
}
