/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface UpdateStatusDTO
 */
export interface UpdateStatusDTO {
  /**
   *
   * @type {string}
   * @memberof UpdateStatusDTO
   */
  zaehlungId?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateStatusDTO
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateStatusDTO
   */
  dienstleisterkennung?: string;
}

/**
 * Check if a given object implements the UpdateStatusDTO interface.
 */
export function instanceOfUpdateStatusDTO(
  value: object
): value is UpdateStatusDTO {
  return true;
}

export function UpdateStatusDTOFromJSON(json: any): UpdateStatusDTO {
  return UpdateStatusDTOFromJSONTyped(json, false);
}

export function UpdateStatusDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateStatusDTO {
  if (json == null) {
    return json;
  }
  return {
    zaehlungId: json["zaehlungId"] == null ? undefined : json["zaehlungId"],
    status: json["status"] == null ? undefined : json["status"],
    dienstleisterkennung:
      json["dienstleisterkennung"] == null
        ? undefined
        : json["dienstleisterkennung"],
  };
}

export function UpdateStatusDTOToJSON(json: any): UpdateStatusDTO {
  return UpdateStatusDTOToJSONTyped(json, false);
}

export function UpdateStatusDTOToJSONTyped(
  value?: UpdateStatusDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    zaehlungId: value["zaehlungId"],
    status: value["status"],
    dienstleisterkennung: value["dienstleisterkennung"],
  };
}
