/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TagesTyp } from "./TagesTyp";

import { mapValues } from "../runtime";
import {
  TagesTypFromJSON,
  TagesTypFromJSONTyped,
  TagesTypToJSON,
  TagesTypToJSONTyped,
} from "./TagesTyp";

/**
 *
 * @export
 * @interface ValidateZeitraumAndTagestypForMessstelleDTO
 */
export interface ValidateZeitraumAndTagestypForMessstelleDTO {
  /**
   *
   * @type {Array<Date>}
   * @memberof ValidateZeitraumAndTagestypForMessstelleDTO
   */
  zeitraum: Array<Date>;
  /**
   *
   * @type {string}
   * @memberof ValidateZeitraumAndTagestypForMessstelleDTO
   */
  mstId: string;
  /**
   *
   * @type {TagesTyp}
   * @memberof ValidateZeitraumAndTagestypForMessstelleDTO
   */
  tagesTyp: TagesTyp;
}

/**
 * Check if a given object implements the ValidateZeitraumAndTagestypForMessstelleDTO interface.
 */
export function instanceOfValidateZeitraumAndTagestypForMessstelleDTO(
  value: object
): value is ValidateZeitraumAndTagestypForMessstelleDTO {
  if (!("zeitraum" in value) || value["zeitraum"] === undefined) return false;
  if (!("mstId" in value) || value["mstId"] === undefined) return false;
  if (!("tagesTyp" in value) || value["tagesTyp"] === undefined) return false;
  return true;
}

export function ValidateZeitraumAndTagestypForMessstelleDTOFromJSON(
  json: any
): ValidateZeitraumAndTagestypForMessstelleDTO {
  return ValidateZeitraumAndTagestypForMessstelleDTOFromJSONTyped(json, false);
}

export function ValidateZeitraumAndTagestypForMessstelleDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ValidateZeitraumAndTagestypForMessstelleDTO {
  if (json == null) {
    return json;
  }
  return {
    zeitraum: json["zeitraum"],
    mstId: json["mstId"],
    tagesTyp: TagesTypFromJSON(json["tagesTyp"]),
  };
}

export function ValidateZeitraumAndTagestypForMessstelleDTOToJSON(
  json: any
): ValidateZeitraumAndTagestypForMessstelleDTO {
  return ValidateZeitraumAndTagestypForMessstelleDTOToJSONTyped(json, false);
}

export function ValidateZeitraumAndTagestypForMessstelleDTOToJSONTyped(
  value?: ValidateZeitraumAndTagestypForMessstelleDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    zeitraum: value["zeitraum"],
    mstId: value["mstId"],
    tagesTyp: TagesTypToJSON(value["tagesTyp"]),
  };
}
