/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ValidatedZeitraumAndTagestypDTO
 */
export interface ValidatedZeitraumAndTagestypDTO {
  /**
   *
   * @type {boolean}
   * @memberof ValidatedZeitraumAndTagestypDTO
   */
  isValid: boolean;
}

/**
 * Check if a given object implements the ValidatedZeitraumAndTagestypDTO interface.
 */
export function instanceOfValidatedZeitraumAndTagestypDTO(
  value: object
): value is ValidatedZeitraumAndTagestypDTO {
  if (!("isValid" in value) || value["isValid"] === undefined) return false;
  return true;
}

export function ValidatedZeitraumAndTagestypDTOFromJSON(
  json: any
): ValidatedZeitraumAndTagestypDTO {
  return ValidatedZeitraumAndTagestypDTOFromJSONTyped(json, false);
}

export function ValidatedZeitraumAndTagestypDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ValidatedZeitraumAndTagestypDTO {
  if (json == null) {
    return json;
  }
  return {
    isValid: json["isValid"],
  };
}

export function ValidatedZeitraumAndTagestypDTOToJSON(
  json: any
): ValidatedZeitraumAndTagestypDTO {
  return ValidatedZeitraumAndTagestypDTOToJSONTyped(json, false);
}

export function ValidatedZeitraumAndTagestypDTOToJSONTyped(
  value?: ValidatedZeitraumAndTagestypDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    isValid: value["isValid"],
  };
}
