/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Verkehrsart = {
  Kfz: "KFZ",
  Rad: "RAD",
  Unbekannt: "UNBEKANNT",
} as const;
export type Verkehrsart = (typeof Verkehrsart)[keyof typeof Verkehrsart];

export function instanceOfVerkehrsart(value: any): boolean {
  for (const key in Verkehrsart) {
    if (Object.prototype.hasOwnProperty.call(Verkehrsart, key)) {
      if (Verkehrsart[key as keyof typeof Verkehrsart] === value) {
        return true;
      }
    }
  }
  return false;
}

export function VerkehrsartFromJSON(json: any): Verkehrsart {
  return VerkehrsartFromJSONTyped(json, false);
}

export function VerkehrsartFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Verkehrsart {
  return json as Verkehrsart;
}

export function VerkehrsartToJSON(value?: Verkehrsart | null): any {
  return value as any;
}

export function VerkehrsartToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean
): Verkehrsart {
  return value as Verkehrsart;
}
