/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Hochrechnungsfaktor } from './Hochrechnungsfaktor';
import {
    HochrechnungsfaktorFromJSON,
    HochrechnungsfaktorFromJSONTyped,
    HochrechnungsfaktorToJSON,
    HochrechnungsfaktorToJSONTyped,
} from './Hochrechnungsfaktor';

/**
 * 
 * @export
 * @interface Verkehrsbeziehung
 */
export interface Verkehrsbeziehung {
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    id?: string;
    /**
     * 
     * @type {Hochrechnungsfaktor}
     * @memberof Verkehrsbeziehung
     */
    hochrechnungsfaktor?: Hochrechnungsfaktor;
    /**
     * 
     * @type {boolean}
     * @memberof Verkehrsbeziehung
     */
    isKreuzung?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Verkehrsbeziehung
     */
    von?: number;
    /**
     * 
     * @type {number}
     * @memberof Verkehrsbeziehung
     */
    nach?: number;
    /**
     * 
     * @type {number}
     * @memberof Verkehrsbeziehung
     */
    knotenarm?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Verkehrsbeziehung
     */
    hinein?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Verkehrsbeziehung
     */
    heraus?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Verkehrsbeziehung
     */
    vorbei?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    strassenseite?: VerkehrsbeziehungStrassenseiteEnum;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    vonknotvonstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    nachknotvonstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    vonStrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    vonknotennachstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    nachknotnachstrnr?: string;
    /**
     * 
     * @type {string}
     * @memberof Verkehrsbeziehung
     */
    nachStrnr?: string;
}


/**
 * @export
 */
export const VerkehrsbeziehungStrassenseiteEnum = {
    N: 'N',
    No: 'NO',
    O: 'O',
    So: 'SO',
    S: 'S',
    Sw: 'SW',
    W: 'W',
    Nw: 'NW'
} as const;
export type VerkehrsbeziehungStrassenseiteEnum = typeof VerkehrsbeziehungStrassenseiteEnum[keyof typeof VerkehrsbeziehungStrassenseiteEnum];


/**
 * Check if a given object implements the Verkehrsbeziehung interface.
 */
export function instanceOfVerkehrsbeziehung(value: object): value is Verkehrsbeziehung {
    return true;
}

export function VerkehrsbeziehungFromJSON(json: any): Verkehrsbeziehung {
    return VerkehrsbeziehungFromJSONTyped(json, false);
}

export function VerkehrsbeziehungFromJSONTyped(json: any, ignoreDiscriminator: boolean): Verkehrsbeziehung {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'hochrechnungsfaktor': json['hochrechnungsfaktor'] == null ? undefined : HochrechnungsfaktorFromJSON(json['hochrechnungsfaktor']),
        'isKreuzung': json['isKreuzung'] == null ? undefined : json['isKreuzung'],
        'von': json['von'] == null ? undefined : json['von'],
        'nach': json['nach'] == null ? undefined : json['nach'],
        'knotenarm': json['knotenarm'] == null ? undefined : json['knotenarm'],
        'hinein': json['hinein'] == null ? undefined : json['hinein'],
        'heraus': json['heraus'] == null ? undefined : json['heraus'],
        'vorbei': json['vorbei'] == null ? undefined : json['vorbei'],
        'strassenseite': json['strassenseite'] == null ? undefined : json['strassenseite'],
        'vonknotvonstrnr': json['vonknotvonstrnr'] == null ? undefined : json['vonknotvonstrnr'],
        'nachknotvonstrnr': json['nachknotvonstrnr'] == null ? undefined : json['nachknotvonstrnr'],
        'vonStrnr': json['von_strnr'] == null ? undefined : json['von_strnr'],
        'vonknotennachstrnr': json['vonknotennachstrnr'] == null ? undefined : json['vonknotennachstrnr'],
        'nachknotnachstrnr': json['nachknotnachstrnr'] == null ? undefined : json['nachknotnachstrnr'],
        'nachStrnr': json['nach_strnr'] == null ? undefined : json['nach_strnr'],
    };
}

export function VerkehrsbeziehungToJSON(json: any): Verkehrsbeziehung {
    return VerkehrsbeziehungToJSONTyped(json, false);
}

export function VerkehrsbeziehungToJSONTyped(value?: Verkehrsbeziehung | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hochrechnungsfaktor': HochrechnungsfaktorToJSON(value['hochrechnungsfaktor']),
        'isKreuzung': value['isKreuzung'],
        'von': value['von'],
        'nach': value['nach'],
        'knotenarm': value['knotenarm'],
        'hinein': value['hinein'],
        'heraus': value['heraus'],
        'vorbei': value['vorbei'],
        'strassenseite': value['strassenseite'],
        'vonknotvonstrnr': value['vonknotvonstrnr'],
        'nachknotvonstrnr': value['nachknotvonstrnr'],
        'von_strnr': value['vonStrnr'],
        'vonknotennachstrnr': value['vonknotennachstrnr'],
        'nachknotnachstrnr': value['nachknotnachstrnr'],
        'nach_strnr': value['nachStrnr'],
    };
}

