/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Himmelsrichtung } from "./Himmelsrichtung";

import { mapValues } from "../runtime";
import {
  HimmelsrichtungFromJSON,
  HimmelsrichtungFromJSONTyped,
  HimmelsrichtungToJSON,
  HimmelsrichtungToJSONTyped,
} from "./Himmelsrichtung";

/**
 *
 * @export
 * @interface VerkehrsbeziehungValue
 */
export interface VerkehrsbeziehungValue {
  /**
   *
   * @type {number}
   * @memberof VerkehrsbeziehungValue
   */
  von: number;
  /**
   *
   * @type {number}
   * @memberof VerkehrsbeziehungValue
   */
  nach: number;
  /**
   *
   * @type {Himmelsrichtung}
   * @memberof VerkehrsbeziehungValue
   */
  strassenseite: Himmelsrichtung;
  /**
   *
   * @type {number}
   * @memberof VerkehrsbeziehungValue
   */
  value: number;
}

/**
 * Check if a given object implements the VerkehrsbeziehungValue interface.
 */
export function instanceOfVerkehrsbeziehungValue(
  value: object
): value is VerkehrsbeziehungValue {
  if (!("von" in value) || value["von"] === undefined) return false;
  if (!("nach" in value) || value["nach"] === undefined) return false;
  if (!("strassenseite" in value) || value["strassenseite"] === undefined)
    return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function VerkehrsbeziehungValueFromJSON(
  json: any
): VerkehrsbeziehungValue {
  return VerkehrsbeziehungValueFromJSONTyped(json, false);
}

export function VerkehrsbeziehungValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): VerkehrsbeziehungValue {
  if (json == null) {
    return json;
  }
  return {
    von: json["von"],
    nach: json["nach"],
    strassenseite: HimmelsrichtungFromJSON(json["strassenseite"]),
    value: json["value"],
  };
}

export function VerkehrsbeziehungValueToJSON(
  json: any
): VerkehrsbeziehungValue {
  return VerkehrsbeziehungValueToJSONTyped(json, false);
}

export function VerkehrsbeziehungValueToJSONTyped(
  value?: VerkehrsbeziehungValue | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    von: value["von"],
    nach: value["nach"],
    strassenseite: HimmelsrichtungToJSON(value["strassenseite"]),
    value: value["value"],
  };
}
