/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZaehlungskenngroessenData } from './ZaehlungskenngroessenData';
import {
    ZaehlungskenngroessenDataFromJSON,
    ZaehlungskenngroessenDataFromJSONTyped,
    ZaehlungskenngroessenDataToJSON,
    ZaehlungskenngroessenDataToJSONTyped,
} from './ZaehlungskenngroessenData';
import type { BaseAsset } from './BaseAsset';
import {
    BaseAssetFromJSON,
    BaseAssetFromJSONTyped,
    BaseAssetToJSON,
    BaseAssetToJSONTyped,
} from './BaseAsset';

/**
 * 
 * @export
 * @interface ZaehlungskenngroessenAsset
 */
export interface ZaehlungskenngroessenAsset extends BaseAsset {
    /**
     * 
     * @type {string}
     * @memberof ZaehlungskenngroessenAsset
     */
    zaehlungId?: string;
    /**
     * 
     * @type {Array<ZaehlungskenngroessenData>}
     * @memberof ZaehlungskenngroessenAsset
     */
    zaehldaten?: Array<ZaehlungskenngroessenData>;
    /**
     * 
     * @type {boolean}
     * @memberof ZaehlungskenngroessenAsset
     */
    printFuss?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ZaehlungskenngroessenAsset
     */
    printRad?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ZaehlungskenngroessenAsset
     */
    printKfz?: boolean;
}



/**
 * Check if a given object implements the ZaehlungskenngroessenAsset interface.
 */
export function instanceOfZaehlungskenngroessenAsset(value: object): value is ZaehlungskenngroessenAsset {
    return true;
}

export function ZaehlungskenngroessenAssetFromJSON(json: any): ZaehlungskenngroessenAsset {
    return ZaehlungskenngroessenAssetFromJSONTyped(json, false);
}

export function ZaehlungskenngroessenAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZaehlungskenngroessenAsset {
    if (json == null) {
        return json;
    }
    return {
        ...BaseAssetFromJSONTyped(json, true),
        'zaehlungId': json['zaehlungId'] == null ? undefined : json['zaehlungId'],
        'zaehldaten': json['zaehldaten'] == null ? undefined : ((json['zaehldaten'] as Array<any>).map(ZaehlungskenngroessenDataFromJSON)),
        'printFuss': json['printFuss'] == null ? undefined : json['printFuss'],
        'printRad': json['printRad'] == null ? undefined : json['printRad'],
        'printKfz': json['printKfz'] == null ? undefined : json['printKfz'],
    };
}

export function ZaehlungskenngroessenAssetToJSON(json: any): ZaehlungskenngroessenAsset {
    return ZaehlungskenngroessenAssetToJSONTyped(json, false);
}

export function ZaehlungskenngroessenAssetToJSONTyped(value?: ZaehlungskenngroessenAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseAssetToJSONTyped(value, true),
        'zaehlungId': value['zaehlungId'],
        'zaehldaten': value['zaehldaten'] == null ? undefined : ((value['zaehldaten'] as Array<any>).map(ZaehlungskenngroessenDataToJSON)),
        'printFuss': value['printFuss'],
        'printRad': value['printRad'],
        'printKfz': value['printKfz'],
    };
}

