/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GeoPoint } from "./GeoPoint";
import type { Knotenarm } from "./Knotenarm";
import type { Laengsverkehr } from "./Laengsverkehr";
import type { PkwEinheit } from "./PkwEinheit";
import type { PositionUTM } from "./PositionUTM";
import type { Querungsverkehr } from "./Querungsverkehr";
import type { Verkehrsbeziehung } from "./Verkehrsbeziehung";

import { mapValues } from "../runtime";
import {
  GeoPointFromJSON,
  GeoPointFromJSONTyped,
  GeoPointToJSON,
  GeoPointToJSONTyped,
} from "./GeoPoint";
import {
  KnotenarmFromJSON,
  KnotenarmFromJSONTyped,
  KnotenarmToJSON,
  KnotenarmToJSONTyped,
} from "./Knotenarm";
import {
  LaengsverkehrFromJSON,
  LaengsverkehrFromJSONTyped,
  LaengsverkehrToJSON,
  LaengsverkehrToJSONTyped,
} from "./Laengsverkehr";
import {
  PkwEinheitFromJSON,
  PkwEinheitFromJSONTyped,
  PkwEinheitToJSON,
  PkwEinheitToJSONTyped,
} from "./PkwEinheit";
import {
  PositionUTMFromJSON,
  PositionUTMFromJSONTyped,
  PositionUTMToJSON,
  PositionUTMToJSONTyped,
} from "./PositionUTM";
import {
  QuerungsverkehrFromJSON,
  QuerungsverkehrFromJSONTyped,
  QuerungsverkehrToJSON,
  QuerungsverkehrToJSONTyped,
} from "./Querungsverkehr";
import {
  VerkehrsbeziehungFromJSON,
  VerkehrsbeziehungFromJSONTyped,
  VerkehrsbeziehungToJSON,
  VerkehrsbeziehungToJSONTyped,
} from "./Verkehrsbeziehung";

/**
 *
 * @export
 * @interface Zaehlung
 */
export interface Zaehlung {
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof Zaehlung
   */
  datum?: Date;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  jahr?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  monat?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  jahreszeit?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  zaehlart?: string;
  /**
   *
   * @type {GeoPoint}
   * @memberof Zaehlung
   */
  punkt?: GeoPoint;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  tagesTyp?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  projektNummer?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  projektName?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  kreuzungsname?: string;
  /**
   *
   * @type {boolean}
   * @memberof Zaehlung
   */
  sonderzaehlung?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Zaehlung
   */
  kreisverkehr?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof Zaehlung
   */
  kategorien?: Array<ZaehlungKategorienEnum>;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  zaehlsituation?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  zaehlsituationErweitert?: string;
  /**
   *
   * @type {number}
   * @memberof Zaehlung
   */
  zaehlIntervall?: number;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  wetter?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  zaehldauer?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  quelle?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  kommentar?: string;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  schulZeiten?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Zaehlung
   */
  suchwoerter?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof Zaehlung
   */
  customSuchwoerter?: Array<string>;
  /**
   *
   * @type {PkwEinheit}
   * @memberof Zaehlung
   */
  pkwEinheit?: PkwEinheit;
  /**
   *
   * @type {Array<string>}
   * @memberof Zaehlung
   */
  geographie?: Array<string>;
  /**
   *
   * @type {Array<Knotenarm>}
   * @memberof Zaehlung
   */
  knotenarme?: Array<Knotenarm>;
  /**
   *
   * @type {Array<Laengsverkehr>}
   * @memberof Zaehlung
   */
  laengsverkehr?: Array<Laengsverkehr>;
  /**
   *
   * @type {Array<Querungsverkehr>}
   * @memberof Zaehlung
   */
  querungsverkehr?: Array<Querungsverkehr>;
  /**
   *
   * @type {Array<Verkehrsbeziehung>}
   * @memberof Zaehlung
   */
  verkehrsbeziehungen?: Array<Verkehrsbeziehung>;
  /**
   *
   * @type {boolean}
   * @memberof Zaehlung
   */
  unreadMessagesMobilitaetsreferat?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Zaehlung
   */
  unreadMessagesDienstleister?: boolean;
  /**
   *
   * @type {string}
   * @memberof Zaehlung
   */
  dienstleisterkennung?: string;
  /**
   *
   * @type {PositionUTM}
   * @memberof Zaehlung
   */
  punktUtm?: PositionUTM;
}

/**
 * @export
 */
export const ZaehlungKategorienEnum = {
  Kfz: "KFZ",
  Sv: "SV",
  Gv: "GV",
  SvP: "SV_P",
  GvP: "GV_P",
  Pkw: "PKW",
  Lkw: "LKW",
  Lz: "LZ",
  Bus: "BUS",
  Krad: "KRAD",
  Rad: "RAD",
  Fuss: "FUSS",
  PkwEinheit: "PKW_EINHEIT",
} as const;
export type ZaehlungKategorienEnum =
  (typeof ZaehlungKategorienEnum)[keyof typeof ZaehlungKategorienEnum];

/**
 * Check if a given object implements the Zaehlung interface.
 */
export function instanceOfZaehlung(value: object): value is Zaehlung {
  return true;
}

export function ZaehlungFromJSON(json: any): Zaehlung {
  return ZaehlungFromJSONTyped(json, false);
}

export function ZaehlungFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Zaehlung {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    datum: json["datum"] == null ? undefined : new Date(json["datum"]),
    jahr: json["jahr"] == null ? undefined : json["jahr"],
    monat: json["monat"] == null ? undefined : json["monat"],
    jahreszeit: json["jahreszeit"] == null ? undefined : json["jahreszeit"],
    zaehlart: json["zaehlart"] == null ? undefined : json["zaehlart"],
    punkt: json["punkt"] == null ? undefined : GeoPointFromJSON(json["punkt"]),
    tagesTyp: json["tagesTyp"] == null ? undefined : json["tagesTyp"],
    projektNummer:
      json["projektNummer"] == null ? undefined : json["projektNummer"],
    projektName: json["projektName"] == null ? undefined : json["projektName"],
    kreuzungsname:
      json["kreuzungsname"] == null ? undefined : json["kreuzungsname"],
    sonderzaehlung:
      json["sonderzaehlung"] == null ? undefined : json["sonderzaehlung"],
    kreisverkehr:
      json["kreisverkehr"] == null ? undefined : json["kreisverkehr"],
    kategorien: json["kategorien"] == null ? undefined : json["kategorien"],
    status: json["status"] == null ? undefined : json["status"],
    zaehlsituation:
      json["zaehlsituation"] == null ? undefined : json["zaehlsituation"],
    zaehlsituationErweitert:
      json["zaehlsituationErweitert"] == null
        ? undefined
        : json["zaehlsituationErweitert"],
    zaehlIntervall:
      json["zaehlIntervall"] == null ? undefined : json["zaehlIntervall"],
    wetter: json["wetter"] == null ? undefined : json["wetter"],
    zaehldauer: json["zaehldauer"] == null ? undefined : json["zaehldauer"],
    quelle: json["quelle"] == null ? undefined : json["quelle"],
    kommentar: json["kommentar"] == null ? undefined : json["kommentar"],
    schulZeiten: json["schulZeiten"] == null ? undefined : json["schulZeiten"],
    suchwoerter: json["suchwoerter"] == null ? undefined : json["suchwoerter"],
    customSuchwoerter:
      json["customSuchwoerter"] == null ? undefined : json["customSuchwoerter"],
    pkwEinheit:
      json["pkwEinheit"] == null
        ? undefined
        : PkwEinheitFromJSON(json["pkwEinheit"]),
    geographie: json["geographie"] == null ? undefined : json["geographie"],
    knotenarme:
      json["knotenarme"] == null
        ? undefined
        : (json["knotenarme"] as Array<any>).map(KnotenarmFromJSON),
    laengsverkehr:
      json["laengsverkehr"] == null
        ? undefined
        : (json["laengsverkehr"] as Array<any>).map(LaengsverkehrFromJSON),
    querungsverkehr:
      json["querungsverkehr"] == null
        ? undefined
        : (json["querungsverkehr"] as Array<any>).map(QuerungsverkehrFromJSON),
    verkehrsbeziehungen:
      json["verkehrsbeziehungen"] == null
        ? undefined
        : (json["verkehrsbeziehungen"] as Array<any>).map(
            VerkehrsbeziehungFromJSON
          ),
    unreadMessagesMobilitaetsreferat:
      json["unreadMessagesMobilitaetsreferat"] == null
        ? undefined
        : json["unreadMessagesMobilitaetsreferat"],
    unreadMessagesDienstleister:
      json["unreadMessagesDienstleister"] == null
        ? undefined
        : json["unreadMessagesDienstleister"],
    dienstleisterkennung:
      json["dienstleisterkennung"] == null
        ? undefined
        : json["dienstleisterkennung"],
    punktUtm:
      json["punktUtm"] == null
        ? undefined
        : PositionUTMFromJSON(json["punktUtm"]),
  };
}

export function ZaehlungToJSON(json: any): Zaehlung {
  return ZaehlungToJSONTyped(json, false);
}

export function ZaehlungToJSONTyped(
  value?: Zaehlung | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    datum:
      value["datum"] == null
        ? undefined
        : value["datum"].toISOString().substring(0, 10),
    jahr: value["jahr"],
    monat: value["monat"],
    jahreszeit: value["jahreszeit"],
    zaehlart: value["zaehlart"],
    punkt: GeoPointToJSON(value["punkt"]),
    tagesTyp: value["tagesTyp"],
    projektNummer: value["projektNummer"],
    projektName: value["projektName"],
    kreuzungsname: value["kreuzungsname"],
    sonderzaehlung: value["sonderzaehlung"],
    kreisverkehr: value["kreisverkehr"],
    kategorien: value["kategorien"],
    status: value["status"],
    zaehlsituation: value["zaehlsituation"],
    zaehlsituationErweitert: value["zaehlsituationErweitert"],
    zaehlIntervall: value["zaehlIntervall"],
    wetter: value["wetter"],
    zaehldauer: value["zaehldauer"],
    quelle: value["quelle"],
    kommentar: value["kommentar"],
    schulZeiten: value["schulZeiten"],
    suchwoerter: value["suchwoerter"],
    customSuchwoerter: value["customSuchwoerter"],
    pkwEinheit: PkwEinheitToJSON(value["pkwEinheit"]),
    geographie: value["geographie"],
    knotenarme:
      value["knotenarme"] == null
        ? undefined
        : (value["knotenarme"] as Array<any>).map(KnotenarmToJSON),
    laengsverkehr:
      value["laengsverkehr"] == null
        ? undefined
        : (value["laengsverkehr"] as Array<any>).map(LaengsverkehrToJSON),
    querungsverkehr:
      value["querungsverkehr"] == null
        ? undefined
        : (value["querungsverkehr"] as Array<any>).map(QuerungsverkehrToJSON),
    verkehrsbeziehungen:
      value["verkehrsbeziehungen"] == null
        ? undefined
        : (value["verkehrsbeziehungen"] as Array<any>).map(
            VerkehrsbeziehungToJSON
          ),
    unreadMessagesMobilitaetsreferat: value["unreadMessagesMobilitaetsreferat"],
    unreadMessagesDienstleister: value["unreadMessagesDienstleister"],
    dienstleisterkennung: value["dienstleisterkennung"],
    punktUtm: PositionUTMToJSON(value["punktUtm"]),
  };
}
