/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ZaehlstelleConfigurationDTO
 */
export interface ZaehlstelleConfigurationDTO {
  /**
   *
   * @type {boolean}
   * @memberof ZaehlstelleConfigurationDTO
   */
  automaticNumberAssignment?: boolean;
  /**
   *
   * @type {string}
   * @memberof ZaehlstelleConfigurationDTO
   */
  linkDocumentationCsvFileForUploadZaehlung?: string;
}

/**
 * Check if a given object implements the ZaehlstelleConfigurationDTO interface.
 */
export function instanceOfZaehlstelleConfigurationDTO(
  value: object
): value is ZaehlstelleConfigurationDTO {
  return true;
}

export function ZaehlstelleConfigurationDTOFromJSON(
  json: any
): ZaehlstelleConfigurationDTO {
  return ZaehlstelleConfigurationDTOFromJSONTyped(json, false);
}

export function ZaehlstelleConfigurationDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ZaehlstelleConfigurationDTO {
  if (json == null) {
    return json;
  }
  return {
    automaticNumberAssignment:
      json["automaticNumberAssignment"] == null
        ? undefined
        : json["automaticNumberAssignment"],
    linkDocumentationCsvFileForUploadZaehlung:
      json["linkDocumentationCsvFileForUploadZaehlung"] == null
        ? undefined
        : json["linkDocumentationCsvFileForUploadZaehlung"],
  };
}

export function ZaehlstelleConfigurationDTOToJSON(
  json: any
): ZaehlstelleConfigurationDTO {
  return ZaehlstelleConfigurationDTOToJSONTyped(json, false);
}

export function ZaehlstelleConfigurationDTOToJSONTyped(
  value?: ZaehlstelleConfigurationDTO | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    automaticNumberAssignment: value["automaticNumberAssignment"],
    linkDocumentationCsvFileForUploadZaehlung:
      value["linkDocumentationCsvFileForUploadZaehlung"],
  };
}
