export enum AssetTypesEnum {
    TEXT = "TEXT",
    HEADING1 = "HEADING1",
    HEADING2 = "HEADING2",
    HEADING3 = "HEADING3",
    HEADING4 = "HEADING4",
    HEADING5 = "HEADING5",
    IMAGE = "IMAGE",
    PAGEBREAK = "PAGEBREAK",
    NEWLINE = "NEWLINE",
    DATATABLE = "DATATABLE",
    DATATABLE_MESSSTELLE = "DATATABLE_MESSSTELLE",
    ZAEHLUNGSKENNGROESSEN = "ZAEHLUNGSKENNGROESSEN",
}

export default AssetTypesEnum;
